# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/mapper/luks-87aa6dd8-4e74-4a6a-92a0-6d3d8df96a71";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-87aa6dd8-4e74-4a6a-92a0-6d3d8df96a71".device = "/dev/disk/by-uuid/87aa6dd8-4e74-4a6a-92a0-6d3d8df96a71";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/E0CB-6AC2";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault {system = "x86_64-linux";};
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
