_: let
  #=====================================================================#
  # FREETUBE BLOCKED CHANNELS
  #=====================================================================#
  # One flat list, sorted by lowercased name under LC_ALL=C and matched by
  # id. The label is cosmetic and the icon is a 1x1 transparent GIF: both
  # exist to stop FreeTube re-resolving every entry over the API. Grab a new
  # id from a channel page's "externalId" field, not the first "channelId".
  blankIcon = "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==";

  mk = id: label: {
    name = id;
    preferredName = label;
    icon = blankIcon;
  };
in {
  programs.freetube.settings = {
    channelsHidden = builtins.toJSON [
      (mk "UCYenDLnIHsoqQ6smwKXQ7Hg" "#Mind Warehouse")
      (mk "UCbD4USIyNGKCdL3cWah1GGg" "1010 WINS")
      (mk "UC3gNOGkS3MZn9IVqEjIlepw" "10minuteads")
      (mk "UCzF4Ryn8TKn64md77gS5Q5Q" "11Alive")
      (mk "UCu7G08TrwPx_0WH4M7OxjIQ" "12 News")
      (mk "UCFQyVljCrdof5Uqmo8p3c0Q" "13WHAM ABC News")
      (mk "UCup3etEdjyF1L3sRbU-rKLw" "24 News")
      (mk "UCq7OKQb6_1tbA73oSloIiZQ" "2WAY")
      (mk "UC295-Dw_tDNtZXFeAPAW6Aw" "5-Minute Crafts")
      (mk "UC2etEuPIfohP4P53wM0KImA" "5-Minute Crafts DIY")
      (mk "UC63mNFJR8EAb8wAIJwoCmTA" "5-Minute Crafts FAMILY")
      (mk "UC57XAjJ04TY8gNxOWf-Sy0Q" "5-Minute Crafts PLAY")
      (mk "UC1SaV8cJ5u5U9iEZS6QRbpg" "5-Minute Crafts TEENS")
      (mk "UC8-0f1PAWAqjdtk9ajwtmqg" "5-MINUTEN-TRICKS")
      (mk "UC2C3D_dv4QXgUQo9co9crPQ" "50M Videos")
      (mk "UCsN32BtMd0IoByjJRNF12cw" "60 Minutes")
      (mk "UC0L1suV8pVgO4pCAIBNGx5w" "60 Minutes Australia")
      (mk "UCw77677G3EAODp61b0izs7w" "6abc Philadelphia")
      (mk "UC5T7D-Dh1eDGtsAFCuwv_Sw" "7NEWS Australia")
      (mk "UCFuzExfO2fUVmNK5_COvsNg" "8 News Now — Las Vegas")
      (mk "UCmHzCFgOiVlZVT6ppYi7CpQ" "9 Fun Funny")
      (mk "UCIYLOcEUX6TbBo7HQVF2PKA" "9 News Australia")
      (mk "UCsgC5cbz3DE2Shh34gNKiog" "92 News HD")
      (mk "UCswGsKHdA5Njd_N4me3CMTg" "A&T Reacts")
      (mk "UCt4t-jeY85JegMlZ-E5UWtA" "Aaj Tak")
      (mk "UCyxcZgX1wNU-nk1yB9CvzSw" "Aaron Parnas")
      (mk "UC_vFLohxs5PkAxlk7Y6jEtw" "ABC 7 Chicago")
      (mk "UCfIjR00qhYUFkbWIugAAbGg" "ABC 7 News - WJLA")
      (mk "UCBi2mrWuNuyYy4gbM6fU18Q" "ABC News")
      (mk "UCVgO39Bk5sMo66-6o6Spn6Q" "ABC News (Australia)")
      (mk "UCunkVlKjHWCJ6OKfffus19Q" "ABC News 4")
      (mk "UCxcrzzhQDj5zKJbXfIscCtg" "ABC News In-depth")
      (mk "UCJSxCOEw2SopkddtjbE4ZaA" "ABC World News Tonight")
      (mk "UCVxBA3Cbu3pm8w8gEIoMEog" "ABC7")
      (mk "UCYUbNjkuE4lsr2v1Id2O1oA" "ABC7 News Bay Area")
      (mk "UC_2irx_BQR7RsBKmUV9fePQ" "ABN Telugu")
      (mk "UCH7nv1A9xIrAifZJNvt7cgA" "ABP MAJHA")
      (mk "UCRWFSbif-RFENbBrSiez1DA" "ABP NEWS")
      (mk "UC8DA4o0SyaGfyVaBLbF5EXg" "Adam Mockler")
      (mk "UCshCsg1YVKli8yBai-wa78w" "Agenda-Free TV")
      (mk "UCyps-v4WNjWDnYRKmZ4BUGw" "Airrack")
      (mk "UCV3Nm3T-XAgVhKH9jT0ViRg" "AJ+")
      (mk "UCKByY5zMbPjwJCtG9pL_1fw" "AK Creative Knowledge")
      (mk "UCNye-wNBqNL5ZzHSJj3l8Bg" "Al Jazeera English")
      (mk "UCYVinkwSX7szARULgYpvhLw" "Ali-A")
      (mk "UCgdywGAij6Nob5WealtDKXQ" "Ali-A Plays")
      (mk "UCAea1C_i5EL0Bu48FM-N6Qw" "Ali-A²")
      (mk "UCgEvEKgmQ-CHPIeOSaGCffw" "Amala Ekpunobi")
      (mk "UCTi3mRHhtqqrz5rXgw0F3mw" "Amazing Auditions")
      (mk "UCO9-nEt-Ymh8e-GbfK6HDOg" "Amazing News Today")
      (mk "UCBP39EHhfsTB4nAXpFQHjCg" "America First Drive")
      (mk "UCvubOhuUIhYoYnRyXHtcygQ" "American Bridge 21st Century")
      (mk "UCEnjHoBwhenfKY7s3xhvksg" "Among the Sidemen")
      (mk "UCvi6hEzLM-Z_unKPSuuzKvg" "ANC 24/7")
      (mk "UCtFQDgA8J8_iiwc5-KoAQlg" "ANI News")
      (mk "UC9lQD_Gk9ch7MsGypeiYN2w" "Anna Unboxing Toys")
      (mk "UCMmpLL2ucRHAXbNHiCPyIyg" "ARY News")
      (mk "UCekbhIcWL_x4bYVZPZZi0iw" "Asianet News English")
      (mk "UCjElJyiXmQXnWmceQ1JyKrA" "Asianet Suvarna News")
      (mk "UCMwJJL5FJFuTRT55ksbQ4GQ" "Asmongold Clips")
      (mk "UC8dxBg4gkVr-3XRinQrCfMw" "ASMR STATION")
      (mk "UC52X5wxOL_s5yw0dQk7NtgA" "Associated Press")
      (mk "UCWElIIlFx2JiyI9UVrbrEcw" "Atlanta News First")
      (mk "UCbgcYEdMsuypG2NJ-znBp3w" "ATN Bangla News")
      (mk "UCfU4-ArXuSX0tpyApyklMAg" "Axios")
      (mk "UCA4y9g_GRdNrZLH_u5LLSdw" "BanglaVision NEWS")
      (mk "UCihxJfIAt9NeXmBg393IfqA" "Basically Trending")
      (mk "UCBwejc-awS-mANgrkHQ5-6A" "BBC London")
      (mk "UC16niRr50-MSBwiO3YDb3RA" "BBC News")
      (mk "UCvhPRRiwI1_p4OBsY0yz6mg" "BBC News Africa")
      (mk "UCYUPBf8y9ggcnpBxCKZteHA" "BBC News Gujarati")
      (mk "UCN7B-QD0Qgn2boVH5Q0pOWg" "BBC News Hindi")
      (mk "UCUBIrDsIVzRpKsClMlSlTpQ" "BBC News Mundo")
      (mk "UCiTCB-B_weEmwHk7ifNobQw" "BBC News Telugu")
      (mk "UC3780MVtSV3Huj4si_CQvlQ" "BBC News සිංහල")
      (mk "UC6o-wWU-v2ClFMwougmK7dA" "BBC Politics")
      (mk "UCQXHTFnQYFTqN0MqmNh9EIA" "BBC World Service")
      (mk "UCUaT_39o1x6qWjz7K2pWcgw" "Beast Reacts")
      (mk "UCF1IUjGEr8h0vLwXk8yvtgQ" "Beast Theory")
      (mk "UCnQC_G5Xsjhp9fEJKuIcrSw" "Ben Shapiro")
      (mk "UCztGY3Qsxxk7JDSY3Q_iXsw" "Best HipHop Music")
      (mk "UCIS4oO_HUGtNDmUETH5vSCQ" "Best of Asmongold")
      (mk "UCBJh1lBd44OGUd5JrHZQvCQ" "Best of The Voice")
      (mk "UC4OvD2yIbofl9l4dIlqSNMw" "Bill O'Reilly")
      (mk "UCKkW8kJRYo0GXd1asPX3Z9Q" "Black Conservative Perspective")
      (mk "UCLml2_OPYFkrqs38TVrcU5g" "BlackConservative24")
      (mk "UCDmCBKaKOtOrEqgsL4-3C8Q" "Blaire White")
      (mk "UCKgJEs_v0JB-6jWb8lIy9Xw" "BlazeTV")
      (mk "UChirEOpgFCupRAk5etXqPaA" "Bloomberg News")
      (mk "UCUMZ7gohGI9HcU9VNsr2FJQ" "Bloomberg Originals")
      (mk "UChF5O40UBqAc82I7-i5ig6A" "Bloomberg Podcasts")
      (mk "UCIALMKvObZNtJ6AmdCLP7Lg" "Bloomberg Television")
      (mk "UCo-AjmVaa63_d1LXm2R5pMw" "Blueski YTP")
      (mk "UCpxf2P7fztkrT7NTtQRBG6A" "BluLoo - Kids Songs Label")
      (mk "UCjhSFO_csRvifc3VEJd7aog" "BlurryMemes")
      (mk "UCeifwTqGmxPR0v_z7Tm1BPw" "Bob The Train - Sing Along Nursery Rhymes")
      (mk "UCz2yxQJZgiB_5elTzqV7FiQ" "BOL News")
      (mk "UC56cowXhoqRWHeqfSJkIQaA" "Bounce Patrol - Kids Songs")
      (mk "UC1Cp5caGwHvJZxHoevGoDdA" "BRAIN TIME")
      (mk "UCDRIjKy6eZOvKtOELtTdeUA" "Breaking Points")
      (mk "UCF9LFWX5cdGHBg_FDm6tFrQ" "Breezy Politics")
      (mk "UCCuqvobH6ygNH-PMc8HhzGw" "Brian Karem")
      (mk "UCQANb2YPwAtK-IQJrLaaUFw" "Brian Tyler Cohen")
      (mk "UCpQ_q9AwSgzepjnVElVY0ag" "Brian Tyler Cohen News")
      (mk "UC4rlAVgAK0SGk-yTfe48Qpw" "BRIGHT SIDE")
      (mk "UCnBefwi-Yy5ueSmVI9--YcA" "Bright Side Quizzes")
      (mk "UCN-2Ou-LyHnSFydM9wrge5g" "Bruh Memes")
      (mk "UCFZ1Dv_jsdIIUgnJVVcbqKQ" "Brut America")
      (mk "UCfiWa7d6um8dAb9hSz2UD-w" "Bryton Myler")
      (mk "UChgW94oXxbYnLJ2FK_4jV5g" "bTw Clips")
      (mk "UC25LOJMIXwl1ZQyLeyuEezQ" "Buddha Clips")
      (mk "UCb--64Gl51jIEVE-GLDAVTg" "C-SPAN")
      (mk "UCLkOVcbrrsuljcL8ddI43VA" "Cam Higby")
      (mk "UCL0u5uz7KZ9q-pe-VC8TY-w" "Candace Owens")
      (mk "UC0Ra4Wt7u860wRJRyoRdhpg" "Capitol Central")
      (mk "UCc0AC8pAKI69wq7h2u-sAUg" "CatDany — Asmongold Highlights")
      (mk "UCuFFtHWoLl5fauMMD5Ww2jA" "CBC News")
      (mk "UCKjU3KzdbJE1EFcHVqXC3_g" "CBC News: The National")
      (mk "UCYI_ychRnL7sJrG6PUSBpQA" "CBN News")
      (mk "UCsIzhRSKbRtvBGsiLHfcGOA" "CBS 12 News - WPEC")
      (mk "UCUx2xAViYolMLCQAC8vgYvw" "CBS 13 News")
      (mk "UCMscWako8oDvpdF4pppku-g" "CBS 8 San Diego")
      (mk "UCi4fcBVyo4CAnmdgXeO-NvA" "CBS Boston")
      (mk "UCkBS_xU1WQ7FVsDoQ_OPeDg" "CBS Chicago")
      (mk "UCAeWdyKJXGWmVAXFpgLNNTg" "CBS Evening News")
      (mk "UC-SJ6nODDmufqBzPBwCvYvQ" "CBS Mornings")
      (mk "UC8p1vwvWtl6T73JiExfWs1g" "CBS News")
      (mk "UCVuFPbAjTi3mqpH-0veJRWg" "CBS Philadelphia")
      (mk "UCOEvClYLRZcT5bNCCI5eMKg" "CBS Pittsburgh")
      (mk "UCVT1tPkR-fUVlO652EcO3ow" "CBS Sunday Morning")
      (mk "UCxMXl9L79X1Mq_4iwCOyPFg" "CBS TEXAS")
      (mk "UCMKP8n1dUg-b84lfpb0mfdA" "CBS6 Albany")
      (mk "UCVhSS17jxUOueWmIUYfQcWg" "Celebs AgainstTrump")
      (mk "UCTrQ7HXWRRxr7OsOtodr2_w" "Channel 4 News")
      (mk "UCfaIu2jO-fppCQV_lchCRIQ" "Charlie Kirk")
      (mk "UC2TsKs8KgTLPZf5d0hcJcGQ" "Chat History Compilations")
      (mk "UCZGv4tzxhtawJRr1rgnVE1Q" "Checks and Memes")
      (mk "UCoGav6jgImtvjpogwhRr7Wg" "Chicago_News")
      (mk "UCGAmpBtWveYp0-3v9npnhvQ" "Chilling Scares")
      (mk "UCgT7YSxevs9LFP9YkpUiZjQ" "Chilling Scares Compilations")
      (mk "UCN64HIrZNqFQYZ2BuyY-4zg" "Chills")
      (mk "UCBnZ16ahKA2DZ_T5W0FPUXg" "ChuChu TV Nursery Rhymes & Kids Songs")
      (mk "UCmFjKeZx6ZAS0sp6EvQk8yg" "Clip Queue")
      (mk "UCYH24JU3ZgEIUWYGVgiVT7A" "ClipDemonn")
      (mk "UCdSS1S6jnCAqNz0ttO6boOw" "ClipNeverStop")
      (mk "UC7NOvys6F9lBsq619Zp7mig" "Clipped & Shipped")
      (mk "UC2sGbQRwKBT2Cvq8Bb4CGHw" "Clipper")
      (mk "UC2UIZ4x2UI_3EzFv8R4a2vA" "ClippyTV")
      (mk "UCoZLIB2r-UGWpP3nyO6CmAg" "Clips")
      (mk "UCntj4T04I3lUPpIta_b-lhw" "Clips machina")
      (mk "UCCibqL_mRwlXAXOwQvfAXjA" "ClipStorm")
      (mk "UCvMCgAYChG7O73rhLYxYjIg" "ClipsTycoon")
      (mk "UCrp_UI8XtuYfpiqluWLD7Lw" "CNBC Television")
      (mk "UCmRbHAgG2k2vDUvb3xsEunQ" "CNBC-TV18")
      (mk "UCupvZG-5ko_eiXAupbDfxWw" "CNN")
      (mk "UCTOoRgpHTjAQPk6Ak70u-pA" "CNN 10")
      (mk "UC_lEiu6917IJz03TnntWUaQ" "CNN en Español")
      (mk "UCKII0Ml9S5wneKbHswmUrIQ" "CNN Indonesia")
      (mk "UCef1-8eOpJgud7szVPlZQAQ" "CNN-News18")
      (mk "UCQRk6nOyu9w7CUHnrLtpIQA" "Coco Shark Nursery Rhymes")
      (mk "UCbCmjCuTUZos6Inko4u57UQ" "Cocomelon - Nursery Rhymes")
      (mk "UC193r5YXcpQJV34N99ZbhzQ" "Colion Noir")
      (mk "UCMNIAqEByphf0fNxI5z4LeA" "Comedy Compilations")
      (mk "UCj8ihBuBrtv9db75P4Ym3Ew" "Community W Clips")
      (mk "UCt-XpD0mhZVj2zUJb3i0b1Q" "Compilation Beast")
      (mk "UCYiYFWmU1ozUD8mTQUDmFHw" "Conservative Ladies")
      (mk "UCFfD9fWqkT4PNy7v6r8ilmg" "Conservative Twins")
      (mk "UCvpfautZTTR1opQB04T2fTA" "Conservative Vibes")
      (mk "UCGBR9bk3MCr0wrdP5iLlBBQ" "Conservative — Conservateur")
      (mk "UCXNSyuKeoiHOld1OS3kHuVg" "Conservatives")
      (mk "UCNvsIonJdJ5E4EXMa65VYpA" "ContraPoints")
      (mk "UCYJDvO5WReh6QTGHeM9kTYA" "Core Clips")
      (mk "UCBZEL0hguMlvNO-r3iZkd9w" "CouRage Reacts")
      (mk "UC0Te3dvrWqf9FCQWVpE0o9A" "covenent clips")
      (mk "UCFYFJ-y5p2_a45dAjuH5dOA" "Cozy Compilations")
      (mk "UCFZSV_So_OaXgXVzgu58tJQ" "cpac")
      (mk "UCtULrJ1vZEY5TyjAafuvGUw" "Crime History")
      (mk "UCHlo32FvGRPDk4U14VUyfYg" "critikal compilations")
      (mk "UCMAtX9eFBpwc4LtgvbqsOpQ" "CrowderBits")
      (mk "UCi7Zk9baY1tvdlgxIML8MXg" "CTV News")
      (mk "UCyI4gi0BtlKiUl6KgtuVIUw" "CTV Your Morning")
      (mk "UCclMpNhFKSDgcE07iumX4zw" "Current trendz")
      (mk "UCsPF3cApzCohxPp5oKdoWSQ" "CVS 3D Rhymes & Kids Songs")
      (mk "UCUmDAKhSZJY6qamQb9NGuJg" "Cyr Clips")
      (mk "UCCPNh1MBaHxolHEacvIEJMQ" "Daily Clips Central")
      (mk "UCHZ_SKrb-xmso0xyB8kt9rQ" "Daily Dose of Asmongold")
      (mk "UCW46hm2zWvhalt8XySF4nkg" "Daily Dose of Christ")
      (mk "UCdC0An4ZPNr_YiFiYoVbwaw" "Daily Dose Of Internet")
      (mk "UCZTu831eAXKZd-5w5onpiag" "Daily Dose Of SANITY")
      (mk "UCxk22we-ARqLaxwJK44r9Dg" "Daily Dose of Sodapoppin")
      (mk "UC0A9YrHgD5hZ2JXQrxRPHsw" "Daily Dose Of Wisdom")
      (mk "UCbCbwTq291Mi3kKnGVaEq5Q" "Daily Dose of xQc")
      (mk "UCj1v7Re3XMkYYv_6xMqjCGQ" "Daily Dose Simply")
      (mk "UCw3fku0sH3qA3c3pZeJwdAw" "Daily Mail World")
      (mk "UCroKPvbmaQKGK5tjtQsvaDw" "Daily Wire News")
      (mk "UC6KAzM2H6GFxI78kXfopgGg" "DailySpeedClips")
      (mk "UCwtmzAZ7sj-tU-l5j8YRjvQ" "Daliban Clips")
      (mk "UCmdR4DlZgP4rEslW12Dv_kg" "Dangerously Informed with Evie")
      (mk "UCvfqpaehdaqtkXPNhvJRyGA" "Dash Cam Owners Australia")
      (mk "UCZyRT83aj4Gs9jIF_qgmSgg" "Dashcam Diaries UK")
      (mk "UCEJCehMp7C6uIzARiCtm8tw" "Dashcam Drivers US")
      (mk "UCnetiRHPnIMBCm-yY4m69qA" "Dashcam Lessons")
      (mk "UCOS7jdle9zw_HnKW4ytZnDw" "Dashcam Nation")
      (mk "UCu3sKtOW9TGaErPsAYVPplA" "Dateline NBC")
      (mk "UCEfe80CP2cs1eLRNQazffZw" "Dave Smith")
      (mk "UCvixJtaXuNdMPUGdOPcY8Ag" "David Pakman Show")
      (mk "UCBbpLKJLhIbDd_wX4ubU_Cw" "DB Live")
      (mk "UCP3sSdrcCw7qC0qSrD8xOHQ" "DC News Now")
      (mk "UCKwucPzHZ7zCUIf7If-Wo1g" "DD News")
      (mk "UC7d2WmQqHxc9PTJyj3bVFgw" "Dean Withers")
      (mk "UCpLB7kBu9O5dbBKhaIOmqcQ" "DeFranco News Clips")
      (mk "UCWmMgbc1g6g5O8Tn_-k5qgA" "Democracy Docket")
      (mk "UCzuqE7-t13O4NIDYJfakrhw" "Democracy Now!")
      (mk "UCmA3zSO1wjBGwl61SeM4a3Q" "Democratic Reporter")
      (mk "UC-2MJlKSq9_pYk5-bdvMhnw" "Denver7")
      (mk "UC554eY5jNUfDq3yDOJYirOQ" "Destiny")
      (mk "UCUC1Y65XvU2n9lb6GvfAQ5g" "Destiny DGG Clips")
      (mk "UCtFZqbrEByTPN8VwC5dOhqA" "Destiny Highlights")
      (mk "UC-4SOzdo3fpAtsPKRB1OFvA" "Destiny Productions")
      (mk "UC9aFC44GD2t1fg_MXU3seuw" "Destiny Reacts")
      (mk "UC_eBfVTu6OhqQllZFd-WqGw" "Destiny Reacts 2")
      (mk "UCALsgRqlpl867WCkckre1Sg" "DestinyBites")
      (mk "UCWHbFbZkrCwNxHUVlPQGLXg" "destinyhqclips")
      (mk "UCeRrWJtDH_NUXQAwzCYpf1w" "DGG clips")
      (mk "UCMduNzt_T7-geFY4zc6mX7Q" "DGG Daily Clips")
      (mk "UCNer6UYFzkD7n3JhE4vgjFQ" "DGG_Clips")
      (mk "UCrj9ozSaeeIHBq7NMnqethQ" "DGGWRLD")
      (mk "UCu2fHtN58JgOUG3yaskmYrg" "DH BIHAR NEWS")
      (mk "UCdZmX-f3TDaRhnhM4KLM4SQ" "Doctor ER")
      (mk "UC6VTQKv0uHyKBTSDSCWVzFQ" "Dodgy Drivers")
      (mk "UCXs0PlIGUDSXfBaF7j-1euA" "Don Lemon")
      (mk "UCAql2DyGU2un1Ei2nMYsqOA" "Donald J Trump")
      (mk "UCkH7wZlokQlcIJYx1ZIoWRA" "DOSE OF INTERNET")
      (mk "UCjnYCUIym8wNRjLtZCc6gNg" "Dr Insanity")
      (mk "UCCsiAKRKcgzA_372WbXNBaw" "Dr. Steve Turley")
      (mk "UCrn0Yx2yWAFyxvrETsBP3GA" "Dream SMP Highlights")
      (mk "UCBLDgiZoqfB2JUniOmozUow" "Dream team best moments")
      (mk "UChZtBQK6ui5lW7FyMrxodRw" "Dreamy Toy ASMR")
      (mk "UCRdFBZwu7lZvqjfylbYsyMg" "DrumRollTony Reacts")
      (mk "UCnMBV5Iw4WqKILKue1nP6Hg" "Dunya News")
      (mk "UC-8t7yvYJaBy2QJ0O_Xllsw" "DUSK Reacts")
      (mk "UCknLrEdhRCp1aegoMqRaCZg" "DW News")
      (mk "UC4aFXAl4jiLPnUY3UFg4Wog" "El chico de los minutos")
      (mk "UCZFNk02M_0q-RWkFrIodiTw" "EmVale (Sodapoppin Highlights)")
      (mk "UCHZA_aJuGa4jEoJs6KW-_pw" "Energi Media")
      (mk "UCjXWBFQfzsrghD6a6EYm_Dw" "Epic Movie Nexus")
      (mk "UCxIlACNetQDzDfdpLFQCShw" "Exposed: UK Dash Cams")
      (mk "UCrlIS7z20CnVaCrMvdkig_g" "Eyewitness News ABC7NY")
      (mk "UC2x_qNZXKDxNP1j4jvHATRQ" "Face the Nation")
      (mk "UCXZpQgX1897wYDLtvzmgyIA" "Facts Verse")
      (mk "UCJlOeTniBwao0lUsa59tslA" "Fail Alert")
      (mk "UCSc1iZid09kojac24mPhdpg" "Fail Blast")
      (mk "UCesUN0qMfhDMO7Tacx-Py3g" "Fail Impact")
      (mk "UCPDis9pjXuqyI7RYLJ-TTSA" "FailArmy")
      (mk "UCUKOZiRKuxh6peXL19oKjZw" "FailArmy 2.0")
      (mk "UCZsA9Ml6P-GjA8XGiEAqQuA" "Failicious TV")
      (mk "UC-_mPIOcPS5EiR0gWG9go1g" "FailSide Moment")
      (mk "UCN-F3feiygBgRSfhMz8nWJQ" "Farfa Highlights")
      (mk "UC5dUUCs748wCYQl682LX6bg" "Farron Balanced")
      (mk "UCzI8K9xO_5E-4iCP7Km6cRQ" "Faye D'Souza")
      (mk "UC-0-SQSQhgTuXFMX994jUAA" "FC Memes")
      (mk "UCbGCHkeXk7hV09XkJL0atbg" "Fear& Clips")
      (mk "UCHyFuvaP40uvL0RE48NbsMw" "First Alert 6")
      (mk "UCz8QaiQxApLq8sLNcszYyJw" "Firstpost")
      (mk "UCeUXOovroVZ58AElb240R0A" "FitMC Highlights")
      (mk "UCw92QzuT_stf8jSaGWoKawQ" "FMW - Funny Moments")
      (mk "UCgAPgHNmQSG_ySHRiOVeF4Q" "FOCUS online")
      (mk "UCD4UWbxOOrFsxkMMfjYQ0VA" "Foltyn Reacts")
      (mk "UCg40OxZ1GYh3u3jBntB6DLg" "Forbes Breaking News")
      (mk "UCNjfNLnQYbjBEvnS8KFuyGQ" "FOX 10 Phoenix")
      (mk "UCHfF8wFnipMeDpJf8OmMxDg" "FOX 11 Los Angeles")
      (mk "UC5bKZHg4PzURMOWcvanl6nA" "FOX 13 Seattle")
      (mk "UCOGa-48fFt4cW0UnW5WSdRg" "FOX 2 Detroit")
      (mk "UC4OqEJz6oABzz_7nu29zF3A" "FOX 26 Houston")
      (mk "UCqdOvfSmM2NKRNE0FSbATuw" "FOX 29 Philadelphia")
      (mk "UCFmofUYwZd1Ibf_O3PF71jg" "FOX 32 Chicago")
      (mk "UCruQg25yVBppUWjza8AlyZA" "FOX 4 Dallas-Fort Worth")
      (mk "UCjHWv2DU5-HLpogAAr386DQ" "FOX 5 Atlanta")
      (mk "UCIjSUWHWp6KohfnR5OQTXnQ" "FOX 5 New York")
      (mk "UCHLyP4MuA-JAFBCwxXOEDdA" "FOX 5 Washington DC")
      (mk "UC5maSolHQX9er0BOxrzjMwA" "FOX 7 Austin")
      (mk "UClwddNv0Cr6SIEGkzVK886w" "FOX 9 Minneapolis-St. Paul")
      (mk "UCCXoCcu9Rp7NPbTzIvogpZg" "Fox Business")
      (mk "UCouaZqnOJay2Lacj8fomO3Q" "FOX NASHVILLE")
      (mk "UCG1CoynVOh5uj12qpDLQ7fQ" "Fox Nation")
      (mk "UCXIJgqnII2ZOINSWNOGFThA" "Fox News")
      (mk "UCqlYzSgsh5jdtWYfVIBoTDw" "Fox News Clips")
      (mk "UCh13rzqPKn5c24RU9tLz_TQ" "FOX News Podcasts")
      (mk "UCzHN-FjWDMsgfGPvRq7oy-Q" "FOX6 News Milwaukee")
      (mk "UCBy_C4Tg58BRzyKky45Pfow" "FOX8 WGHP")
      (mk "UCQfwfsi5VrQ8yKZ-UWmAEFg" "FRANCE 24 English")
      (mk "UCMPNAq4xRaz2XMtYSvm8oOA" "Freakin' Famous Auditions")
      (mk "UCuHeJgTeMf3r3wLv64hOUog" "Freedom Daily")
      (mk "UCRXnOs1rjfLMYrtZ-0n29NA" "FreedomToons")
      (mk "UCksHFQBGb1l5pQaNWAhUdzg" "Funny Catlos")
      (mk "UCw6s_N3IQI4sswTSfLoIUrA" "Funny Local News")
      (mk "UChFvSQf3Ut_yjq_FVY-wfmw" "FUNNY VİDEOS")
      (mk "UCllmCh9Zat9OaNyc3fRDJag" "Funny Zone")
      (mk "UCCKaR8KcXZsHVEH9BadXfDw" "Futcrunch Reacts")
      (mk "UCDulKGuVhHmRzikYCQ8Aa3Q" "gabi toys ASMR")
      (mk "UC0vn8ISa4LKMunLbzaXLnOQ" "GBNews")
      (mk "UCtIU87Ed-l2B7fMuqtGGA_g" "Generational News")
      (mk "UC_vt34wimdCzdkrzVejwX9g" "Geo News")
      (mk "UCvqtzdcURSqNjY9RQEK4XmQ" "Glenn Beck")
      (mk "UCrWmonkmTk5NbvmVnc7f70w" "Glenn Kirschner")
      (mk "UChLtXXpo4Ge1ReTEboVvTDg" "Global News")
      (mk "UCqYw-CTd1dU2yGI71sEyqNw" "GMA News")
      (mk "UCyVLweEwZE2A-qUL_J7ZlTg" "Golden Clips")
      (mk "UCWXPkK02j6MHW-4xCJzgMuw" "Golden State Times")
      (mk "UCOlq7FRJdf0QtfsPtwZ64Cg" "Golden Voices")
      (mk "UCH1oRy1dINbMVp3UFWrKP0w" "Good Morning America")
      (mk "UCq18eeL7D9Vd8DhjMcLh9QQ" "Good Morning Britain")
      (mk "UCe_Fx4EZAgKjDz0aQ_Y7hSA" "Got Talent Global")
      (mk "UClY29xvQr3YEx3TjeGj5MPg" "GRWM TikTok")
      (mk "UCoWKwd06OC0Y0XpvAa8jfdw" "Guardian Australia")
      (mk "UCIRYBXDze5krPDzAEOxFGVA" "Guardian News")
      (mk "UC-8_qAhNVG8G1wxONMnYr3Q" "GZERO Media")
      (mk "UCZZHPXsg6LopvdOKF7qM6cQ" "H3 Podcast Highlights")
      (mk "UCUPc_DkIN_I5pAu-6vignrg" "Hasan Moments")
      (mk "UC1hW1iEFDsW-6V0zC8jqVQA" "Hasan Reactions")
      (mk "UCtoaZpBnrd0lhycxYJ4MNOQ" "HasanAbi")
      (mk "UCuA9ZT6Uqsvc_K81f2Sk8Pg" "HasanAbi - Comps")
      (mk "UCc30Q1bAxLtfzeS_jh7J5wQ" "HasanAbi Archive")
      (mk "UCvN9kbIqjRhWaE0GVBLWi0w" "HasanAbi Archive")
      (mk "UCN7jo9su_7oDqwpfin8lgjw" "Hasanabi Clips")
      (mk "UCi1UIejGoWgSZWf15wHPj7g" "HasanAbi Compilations (Fan Channel - littlebear36)")
      (mk "UC8CKu-P14fDHzAFuyQCehWg" "HasanAbi Condensed")
      (mk "UC3B3Uj8LbGIhCQkB4YTZaow" "HasanAbi Corporate")
      (mk "UCCizpvXws0bY_VAf7DYRV5g" "HasanAbi Direct")
      (mk "UCK9fhebRQfvSfpI8780WpTQ" "HasanAbi Entertainment")
      (mk "UCQUx987JrYwNWOYCyor0ZPg" "HasanAbi Greatest Hits Clips")
      (mk "UCmCWQWDahJf2CKclt694cZw" "HasanAbi Highlights")
      (mk "UCz2n05fvYYoVTrhq1ZUnyHA" "HasanAbi Industries (Fan Channel)")
      (mk "UCBBQ9PIs8ARguuwVJZowGIg" "Hasanabi Productions")
      (mk "UCte9SD4XLBDFtRZD2dzj_jw" "HasanAbi Reacts")
      (mk "UCSi7XpA8swk2rJww6HEHA7g" "HasanAbi Rewind")
      (mk "UC3OTOy8vuu_r4wK80tpTmoA" "HasanAbi Searches for Humanity")
      (mk "UCB-MPptlCv5VCdIvAJxNwcA" "Hasanabi Yaps")
      (mk "UCJuJKGTbQDWq57ld5hjB6IQ" "HasanAbi_")
      (mk "UCoAxJF0J-kTqVS7HP0e7sfw" "HasanDaily")
      (mk "UC3e7LF-wOk7TzRTovnSJX-Q" "Hasanprop")
      (mk "UC4AScNTPAuPW0JtHtbfPwxQ" "HasMEMES")
      (mk "UCBnLE14tUHTDyDc8Xij9rAg" "Hawaii News Now")
      (mk "UCnbKOlm6H9njgmN-Yil90Rg" "Heather Cox Richardson")
      (mk "UC_N0S09lbFVoCNt8r1d1wuQ" "HeClippin")
      (mk "UCErKUCncCyBgEdxWAtrj5hg" "Hip Hughes (HipHughes)")
      (mk "UCwH-lORF3rBFef9gk8HGwUg" "Hollywood Remix")
      (mk "UCvfugNrodtC-9xpVMU0IQ_A" "Hook Moments")
      (mk "UCNKbE_ac5P_OaPraUoCxvKA" "Hooray Kids Songs & Nursery Rhymes")
      (mk "UCySy3wCTUWIa-m3Ogwh68Pw" "Horror Buddy")
      (mk "UCqQo7ewe87aYAe7ub5UqXMw" "House of Highlights")
      (mk "UCiiiNujtnT1ULcEXCWIFjQw" "Houston Public Media")
      (mk "UCBc13XYipnBIBE3Ff8QaaGg" "IBC24")
      (mk "UC_OLtzRJdg0MJfiqGWAAIHw" "IDEAS EN 5 MINUTOS")
      (mk "UCuN7anK2gOdqWAAENarYY2Q" "Idiot UK Drivers Exposed")
      (mk "UCfDIOBU2LwMah_rBxL9xjdQ" "Idiots In Cars Crash Compilation")
      (mk "UCuxgEyMeaks7HS5gAw6Tt7w" "ILTV Israel News")
      (mk "UCGeBogGDZ9W3dsGx-mWQGJA" "IMPAULSIVE")
      (mk "UCE9ZKI1b_PhVm3gejYuilhw" "IMPAULSIVE Clips")
      (mk "UCfC6JBx-VEcQYuWX4wCtMwQ" "INCREDIBLE LIFE HUB")
      (mk "UCYPvAwZP8pZhSMW8qs7cVCw" "India Today")
      (mk "UCttspZesZIDEwwpVIgoZtWQ" "IndiaTV")
      (mk "UC9k-yiEpRHMNVOnOi_aQK8w" "Inside Edition")
      (mk "UC3v3VpUyf34SLfN1IyUlMeA" "inside nepal news")
      (mk "UCHjm6wybRbldhqveS7c2WTA" "Insider News")
      (mk "UCV-oV8yecSfMZnzdKAhO_4A" "Interesting Facts")
      (mk "UCriIebMgM0wtH25S_6i6NeA" "Internet Anarchist Compilations")
      (mk "UCMZHX2oh_s9kFhmCRCNosuw" "Iowa's News Now")
      (mk "UCKMc9n9yHR3tCe0H2iIjVng" "iReddit for Sleeping")
      (mk "UCclAEvWIwKcUSSti1HDotrg" "iShow Instant Clips")
      (mk "UCyhOl6uRlxryALlT5yifldw" "J.J. McCullough")
      (mk "UC7ddSzBrkukSCJzMIXfGEdg" "Jack Cocchiarella")
      (mk "UCYHosdETLPp6dpJEsgIUTmw" "Jake Broe")
      (mk "UCcgVECVN4OKV6DH1jLkqmcA" "Jake Paul")
      (mk "UCXGSPtUJbczWecn9Ik3dW7A" "JasonTheWeen Clips")
      (mk "UCd62jsuGenFGkbObeRI9f4A" "JBS")
      (mk "UC25GHmlU1I-zbNcZe7a-aiQ" "Jemele Hill")
      (mk "UC_ntsgtfQEhAyzyflAueW9Q" "Jennifer Reacts")
      (mk "UCGHtep7hxIpz2D6RAQ8Kp0g" "Jeremy Boreing")
      (mk "UCUSySH2YjIwsDu2Hx6DWwTA" "Jesse Dollemore")
      (mk "UCPFj8_mICWyTrFMspnbrF4g" "JideClips")
      (mk "UCvj3hNvwrEgTRkeut7_cBAQ" "JiDion")
      (mk "UC8pOnl4XYXcKfZ_aWBO0o_A" "JiDionPremium")
      (mk "UCV98lDQ42J3PDjNQIpdoYmg" "JKW Compilations")
      (mk "UC-lfGGqb5hHLBqVnVnWyrsw" "Joe Bart VODs")
      (mk "UCmGSJVG3mCRXVOP4yZrU1Dw" "Johnny Harris")
      (mk "UCNJTWkcUJoMBamCr1IW097w" "Jolah Politics")
      (mk "UCKaCalz5N5ienIbfPzEbYuA" "Jordan Matter")
      (mk "UCN5tcDI7z6vN9s3p3n_JtoQ" "Jorge Ramos")
      (mk "UCP391YRAjSOdM_bwievgaZA" "Jovem Pan News")
      (mk "UCnxGkOGNMqQEUMvroOWps6Q" "JRE Clips")
      (mk "UCeTZ232XWIx95Z6k960UlAA" "Justin Reacts")
      (mk "UC1JAwKeDUjN2orv5t7LWODQ" "KARE 11")
      (mk "UCW-koFCP2fXeKnd2k3itkEg" "Katchii&NickClips")
      (mk "UCZl9z2UMvN9mwpUoU9-E9bA" "Katie Phang")
      (mk "UCmDTerxNU_gvCWLkIPkqghA" "KATU News")
      (mk "UCYOaYgTPCwEN9AvDjZ78HMA" "Kawaii Reaction")
      (mk "UC_rgiZZtwj0wGHAYNAfoBCg" "KBAK - KBFX - Eyewitness News - BakersfieldNow")
      (mk "UCjq9ElqnV7Df6NLb4oDHKqQ" "KCENNews")
      (mk "UCie7RmdcnvXA1FXHRJa7WtA" "KCTV5 News")
      (mk "UCagO3YGMBqDjrWBhw7wKuGA" "Keith Edwards")
      (mk "UC6FzYp_kEmTLkvIgw5Hssqw" "Ken Highlights")
      (mk "UCVnjt9mMx46gMUeTtONXimQ" "KENS 5: Your San Antonio News Source")
      (mk "UCjIngCN57O70jAo5Ez6Kmqw" "KERA")
      (mk "UClIYfCAhMAlacxT0e_sl1uA" "Kerajinan 5-Menit")
      (mk "UCa-x5T8TD99WYST764WhsEA" "KEZI 9")
      (mk "UC7Pq3Ko42YpkCB_Q4E981jw" "Kids TV - Nursery Rhymes And Baby Songs")
      (mk "UCx7bx9ViRETF04UE3dCxu5w" "Kidsberry - Nursery Rhymes ♫")
      (mk "UCp1KrVaZDZ7BOI_QBuTWWmg" "KING 5 Seattle")
      (mk "UCQfrWrZ6-XHGO0wgoODqXww" "KingofClipz")
      (mk "UC3mQV9qPc4pzzYHkhTlRA-A" "Kirk Takes Daily")
      (mk "UCPZbwdXrHUXXuaDDdRuZ40A" "Kirk Unpacked")
      (mk "UCu80jy-7aAhPxda8_u_sxVA" "Kitty Mashup")
      (mk "UChrpaYlmaVsVyEF0bTqmuHw" "KJRH -TV | Tulsa | Channel 2")
      (mk "UCKbj5d8f70i0AYLyiJ3YMXg" "KMPH FOX26 NEWS")
      (mk "UC__2_0RJ8XnHt2angfw6S1Q" "KOMO News")
      (mk "UCNXjJ4Igw2Ir8774eBNb4yA" "KRCG 13")
      (mk "UCVWQWc8PXy6Itt7YNrivOYw" "KRON 4")
      (mk "UCETE4rKzRRjqM0JaB7TlPpQ" "KSAT 12")
      (mk "UCwPzlQU2MqEQJWgqM_0VFKQ" "KSBW Action News 8")
      (mk "UCGmnsW623G1r-Chmo5RB4Yw" "KSI")
      (mk "UCrZY5AC-15w4KrndsJAFdtQ" "KSI CLIPS")
      (mk "UCMiY4t431lhXY4QtPZtzftQ" "KSIClips")
      (mk "UCinjnmQEwCddOudyCC1v7qA" "KTLA 5")
      (mk "UCVhtkN7-c8mA8GXEoxS4YQw" "KTVU FOX 2 San Francisco")
      (mk "UCFVUStJ4azXbWMhFO4yTELg" "KUTV 2 News Salt Lake City")
      (mk "UCYedMp8lKCCw9y0Qe3J9huQ" "KWTX News10")
      (mk "UCI8V0wOaigGdBpv5uk7DxxQ" "Kyoot")
      (mk "UCfIOSIFur-qFToVKahB0A6w" "L3WG Reacts")
      (mk "UC4Rrzu44rIpYtuVit90Kl5w" "LA Times Studios")
      (mk "UC5mNk1y0O1awxC8DucC8r0w" "Lalafun - Nursery Rhymes")
      (mk "UC3XTzVzaHQEd30rQbuvCtTQ" "LastWeekTonight")
      (mk "UCRl8O0ygm0fwpmM65kxxA3w" "Late Night Hasan")
      (mk "UCN4Z7nUtWpKo7P4MQwKSbkw" "Laugh Lobby")
      (mk "UC6iSAm2OgMS8e_RKuwnXzaw" "Laugh Trapped")
      (mk "UCxq9i443wiw2So5Cr82cqMQ" "Laughcable")
      (mk "UCb1Ti1WKPauPpXkYKVHNpsw" "LBC")
      (mk "UC9GGzAhhvhJO1hL10-BcgNA" "Le Huffington Post")
      (mk "UCJgZJZZbnLFPr5GJdCuIwpA" "Legal AF")
      (mk "UCJIfeSCssxSC_Dhc5s7woww" "Lex Clips")
      (mk "UCIr4vkCsn0tdTW2xZ1jRG1g" "Liberal Hivemind")
      (mk "UClFZWPaA12RUD8WYkR0yiBw" "Life Awesome")
      (mk "UCkBrtQrHN6Lc3vJUzXT0m6A" "Lincoln Square")
      (mk "UCWqJpFqlX59OML324QIByZA" "List 25")
      (mk "UCKAqou7V9FAWXpZd9xtOg3Q" "Little Baby Bum - Nursery Rhymes & Kids Songs")
      (mk "UCBMiY29jmxd9PGU74eT1xPg" "Little BoBo Nursery Rhymes - FlickBox Studios")
      (mk "UCy5tR9C0xM6tp7ha1Usq9Ag" "LIVE SNEAKO")
      (mk "UCJg9wBPyKMNA5sRDnvzmkdg" "LiveNOW from FOX")
      (mk "UClSzp3HiF1N1gz1E2xzxtGg" "Livestreams Memes")
      (mk "UCG8rbF3g2AMX70yOd8vqIZg" "Logan Paul")
      (mk "UCrN2VgX7U4iVmz40-z-kZMw" "loltyler1 CLIPS")
      (mk "UC4NALVCmcmL5ntpV0thoH6w" "LooLoo Kids - Nursery Rhymes and Children's Songs")
      (mk "UC2McAB2fbAkMIqOU4Dh0mLg" "Love ASMR")
      (mk "UCzAJnWovn2rpkjU_wkxOdqQ" "Ludwig Reacts")
      (mk "UCmbSGFM9OU8FwjxZCevr6zw" "Ludwig VODs")
      (mk "UCM05jgFNwoeXvWfO9GuExzA" "Luke Beasley")
      (mk "UCCT0-fxrMR-2Jv-DNs-MSHA" "Luke Stephens CLIPS")
      (mk "UCGLA2qQ_N_83Spcjz51d8HA" "MAGNO NEWS")
      (mk "UCwXrBBZnIh2ER4lal6WbAHw" "Mathrubhumi News")
      (mk "UCO01ytfzgXYy4glnPJm4PPQ" "Matt Walsh")
      (mk "UCWM3hAGXUIgqsdEkTeUxATA" "MattMorseTV")
      (mk "UC2qXepJ_mmGzyghwfxNlBOA" "Mavrik Edits")
      (mk "UC6EmR959HIts4gzdt80t3Xg" "Mega YTP")
      (mk "UCo8h0o9T3e-M3IOncmzjrkA" "MegaCompilations")
      (mk "UCKIrZr7WuPFgFy7OfkAuHOw" "MegaDrivingSchool - Dashcam Hub")
      (mk "UCzJXNzqz6VMHSNInQt_7q6w" "Megyn Kelly")
      (mk "UC9r9HYFxEQOBXSopFS61ZWg" "MeidasTouch")
      (mk "UCps7kPuenko3km-0RZcy6DQ" "Meme Reactions")
      (mk "UC-sHeRGtnOcqt5tXh1nG9OQ" "memes from hole")
      (mk "UC4b0ttz3Lh1mdcNOOM23R5A" "MemeSack")
      (mk "UCr4kgAUTFkGIwlWSodg43QA" "Michael Knowles")
      (mk "UCb2jveHvSiwdA0SfdIXqQBA" "Mickey Unboxing")
      (mk "UCkRzm-ELNPhz9l4sGRx3sMQ" "Mike Nellis")
      (mk "UCWZmCMB7mmKWcXJSIPRhzZw" "Miniminter")
      (mk "UCWCEYVwSqr7Epo6sSCfUgiw" "MIRROR NOW")
      (mk "UC2ZE6KuIyWjyOrGZFYXIIzg" "Mixed Reactions")
      (mk "UCfnpUsAB6Qb-HpEiCy3ZPiA" "Mo Funny")
      (mk "UC9MpuWZatMPIJVo_b_FCSKA" "MoonlightEdits")
      (mk "UCyeVfsThIHM_mEZq7YXIQSQ" "MoreAliA")
      (mk "UCWA4LJu3-gZfvvt6DN8-VFQ" "MoreAliA Top Videos")
      (mk "UCh5mLn90vUaB1PbRRx_AiaA" "MoreSidemen")
      (mk "UCBwSufNse8VMBvQM_rCSvgQ" "Morgz")
      (mk "UCBINYCmwE29fBXCpUI8DgTA" "MostAmazingTop10")
      (mk "UCDM5S7F6gocPxEDpHxHN_hQ" "Mr Horror")
      (mk "UCX6OQ3DkcsbYNE6H8uQQuVA" "MrBeast")
      (mk "UC4-79UOlP48-QNGgCko5p2g" "MrBeast 2")
      (mk "UCMSRW6Op77nGtl8pVZI12DQ" "MrBeast Clips")
      (mk "UCIPPMRA040LQr5QPyJEbmXA" "MrBeast Gaming")
      (mk "UCvIgMaAiW65MXfnuZif-MnQ" "MrLboyd Reacts")
      (mk "UC_jQ64mgxDbvATLv94lMwaw" "MrTop5")
      (mk "UCPod44VgEE39zjZe2ynhHKQ" "MrWinning Fun")
      (mk "UCaXkIU1QidjPwiAYu6GcHjg" "MS NOW")
      (mk "UCun4tg1BecN4PuxwZ6mL3NA" "National Review")
      (mk "UCmKKVuZrBfSGiuvtOuipoDA" "NBC Bay Area")
      (mk "UC2xLESFeytXO0j7pgVBf7fg" "NBC Montana")
      (mk "UCxCfoSInadl-4i3F70zDt1A" "NBC New York")
      (mk "UCeY0bbntWzzVIaj2z3QigXg" "NBC News")
      (mk "UCC_K68VPF-NEPBky01ClquA" "NBC News Learn")
      (mk "UCD158fKWVgwCkOooKEoJ1kw" "NBC10 Philadelphia")
      (mk "UC1VKVKhJLc7PjdPPVxTDk0Q" "NBC4 Washington")
      (mk "UCSWoppsVL0TLxFQ2qP_DLqQ" "NBCLA")
      (mk "UCZFMm1mMw0F81Z37aaEzTUA" "NDTV")
      (mk "UCwd8Byi93KbnsYmCcKLExvQ" "Negocios TV")
      (mk "UC5eXIV7HW4mHjdUOgMrpS5A" "neha ki news")
      (mk "UCZxoQbr2we2kXJ9WHJGOiGg" "NeverMissClip")
      (mk "UCrvhNP_lWuPIP6QZzJmM-bw" "New York Post")
      (mk "UCm1fqkJ-Tq64bQzM6VRMicQ" "New York Times Opinion")
      (mk "UCuzS3rPQAYqHcLWqOFuY0pw" "News 24")
      (mk "UCllyIkZaUy2zg-smrWiahow" "News 3 Las Vegas")
      (mk "UCHMxlXMj0RJIMta6CbgfT3A" "News 4 Reno")
      (mk "UCEW9foRmk4UdbzacT8KCYkA" "News Ganga")
      (mk "UCJ6IXLKR40-5gfS2qc6dtuQ" "News Without Borders")
      (mk "UC531MlZA5LUbeGwEN_zcppw" "News18 Bihar Jharkhand")
      (mk "UCPP3etACgdUWvizcES1dJ8Q" "News18 India")
      (mk "UC9IQhNgS43lmUdU-KdGyb0A" "News18 Urdu")
      (mk "UCO0akufu9MOzyz3nvGIXAAw" "News24")
      (mk "UCLK0Hvf6wP183FcmOprkrdw" "News_Junction_1")
      (mk "UCx6h-dWzJ5NpAlja1YsApdg" "Newsmax")
      (mk "UCCjG8NtOig0USdrT5D1FpxQ" "NewsNation")
      (mk "UCtbo6_eDG7zEtaOtcSltJkA" "NewsTamil 24X7")
      (mk "UC2a35q7eyzkfoIusBzdH4Hw" "Newsweek")
      (mk "UC7sL-CtxlyCPeZ0Oj95kvDQ" "NewsWest 9")
      (mk "UCytSP0M0Jdnw6qIy3Y-nTig" "NewsX Live")
      (mk "UCPFzA28Hw9tYDxXAeidDk6w" "Nick Freitas")
      (mk "UCF3D1D3RL6z8QJzgc6dtQRg" "Nidal Wonder")
      (mk "UCpZ88DWlKW0H_AYDaUZptcw" "Ninja Kidz TV")
      (mk "UCUoDnoHG6bpp4go2_XCS6VQ" "Nkenge - Fail Official")
      (mk "UCSUMDtO7urmLevH7W31sVLA" "Nmplol Clips")
      (mk "UCuJq3BQfvNfMpeoXnbpZz8A" "NODHasan")
      (mk "UC7wV9BwhmNksC2VxZbOqiZA" "Nogla & Terroriser React")
      (mk "UCRwA1NUcUnwsly35ikGhp0A" "Noticias Telemundo")
      (mk "UCloyKhGblgw3vhwDGzVVJNw" "NotSoHasanAbi")
      (mk "UCn4sPeUomNGIr26bElVdDYg" "NowThis Impact")
      (mk "UCumtYpCY26F6Jr3satUgMvA" "NTV Telugu")
      (mk "UCMEVZK5J38upc4XiRO3sqWQ" "NuNu Tv Nursery Rhymes")
      (mk "UCiq1e7slPdo1gG_rxt_QF5w" "Nursery Rhymes for Babies")
      (mk "UCA4plE8LqhERSNUiYDuVUFg" "Nursery Rhymes TV")
      (mk "UCn_uMY15GlwaPpx80-WjR6g" "Occupy Democrats")
      (mk "UCXaujLe65Dbe_7SUUyuhEnw" "Oddly Satisfying Motion")
      (mk "UCdTF__UASnN77R3VY1D0iXQ" "Office Blokes React")
      (mk "UC-yIj26cJVuw__d0u4rgt5w" "On The Go Clips")
      (mk "UCRRsHRG0qzS42KAK1YsEr-g" "One TikTok Mashup")
      (mk "UC8Xwcv1F_Hmg3NxsetJqdYg" "One Tiktok Mashup k")
      (mk "UCqTa3sNT6SfiQ2DQK_kuWlA" "Oneindia News")
      (mk "UCpJlmVOckoFYvK4Mf7tM4bQ" "Onyx Kids")
      (mk "UCV76mCbuKq3uyfg2BqsoC6w" "OTK Reacts")
      (mk "UCiNQdU1SwyOLUmnB9EoOusQ" "OTK VODs")
      (mk "UCR4z8ccOWNoUThB4VAMNBTg" "OUR STUPID REACTIONS")
      (mk "UCWjBqATYrifMWdw-J84k8XA" "Parker Highlights")
      (mk "UCHUcU1A9KhO9Sf4-8E5-ArA" "PAW YTP")
      (mk "UCGX7nGXpz-CmO_Arg-cgJ7A" "PBD Podcast")
      (mk "UC6ZFN9Tx6xh-skXCuRHCDpQ" "PBS NewsHour")
      (mk "UCL_S6BdUIyRbASIWecU0ksA" "Peepo Clips")
      (mk "UCIJ0lLcABPdYGp7pRMGccAQ" "People Are Awesome")
      (mk "UCpg9hTxmeuuglMYUz1MRiog" "Personal Development Clips")
      (mk "UCwPy85bZrLGYDRU3AOSK8Ow" "Phat Memer")
      (mk "UClFSU9_bUb4Rc6OYfTt5SPw" "Philip DeFranco")
      (mk "UCatt7TBjfBkiJWx8khav_Gg" "Piers Morgan Uncensored")
      (mk "UCQLRK5wiWGmzp4dnFt0arwA" "PinkNews")
      (mk "UCnWi59TPymx0_qt7PX3VeNA" "PIX11 News")
      (mk "UCKRoXz3hHAu2XL_k3Ef4vJQ" "Pod Save America")
      (mk "UCU9ccRjKksigQicSlIRlcOQ" "PodClip Vault")
      (mk "UC8Z-VjXBtDJTvq6aqkIskPg" "Polimer News")
      (mk "UCh7lorgEZg6fZsvg6bxgleA" "Political Gurus")
      (mk "UCAHVeeUYu70LGb0c0Rfb5Ig" "Political Voices Network")
      (mk "UCgjtvMmHXbutALaw9XzRkAg" "POLITICO")
      (mk "UCTFjmvpWb_gfIAFsEZqD3NQ" "Politicon")
      (mk "UCaJsUfWlqkiDxnoWrTK2iyg" "Politics & Paper")
      (mk "UCqJSzfY0TUADFHkw6tEOoOQ" "politics clips")
      (mk "UCbmoYCccdSpnWdmWW4b7BlA" "Politics Exchange")
      (mk "UCyzkxMLeZDcd_Qhzh6uMgbg" "PoliticsJOE")
      (mk "UCUrfzuazQPsjSTeq4x28QXA" "PoliticsNewsPolitics")
      (mk "UClGpc-n0Tt44FEkYvs7Tzew" "PoliticusUSA")
      (mk "UCbU6Rve0XMNZ2a2yaYgjlTA" "Pondering Politics")
      (mk "UC1bEP98I70i2S205aIQipDQ" "Pop & Politics")
      (mk "UCXgQjCFcgaooFb-gIT1Vo-g" "POPbuzz Memes")
      (mk "UCZWlSUNDvCCS1hBiXV0zKcA" "PragerU")
      (mk "UCKpSiUg_W-scoE6ltSp4TnQ" "President Sunday")
      (mk "UCgEzma_jxBinbVfd-KnNdLQ" "Progressive Exchange")
      (mk "UCjrEtsIBBV7TyJ9PPyo786w" "Proper Scary")
      (mk "UCyAZL7-AjKwybGHQ1FhTsxw" "Pulse Clips")
      (mk "UCmagDxvmbBpjzKg09LmBSow" "Punchbowl News")
      (mk "UCkHdoV_4R0JNMRMOF4uMF4g" "PURPLE CLIPPER")
      (mk "UCmyKnNRH0wH-r8I-ceP-dsg" "PuthiyathalaimuraiTV")
      (mk "UC4f_rZQPef5GlWhdl44DTrw" "QTCinderella Clips")
      (mk "UC8oNOD1ywI5KkpTIFhQcRCg" "Quality Highlights")
      (mk "UCzNPh2wueY888Tt3vgzxk2Q" "Quiz Plug")
      (mk "UCnrcd7yBB8guNPqKuwtdtNA" "Quote")
      (mk "UCW7DEppFdRIbcuYREFiMJAQ" "Rare Memes")
      (mk "UC0v-tlzsn0QZwJnkiaUSJVQ" "REACT")
      (mk "UCd7SCDxPEIYdXHkrpEmBXFA" "Real _ news")
      (mk "UCy6kyFxaMqGtpE3pQTflK8A" "Real Time with Bill Maher")
      (mk "UCpJ7ZS8hK-IOeciv952Xhug" "Really American")
      (mk "UCuMo0RRtnNDuMB8DV5stEag" "Rebel HQ")
      (mk "UCoJhK5kMc4LjBKdiYrDtzlA" "Redacted")
      (mk "UCEgBtMWERAfed_Q5YweMEng" "Reddit Clips")
      (mk "UC3IqRNrIM0kRfApcrDEra5w" "Reddit in Blocks")
      (mk "UCGF9LaOb7QFvjADRcZEQhXg" "Reddit stories")
      (mk "UCijeVTDybmGrWNJN9a6xU8w" "Reddit TTS")
      (mk "UCgUPH_Lbwu7NYAICg4FaQNQ" "Reddit_Rewind")
      (mk "UC8-P63-J6DhWzj9dwFemKcw" "Redditor")
      (mk "UC2CI0BYmLTk2fttMI63TvzA" "RedditWhispers")
      (mk "UC9infsKo33_2LUoiqXGgQWg" "Renegade Cut")
      (mk "UCFx1nseXKTc1Culiu3neeSQ" "REPORTER LIVE")
      (mk "UChqUTb7kYRX8-EiaN3XFrSQ" "Reuters")
      (mk "UCm3oV6IfDHfCJbgvrVqvPQQ" "RevIt Up Dashcam")
      (mk "UCDo9msNItILnyF_Y2eHaNQg" "RiceGum")
      (mk "UCA4sF2INOBVv2aNglhNjNNA" "RICH CRAFTS")
      (mk "UCHqC-yWZ1kri4YzwRSt6RGQ" "Right Side Broadcasting Network")
      (mk "UCjXB7nX8bL2U2sje8d212Yw" "Roland S. Martin")
      (mk "UC8FpG11hqfqr8n9a9LcxKzA" "RR&BD Driving School")
      (mk "UCydcMzXFa0hq3mktq0s9dwg" "Sad Boyz Highlights")
      (mk "UCQ_FATLW83q-4xJ2fsi8qAw" "Sakshi TV Live")
      (mk "UCTln5ss6h6L_xNfMeujfPbg" "Scripps News")
      (mk "UCJm2TgUqtK1_NLBrjNQ1P-w" "Second Thought")
      (mk "UCldfgbzNILYZA4dmDt4Cd6A" "Secular Talk")
      (mk "UCpgILFSGxY-9mQR79fLSt2A" "Senate Democrats")
      (mk "UCJ6o36XL0CpYb6U5dNBiXHQ" "Shaun")
      (mk "UC0aanx5rpr7D1M7KCFYzrLQ" "Shoe0nHead")
      (mk "UCJA9mOUHSsFlU6MPBvA99lg" "SHORT FACTS")
      (mk "UCcaa_Fc-Ei7r_0iQxbUAABg" "ShumbagalaClips")
      (mk "UCDogdKl7t7NHzQ95aEwkdMw" "Sidemen")
      (mk "UC1J9rH410gWoZ8ZnZv1QV1g" "Sidemen Moments")
      (mk "UCjRkTl_HP4zOh3UFaThgRZw" "SidemenReacts")
      (mk "UCoMdktPbSTixAyNGwb-UYkQ" "Sky News")
      (mk "UCQQ8ZCMDgfoiOnz3zMcwSaA" "Sleep videos")
      (mk "UCQ2Zh_7fnOSW9BegOmkwOtg" "SmartHER News")
      (mk "UC0cn3iEArxt-PbQmTs1jIew" "Sodapoppin Clips")
      (mk "UCumPSFE68y-cpUg_qMJBx7w" "Sodapoppin Clips")
      (mk "UCwGBF20IvS4CgkKToDtCJdw" "Sodapoppin Clips")
      (mk "UCOYk2h29-mO5m6WfoLFHrrA" "Sodapoppin VODS")
      (mk "UCcG6gZVYiC-y8xwEK3DiWaQ" "SodapoppinClips")
      (mk "UC6i4XtwlConYT_8v8djayeg" "Someclipz")
      (mk "UCXXq3MmNAQ4CRbu41kXXjWA" "Sonic Asmr")
      (mk "UCS5M7wUB-ugaDtdFY5_pbJA" "Sovereign Citizen Encounters")
      (mk "UCr0CLei2lv9tqPQa1b1VOfw" "SpeedEditsHD")
      (mk "UCEcMWs6GudljuLw0-Umf97A" "Spirit Science")
      (mk "UCpB959t8iPrxQWj7G6n0ctQ" "SSSniperWolf")
      (mk "UCMpW4kMfP8yPzFqHUqX3h2g" "SSSniperWolf Gaming")
      (mk "UCZpjmnFZANDsgzQQkZwMJ7w" "SSSniperWolf Gaming Top Videos")
      (mk "UCGovFxnYvAR_OozTMzQqt3A" "SSSniperWolf Top Videos")
      (mk "UC5oXV8H8d8LiX76CPLwlVSw" "Star Clips")
      (mk "UCGgK-ff3W-B8IbQ0KyHSpLA" "Stay Wild Reacts")
      (mk "UCIveFvW-ARp_B_RckhweNJw" "StevenCrowder")
      (mk "UCETtrBJPkb_vy-0J56OTQyw" "Stream Clipper")
      (mk "UClDtG4S7HtwnPktmu3ZIqkA" "StreamClipper")
      (mk "UCHbZa_koHjqy_H5Wz3AGjjg" "Streamer Highlights")
      (mk "UCr1-1RNDJLhWqcLqz14xjxQ" "Streamer Moments")
      (mk "UCqOPTuLESVvDJtxooEJ9tVw" "StreamOnCNN")
      (mk "UCYlh4lH762HvHt6mmiecyWQ" "Sun News")
      (mk "UCLsooMJoIpl_7ux2jvdPB-Q" "Super Simple Songs - Kids Songs")
      (mk "UCfLUpsmJ3v99NEbLTE9Dzng" "supertf clips")
      (mk "UCSFy-1JrpZf0tFlRZfo-Rvw" "Sydney Watson")
      (mk "UC2FuqJOGxHdoEjwyJ1LUxSA" "sylix • xQc VODS")
      (mk "UCSWwb_YyNB8vuC1VDcfPPaQ" "Talent Recap")
      (mk "UCu1wUSjVGL2azTLNN_rqo3Q" "Talent Replay")
      (mk "UCbDSo4C1f1SnKsAzHOpTdUA" "Talent Rewind")
      (mk "UCi70qFIwSUyMgxT5ZjR2zQg" "TALENTKINGHD")
      (mk "UCm0yTweyAa0PwEIp0l3N_gA" "TalkTV")
      (mk "UCmuTmpLY35O3csvhyA6vrkg" "TeleSUR English")
      (mk "UCnYXk91SONNe5Sobp0fdWpQ" "Terror Time")
      (mk "UCY2SXwuYKI2C2OUcXL90cFw" "ThatsVaddy Clips")
      (mk "UCK0z0_5uL7mb9IjntOKi5XQ" "The Atlantic")
      (mk "UCNXD5enYf0UZXccisoxLy0A" "The Biblical Conservative")
      (mk "UC2CBT8IHw9ZL4RjNevC8h0Q" "The Boys React")
      (mk "UCG4Hp1KbGw4e02N7FpPXDgQ" "The Bulwark")
      (mk "UCj6EKBe990fanr4MSh45Alw" "The Canadian Press")
      (mk "UCcukTqc1cJJ4K3c4uzxTzjA" "The China Show")
      (mk "UCGB-czkAt6nLd3UrQ1eD0uw" "The Chris Cuomo Project")
      (mk "UC7qZ_e097NBkgOljy1joVRA" "The Daily Beast")
      (mk "UCwWhs_6x42TyRM4Wstoq8HA" "The Daily Show")
      (mk "UCHqkXbgqrDrDVInBMSoGQgQ" "The Daily Signal")
      (mk "UCaeO5vkdj5xOQHp4UmIN6dw" "The Daily Wire")
      (mk "UCACRim7l0tmc5lhNnDQyUvQ" "The Dallas Morning News")
      (mk "UCl9roQQwv4o4OuBj3FhQdDQ" "The Damage Report")
      (mk "UCMj4JuasdvxSXbOupkFF99A" "The Dashcam Report")
      (mk "UClkO4MArT2WKWj32YDD_-Ew" "The Democrats")
      (mk "UCHWLd6ty8uiAjTFsJHQVFJw" "The Fail Report")
      (mk "UCmk6ZFMy1CT80orXca4tKew" "The Financial Express")
      (mk "UCQVhgOxzt5W1fZhOd0l2E6g" "The First")
      (mk "UCSRRURbKlPf1HwPUhjmufTg" "The Free Press")
      (mk "UCHpw8xwDNhU9gdohEcJu4aA" "The Guardian")
      (mk "UCETtxFEHvxHm_lg99SA8cjg" "The HasanAbi Library (fan Channel)")
      (mk "UC5bEfSFTYQVfLCwkhBt8NtQ" "The Heritage Foundation")
      (mk "UCPWXiRWZ29zrxPFIQT7eHSA" "The Hill")
      (mk "UC7Q4rvzJDbHeBHYk5rnvZeA" "The Humanist Report")
      (mk "UCfdNM3NAhaBOXCafH7krzrA" "The Infographics Show")
      (mk "UC3M7l8ved_rYQ45AVzS0RGA" "The Jimmy Dore Show")
      (mk "UCvKGiwSwqd92gUoxJI3W_fw" "The Joy Reid Show")
      (mk "UCx8Z14PpntdaxCt2hakbQLQ" "The Lallantop")
      (mk "UC-3jIAlnQmbbVMV6gR7K8aQ" "The Majority Report w/ Sam Seder")
      (mk "UC3EmxrWVl7K8xBH_UVIWY4Q" "The Mirror")
      (mk "UCYz8MBZdBbncYv-q8Eh92RQ" "The Narrative Brief")
      (mk "UCvAnclelY8eSq8GyPE19KTw" "The National Desk")
      (mk "UCqnbDFdCpuN8CMEg0VuEBqA" "The New York Times")
      (mk "UCDGknzyQfNiThyt4vg4MlTQ" "The Obama White House")
      (mk "UC535XrYeD-S3ZAjfCZ8hXNw" "The Quiz Show")
      (mk "UCo9oQdIk1MfcnzypG3UnURA" "The Rational National")
      (mk "UCH8n_3TMzBvsdj6XpNo0egQ" "The Reaction Room")
      (mk "UCII84rxnNkEjtk1zC3qTtbg" "The Rest Is Politics US")
      (mk "UCYWIEbibRcZav6xMLo9qWWw" "The Ring of Fire")
      (mk "UC_wpodAWmXyQanNVof8vyFg" "The Soy Pill")
      (mk "UCIzXayRP7-P0ANpq-nD-h5g" "The Sun")
      (mk "UCPgLNge0xqQHWM5B5EFH9Cg" "The Telegraph")
      (mk "UCTjDhFuGXlhx9Us0gq0VK2w" "The Trump Report")
      (mk "UCHmb7OFncrZ7BRpMxTzsP4g" "The US Sun")
      (mk "UCdUD6racxisHiSX9iWFcuug" "The Vaush Pit")
      (mk "UCeH6qE4V7n5tVwP7NkdrtJg" "The View")
      (mk "UC2CGbJNDsxYDD_5k3P4Ouzg" "The Voice Europe")
      (mk "UCJYtYkiGldqX6Ne938j-k2g" "The Voice Global")
      (mk "UC6dtjRVZ61_Y-HohzJ24ObA" "The Voice Norway")
      (mk "UCyYRmqY8pIZXCqJ6hwBk5xg" "The Voice: Best Blind Auditions")
      (mk "UCK7tptUDHh-RYDsdxO1-5QQ" "The Wall Street Journal")
      (mk "UC8BxSGcBKriJvoeyKOnJ6tA" "The Washington Examiner")
      (mk "UCQlJ7XpBtiMLKNSd4RAJmRQ" "The Weekly Show with Jon Stewart")
      (mk "UCYxRlFDqcWM4y7FfpiAN3KQ" "The White House")
      (mk "UC1yBKRuGpC1tSM73A0ZjYjQ" "The Young Turks")
      (mk "UCfDdlNLRVb1h3_7Xh-WhL3w" "TheDC Shorts")
      (mk "UC4Hdb26_xnPQsntwLazMqYw" "TheLearningStation - Kids Songs and Nursery Rhymes")
      (mk "UCj7FOK8z5nKmvMjJS3YwNSA" "TheMemePlug")
      (mk "UCbwMZHCMpBiOWfYLBOH-9Qw" "TheOfficialLoganPaul")
      (mk "UCbjBOso0vpWgDht9dPIVwhQ" "Thom Hartmann Program")
      (mk "UCStCUMvCw067Nw5uSlbyDsw" "THV11")
      (mk "UC56RKHnIutm-L99-fhxulDA" "Tik Tok Now")
      (mk "UCQnwyBLqXRmxdjBiCIm7TWA" "TIKTOK COMPILATION")
      (mk "UCbq3nNZKry1KjS6n0jw6S_Q" "TikTok CREEPY")
      (mk "UCmGu_-no0e5z9PwJsXjM41A" "TikTok Dance")
      (mk "UCh3NRV_qIKoXfYhYwF0zCVg" "TikTok History")
      (mk "UCmw-JM4ToC24PSpKrJEI4dQ" "TikTok HOME")
      (mk "UCTsph53p_wsu6ZYBMQ36fmg" "tiktok stories !!")
      (mk "UCPBJ6bLj-uCKaeh7qSJkXkg" "tiktokforyou")
      (mk "UCjRXO-HSl5XpuF-cWvtMV_g" "Tim Black TV")
      (mk "UCe02lGcO-ahAURWuxAJnjdA" "Timcast")
      (mk "UC8Su5vZCXWRag13H53zWVwA" "TIME")
      (mk "UC6RJ7-PaXg6TIH2BzZfTV7w" "Times Now")
      (mk "UCMk9Tdc-d1BIcAFaSppiVkw" "Times Now Navbharat")
      (mk "UCw8Fc5R0Q5yyS3KrDCPM3xg" "Times Now World")
      (mk "UCckHqySbfy5FcPP6MD_S-Yg" "Times Of India")
      (mk "UCF-VP3b3oH0XASqsLI5rnLw" "Times Radio")
      (mk "UCsD1m31dFYxpmEixmWT6bGg" "Tina Toys ASMR")
      (mk "UCxaZ0oJZJlRQ8wQihzwzsWg" "Tina Unboxing Toys")
      (mk "UC4aqtbSmF7jDxOeiD19eZCA" "Tiny Clipper")
      (mk "UC-uhvujip5deVcEtLxnW8qg" "TLDR News Global")
      (mk "UCNF3YWH9ud6I_D97bNnZngg" "TNT Reactions")
      (mk "UChDKyKQ59fYz3JO2fl0Z6sg" "TODAY")
      (mk "UCGJnHg5-o822HDiaACGXaCw" "Tommyinnit Clips")
      (mk "UCnMp_7DVSGuzNfTpNKWVldw" "TommyKayVODs")
      (mk "UC9gVCa6ap-KDayMRPg5wjIg" "TommyVODS")
      (mk "UCeBWh-0p7vgBeD6HOHBpfwQ" "Top 10 Talent")
      (mk "UC9VXLLbZ3E0_ypPYXkqoJcA" "Top 5 Ranking funny moments")
      (mk "UCrykHmaD5dq-2di1d5kIkIA" "Top Clips")
      (mk "UCbAlVnKhbGLK78GsSemQXxw" "Top Fives")
      (mk "UCD2GdZBCsUa0TIssLai6Skw" "Top Talent")
      (mk "UCArcrGQYzJhB_IfEla_XN4Q" "Top Things")
      (mk "UCDnEa2HC2eeT-cN3pAKnNTw" "Top Viral Talent")
      (mk "UCLKcN0HvTwCpOPryf9VyXRA" "Top World Talent HD")
      (mk "UCYn6CZe5UGIyPe9WJb0pTrg" "Top5Gaming")
      (mk "UCVrt7vJmcb-2rG72anTsh9A" "Top5Moments")
      (mk "UCB58HbhbM93ygXfnCJ1K2kA" "Topper Guild Highlights")
      (mk "UCBtjFm7bmGzUb3xvYhFSHuQ" "Touchy Reactions")
      (mk "UCta3MuD7omvsJyb-SMQkKOQ" "Trend Max")
      (mk "UCkUhqxxc9kBGRqIP7cUK3-w" "TREND SPHERE")
      (mk "UC7oPkqeHTwuOZ5CZ-R9f-6w" "Triggernometry")
      (mk "UC0KZo93qTFZaE3Rs0v_TB4w" "Troom Teen")
      (mk "UCWwqHwqLSrdWMgp5DZG5Dzg" "Troom Troom")
      (mk "UCbtTiuoDeSidOlUIbiMTbig" "True crime stories of all time")
      (mk "UC9AKA0PYiGCSPqfCEMaKtag" "Trump")
      (mk "UCMFliQOE-q8oXuW6RgqyBbg" "TT compilations")
      (mk "UCGttrUON87gWfU6dMWm1fcA" "Tucker Carlson")
      (mk "UCmbm72l60p3OH4aL4o7BFeA" "Turning Point UK")
      (mk "UCVrK_pMRp_q8IelpfUCTGLQ" "Turning Point USA")
      (mk "UCIqMBrPv0zRqJaUTHHyvZ6g" "Twinkle Little Songs - Nursery Rhymes")
      (mk "UCwNJt9PYyN1uyw2XhNIQMMA" "TYT Investigates")
      (mk "UCIbaZHZP3VqXRfJlAtJv6Vw" "U.S. Democratic Socialists")
      (mk "UCfZwNd8i7spJmLr4qq1_Gyw" "UK Dash Cameras")
      (mk "UCVygVPu30g93cY0sIbqsSNA" "Unboxing Playset")
      (mk "UCm2fwZgh4UrXIuo2HERvkrg" "Unboxing Xtra")
      (mk "UCzOrrheF99HIxv9Do2K5ghw" "UNIVISION LOS ANGELES")
      (mk "UCDTbhmttw6LkaoMSInZ-e8w" "Unwanted Highlights")
      (mk "UC3055Mg81-5X5l9t_DFAAxQ" "Urban Legends")
      (mk "UCP6HGa63sBC7-KHtkme-p-g" "USA TODAY")
      (mk "UCccLJcTFQAVcFGOWcF1DTtw" "V U Meme")
      (mk "UCIHdDJ0tjn_3j-FS7s_X1kQ" "Valuetainment")
      (mk "UCufcqvN5lw1XlG4-4iQR6YA" "vanillamace vods")
      (mk "UC1E-JS8L0j1Ei70D9VEFrPQ" "Vaush")
      (mk "UCnJo_lQSjVHCwUzUtVqde4Q" "Vaushite")
      (mk "UCn8zNIfYAQNdrFRrr8oibKw" "VICE")
      (mk "UCLkatK-rdCD9S6mABaQveEg" "Vine Mansion")
      (mk "UCod_t2sXD_gRI11yFFGkoXg" "Vines best fun")
      (mk "UC7Em55vyn2rzJQEStMZaecQ" "Viral Central TV")
      (mk "UC1_yfBLZ2FNOGz9cacSibvw" "Viral Crimes")
      (mk "UCmSPDMxfLphFJlZirsHbP0A" "Viral Feed")
      (mk "UClkXLaqttTs8YJHyuZ_wVKA" "Viral Memes")
      (mk "UC-NPQYmHM9AagZg2GfaiiBw" "Viral Now")
      (mk "UCj6Ed6HiG3EHJP80EQ1L9bg" "Viral Sap")
      (mk "UCA4s5lwjkmmR9Coh1-FGItQ" "Viral Trends Daily🌏")
      (mk "UCl_LO48OHG9K8A3Js8Hj40g" "Viral Voices")
      (mk "UCJsgJk0Nwst62HikqF8IxzQ" "Viralmashup Edits")
      (mk "UCYCFeGE0Y8QlWJsho8-r1_w" "ViralVideoLab")
      (mk "UC6IuAwaMYPwABARv0AkjAoQ" "Voice Finest")
      (mk "UCLXo7UDZvByw2ixzpQCufnA" "Vox")
      (mk "UCw0_9Iih3qM_I_gFLrJeNRg" "Wall Street Journal Opinion")
      (mk "UCHd62-u_v4DvJ8TCFtpi4GA" "Washington Post")
      (mk "UC2s0uKOc2WgB9eGta7cUUEA" "Washington Week PBS")
      (mk "UCAEa98uGVYj2j1at0MRNSCw" "WasLudwigClips")
      (mk "UCaWd5_7JhbQBe4dknZhsHJg" "WatchMojo.com")
      (mk "UCAKK8dbcSmckr2sWJhv5ezA" "WBNS 10TV")
      (mk "UCry2gCVdntv6r661sKUiKXw" "WCCO - CBS Minnesota")
      (mk "UCVTDqKGUUvbmaVzyFwGqZYg" "WDRB+WAVE")
      (mk "UC659PRLT5K2h7QBLN2Q6Iaw" "WDTNTV")
      (mk "UC1Ahz-Lx2CkejAunMWwCpYQ" "WDTV 5 News")
      (mk "UCf2aLsnOvjzZSXLHB9V1b9Q" "Weekly Of Fun")
      (mk "UCBu0KdNokE4MqdkacvH37_A" "WFAA")
      (mk "UCByGc7P_siORkC1pum8T3_Q" "WFSB 3")
      (mk "UCDrLGkZTcNCshOLiKi5NtEw" "WGN News")
      (mk "UCTvZcgH_rsvaGuZ8mU5jpnA" "WHAS11")
      (mk "UCvG9LbHpMlr5_XCpJRWp9LA" "WILDCAT Reacts")
      (mk "UCk_e9rhSH_Gg4Mp44Ut72ZQ" "WIN Compilation")
      (mk "UC_gUM8rL-Lrg6O3adPW9K1g" "WION")
      (mk "UCnVh7Mb5FdqHUCkYfyPRaqg" "WISDOM")
      (mk "UCFOq-dKCPu3PcmaCMEGDzTA" "WKRG")
      (mk "UCNBmxc6FvKyxtCpUygcdINA" "WKYC Channel 3")
      (mk "UCojNA7ZvnmGuIvYnm44wl3Q" "WLKY News Louisville")
      (mk "UCwuZjWoiT30kDTz0G41Y8gQ" "WMUR-TV")
      (mk "UCM9LVNOFrL5BWmXA3c3Rngg" "World Best Talent")
      (mk "UCGUwSjGn6E3oaT6mJKN4zrQ" "World Crew")
      (mk "UCy0dTlYgFtwyItApHRHPdAw" "Worldwide Music")
      (mk "UCv7BR3sK8XcH3j4WtfXK9OA" "Worst Trends")
      (mk "UCgVZ0mrM3liHNhRYC5Mchgg" "WPLG Local 10")
      (mk "UCnwI-VN5jXWIGQKOI9PMDMw" "WPRI")
      (mk "UCMliswJ7oukCeW35GSayhRA" "WSJ News")
      (mk "UCnquIO-KeazvWWR38jvdu0A" "WSVN-TV")
      (mk "UCSFLs1nwzqSC3Tq6cXhJkLg" "WTHR")
      (mk "UCIFD9TMCLBXvJJMe2OpCtCA" "WTOP News")
      (mk "UCxhC6ALtyS6Xs0gZCPYAZPA" "Wubby Clips")
      (mk "UCcT6w3xUyVshyR2_2vrMp1w" "WUSA9")
      (mk "UC6my_lD3kBECBifeq0n2mdg" "X Factor Global")
      (mk "UCcWkShE9dqAw8uM1RJC99fQ" "Xanderhal")
      (mk "UCGmOuk25_FgwkH2HRAJIfqQ" "xQc Clips")
      (mk "UC5WEyghnbnTTnMtNU4fqYvQ" "xQc Reacts")
      (mk "UC0in9SwaQ9LNxDDFvgOeAwg" "xQcOW Highlights")
      (mk "UCEAZeUIeJs0IjQiqTCdVSIg" "Yahoo Finance")
      (mk "UCKY1msUI1iVtnKHPaLOsiQg" "Yahoo News")
      (mk "UCZhjej7CrosEvVsUetrKbmg" "Yard Best Moments")
      (mk "UCb8mM4kuhD1zf9u7C_IS5mg" "YMS Highlights")
      (mk "UC4-AGCUwX7C-D4BsBook9fQ" "Young America's Foundation")
      (mk "UCQPuCasPh2g7lmsbNQIwa4Q" "YRG HIGHLIGHTS")
      (mk "UCezCkRdT16ao14b0PaDFzaQ" "YRG Stream Highlights")
      (mk "UCHpx-ZlekClc2L-7gRP5GYg" "YTP Room")
      (mk "UCIvaYmXn910QMdemBG3v1pQ" "Zee News")
      (mk "UCxsjWbW_inWEEgfZyJoyS2A" "Zero React")
    ];
  };
}
