{...}: let
  #=====================================================================#
  # FREETUBE BLOCKED CHANNELS
  #=====================================================================#
  # One flat list, deliberately unordered. Matching is by id, so the
  # label is cosmetic - it only shows on the Distraction Free settings
  # page and stops FreeTube re-resolving each entry over the API.
  #
  # The icon is a 1x1 transparent GIF for the same reason; browsing
  # thumbnails come from the API and are unaffected. Grab a new id from a
  # channel page's "externalId" field, not the first "channelId" match.
  blankIcon = "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==";

  mk = id: label: {
    name = id;
    preferredName = label;
    icon = blankIcon;
  };
in {
  programs.freetube.settings = {
    channelsHidden = builtins.toJSON [
      (mk "UChqUTb7kYRX8-EiaN3XFrSQ" "Reuters")
      (mk "UCQVfy3QRi9zM7hp1m6ECKcg" "AlphaExtra")
      (mk "UCGGsXUUTM6h0Dyomfm2p2Lg" "Amethysta Herrick, Ph.D.")
      (mk "UCsgC5cbz3DE2Shh34gNKiog" "92 News HD")
      (mk "UC_62jYuKq0O-K66pjrK5jhQ" "Knox Hill")
      (mk "UC8DA4o0SyaGfyVaBLbF5EXg" "Adam Mockler")
      (mk "UCpQ_q9AwSgzepjnVElVY0ag" "Brian Tyler Cohen News")
      (mk "UC18w0GiCganWW6XeXcw4wgg" "glamspot1")
      (mk "UCn8zNIfYAQNdrFRrr8oibKw" "VICE")
      (mk "UCnwp0iOA4LjPhubDdPXsHWQ" "StreamerTV")
      (mk "UCyNzZ1wgkOWkzYE0zbs7zhA" "Jynxzi Live")
      (mk "UCTvZcgH_rsvaGuZ8mU5jpnA" "WHAS11")
      (mk "UC7LJSq2EkTUhHiNjpXg22mg" "yikes")
      (mk "UC6RJ7-PaXg6TIH2BzZfTV7w" "Times Now")
      (mk "UC63mNFJR8EAb8wAIJwoCmTA" "5-Minute Crafts FAMILY")
      (mk "UCU63EiU7Y-8xcRntPIRVrzA" "Unpacked")
      (mk "UCNvsIonJdJ5E4EXMa65VYpA" "ContraPoints")
      (mk "UCvtq2iUDaijoI4TEtUl_SVw" "𝓡𝓪𝓿𝓮𝓷")
      (mk "UCP6HGa63sBC7-KHtkme-p-g" "USA TODAY")
      (mk "UCm1fqkJ-Tq64bQzM6VRMicQ" "New York Times Opinion")
      (mk "UCRWFSbif-RFENbBrSiez1DA" "ABP NEWS")
      (mk "UCv8klVLFrL_Mf9JZAx5IDzw" "Arash Esfandiari")
      (mk "UCSFy-1JrpZf0tFlRZfo-Rvw" "Sydney Watson")
      (mk "UCYxRlFDqcWM4y7FfpiAN3KQ" "The White House")
      (mk "UCUsm-fannqOY02PNN67C0KA" "NMás")
      (mk "UCByGc7P_siORkC1pum8T3_Q" "WFSB 3")
      (mk "UCEZHP3ngrpdDuO-v1eYfdow" "Botched")
      (mk "UCKpSiUg_W-scoE6ltSp4TnQ" "President Sunday")
      (mk "UClSzp3HiF1N1gz1E2xzxtGg" "Livestreams Memes")
      (mk "UCzI8K9xO_5E-4iCP7Km6cRQ" "Faye D'Souza")
      (mk "UCl9u8dvuTxlikeGSKH8fQ9A" "pxppycorpse")
      (mk "UCWnmTyhtsVRXGdbBOW4Rr1w" "DyQuell Dontae")
      (mk "UC-sHeRGtnOcqt5tXh1nG9OQ" "memes from hole")
      (mk "UCB-MPptlCv5VCdIvAJxNwcA" "Hasanabi Yaps")
      (mk "UCJn6P-l72V2v5wVHtNXS5RQ" "Doll Deranged")
      (mk "UCJZam2u1G0syq3kyqrCXrNw" "PrestonPlayz")
      (mk "UC1PGcfaJ8lFEzgEGn6nm7fw" "Arikido")
      (mk "UCRlCbdMywk2q4Bd-5nyiIOQ" "Cozy Cup Music")
      (mk "UCtDzHr6meh7Y_n6JqSmHazg" "Rayactions")
      (mk "UCn4sPeUomNGIr26bElVdDYg" "NowThis Impact")
      (mk "UCuuBNabOJHBc5rZfX4He9pA" "KreekCraft Hub")
      (mk "UCsIc8Tq-YSFY3BViLJG4d1A" "Stickman Talks")
      (mk "UCbGCHkeXk7hV09XkJL0atbg" "Fear& Clips")
      (mk "UCYUPBf8y9ggcnpBxCKZteHA" "BBC News Gujarati")
      (mk "UCmagDxvmbBpjzKg09LmBSow" "Punchbowl News")
      (mk "UCMKP8n1dUg-b84lfpb0mfdA" "CBS6 Albany")
      (mk "UCgjtvMmHXbutALaw9XzRkAg" "POLITICO")
      (mk "UCTtU4q8rJK0IBWkwli-rCEQ" "Catalyst")
      (mk "UCEAZeUIeJs0IjQiqTCdVSIg" "Yahoo Finance")
      (mk "UCpMTplwUKH5D7jJ_O_YTWyg" "Lord Tmanoz")
      (mk "UCHZA_aJuGa4jEoJs6KW-_pw" "Energi Media")
      (mk "UCSRRURbKlPf1HwPUhjmufTg" "The Free Press")
      (mk "UCvi6hEzLM-Z_unKPSuuzKvg" "ANC 24/7")
      (mk "UCYUbNjkuE4lsr2v1Id2O1oA" "ABC7 News Bay Area")
      (mk "UC6wUQzr_KOZXcNpOTdyYQXA" "DigitalNex")
      (mk "UCWjBqATYrifMWdw-J84k8XA" "Parker Highlights")
      (mk "UCMpW4kMfP8yPzFqHUqX3h2g" "SSSniperWolf Gaming")
      (mk "UCM9LVNOFrL5BWmXA3c3Rngg" "World Best Talent")
      (mk "UCe_Fx4EZAgKjDz0aQ_Y7hSA" "Got Talent Global")
      (mk "UCzWC1TkgyBxxrHkqb6aZf1g" "PLAYGRND SERIES")
      (mk "UCDLeP5A0yBqGUW8FrhWdDTw" "Rich Gang")
      (mk "UC4aqtbSmF7jDxOeiD19eZCA" "Tiny Clipper")
      (mk "UCQyDIp03A6tsck3w29gflfg" "imKaiL00L")
      (mk "UC4OvD2yIbofl9l4dIlqSNMw" "Bill O'Reilly")
      (mk "UCp0Dqeb9JEDJ8aDSWur3ZRQ" "REACTORS GOIN' CRAZY | RGC")
      (mk "UCXNSyuKeoiHOld1OS3kHuVg" "Conservatives")
      (mk "UClGpc-n0Tt44FEkYvs7Tzew" "PoliticusUSA")
      (mk "UCMk9Tdc-d1BIcAFaSppiVkw" "Times Now Navbharat")
      (mk "UCGX7nGXpz-CmO_Arg-cgJ7A" "PBD Podcast")
      (mk "UCmAjdwkUVd5tcSRAhwV5gnQ" "The Chloe Connection")
      (mk "UCpnkp_D4FLPCiXOmDhoAeYA" "UnusualVideos")
      (mk "UCVhSS17jxUOueWmIUYfQcWg" "Celebs AgainstTrump")
      (mk "UC5UyDGFC39h9Mcnem7aNNrg" "Happy Pancake")
      (mk "UC3YUjC9f7GMRWzOKYgibk3A" "All About Fortnite")
      (mk "UCdUD6racxisHiSX9iWFcuug" "The Vaush Pit")
      (mk "UCMiY4t431lhXY4QtPZtzftQ" "KSIClips")
      (mk "UCmA3zSO1wjBGwl61SeM4a3Q" "Democratic Reporter")
      (mk "UCu28JGd1UDoQRlZZtG5Qrcw" "Amir Odom")
      (mk "UCLUZ6ShyBV3vnUAVMlUs4_g" "Absolute Documentaries")
      (mk "UCw8Fc5R0Q5yyS3KrDCPM3xg" "Times Now World")
      (mk "UCtbo6_eDG7zEtaOtcSltJkA" "NewsTamil 24X7")
      (mk "UCQVhgOxzt5W1fZhOd0l2E6g" "The First")
      (mk "UCnQC_G5Xsjhp9fEJKuIcrSw" "Ben Shapiro")
      (mk "UCuFFtHWoLl5fauMMD5Ww2jA" "CBC News")
      (mk "UCuMo0RRtnNDuMB8DV5stEag" "Rebel HQ")
      (mk "UCnTtVY_CHmub27aFurnTanw" "Glimpse Grid")
      (mk "UCqJSzfY0TUADFHkw6tEOoOQ" "politics clips")
      (mk "UCGtLR4lHUM5ovzvFxY4bDOA" "Othniel Eleazar")
      (mk "UC7qZ_e097NBkgOljy1joVRA" "The Daily Beast")
      (mk "UCHaHD477h-FeBbVh9Sh7syA" "BBC Learning English")
      (mk "UC_vt34wimdCzdkrzVejwX9g" "Geo News")
      (mk "UCllmCh9Zat9OaNyc3fRDJag" "Funny Zone")
      (mk "UCte9SD4XLBDFtRZD2dzj_jw" "HasanAbi Reacts")
      (mk "UCnFRJ3mNt6nL9vMHduwCCyg" "Ellii (formerly ESL Library)")
      (mk "UCIYLOcEUX6TbBo7HQVF2PKA" "9 News Australia")
      (mk "UCPWXiRWZ29zrxPFIQT7eHSA" "The Hill")
      (mk "UCwNJt9PYyN1uyw2XhNIQMMA" "TYT Investigates")
      (mk "UCHqC-yWZ1kri4YzwRSt6RGQ" "Right Side Broadcasting Network")
      (mk "UCO9-nEt-Ymh8e-GbfK6HDOg" "Amazing News Today")
      (mk "UCfoxSKJm9pD1Ojb-ZiaOafQ" "Dingo")
      (mk "UC-PYaO3-ikcOLYKmvdN_CwA" "Food Club")
      (mk "UCLldJScHWCtsFlfanYXS8nQ" "Stable Ronaldo Live")
      (mk "UCIQqnNggjzmAM_RHwwH-IaA" "ImStillxQc")
      (mk "UCSWwb_YyNB8vuC1VDcfPPaQ" "Talent Recap")
      (mk "UCVG21WPT3_7rgPskQbmAyfA" "France's Got Talent")
      (mk "UC3wOMk2hNc1f3tWKnPPuUMw" "NIKKI")
      (mk "UCAhtLWZIbOZTl4LIZ9Uby4A" "The Watering Hole")
      (mk "UCTkXRDQl0luXxVQrRQvWS6w" "Dream")
      (mk "UCw6s_N3IQI4sswTSfLoIUrA" "Funny Local News")
      (mk "UCJLiLff4-TOFD-RR4-Ue_dA" "FairyPrincessLucy")
      (mk "UCMmpLL2ucRHAXbNHiCPyIyg" "ARY News")
      (mk "UCRmDJhK_ocN5jXBRIEAyNXg" "Comedy Central Africa")
      (mk "UCPSdTC-PYah-O9B_QwaaYyw" "GlazeDaOne")
      (mk "UCWmMgbc1g6g5O8Tn_-k5qgA" "Democracy Docket")
      (mk "UC_zmPqauxanOAGszXfdipEA" "HeelvsBabyface")
      (mk "UCJHBJ7F-nAIlMGolm0Hu4vg" "Maizen")
      (mk "UC9KblDFy0lrGLvC6w0qH78g" "unknown")
      (mk "UCpB959t8iPrxQWj7G6n0ctQ" "SSSniperWolf")
      (mk "UCg40OxZ1GYh3u3jBntB6DLg" "Forbes Breaking News")
      (mk "UCFZSV_So_OaXgXVzgu58tJQ" "cpac")
      (mk "UCrYrcFGGs_nke1MggS8Jvqg" "Karl")
      (mk "UC2s0uKOc2WgB9eGta7cUUEA" "Washington Week PBS")
      (mk "UCUNtD-UN-fQHHteLHK9HgvQ" "Dr. Fatima")
      (mk "UCesUN0qMfhDMO7Tacx-Py3g" "Fail Impact")
      (mk "UCnxGkOGNMqQEUMvroOWps6Q" "JRE Clips")
      (mk "UCtTLxG2tRLjB0aXMNWCmvhw" "Asia's Got Talent")
      (mk "UCFrmfDhZIom8coan10W819w" "SquidTips")
      (mk "UC7d2WmQqHxc9PTJyj3bVFgw" "Dean Withers")
      (mk "UCTln5ss6h6L_xNfMeujfPbg" "Scripps News")
      (mk "UC2bW_AY9BlbYLGJSXAbjS4Q" "Live Speedy")
      (mk "UChhyfYkhuVrzmvDr-WqpDSw" "Not Even Emily")
      (mk "UCCwUTfKeDj4p9uTNrn9U6Sw" "BBC Archive")
      (mk "UCvBL76p8GgJZExW_0k5BIAw" "unknown")
      (mk "UCH1oRy1dINbMVp3UFWrKP0w" "Good Morning America")
      (mk "UCCsiAKRKcgzA_372WbXNBaw" "Dr. Steve Turley")
      (mk "UCfIjR00qhYUFkbWIugAAbGg" "ABC 7 News - WJLA")
      (mk "UC2kkU18MIJpUaCdokZj3_kQ" "Zeducation")
      (mk "UCnbKOlm6H9njgmN-Yil90Rg" "Heather Cox Richardson")
      (mk "UC-FQUIVQ-bZiefzBiQAa8Fw" "BBC Radio 1")
      (mk "UCPZbwdXrHUXXuaDDdRuZ40A" "Kirk Unpacked")
      (mk "UCzOrrheF99HIxv9Do2K5ghw" "UNIVISION LOS ANGELES")
      (mk "UC-2MJlKSq9_pYk5-bdvMhnw" "Denver7")
      (mk "UCYI_ychRnL7sJrG6PUSBpQA" "CBN News")
      (mk "UCEH_fkvXZCMwPY1pKyEyM3Q" "DailyRapUpCrew")
      (mk "UCmyjVwYZbp5YPYTUyeopO2g" "Pawn Stars")
      (mk "UCj6Ed6HiG3EHJP80EQ1L9bg" "Viral Sap")
      (mk "UCC974Jswc2RGhCmCpxF2boQ" "Lily Simpson")
      (mk "UC3h2dpafuScrNGMYiUDwUiQ" "pierbii")
      (mk "UCStCUMvCw067Nw5uSlbyDsw" "THV11")
      (mk "UCLml2_OPYFkrqs38TVrcU5g" "BlackConservative24")
      (mk "UC1E-JS8L0j1Ei70D9VEFrPQ" "Vaush")
      (mk "UCmk6ZFMy1CT80orXca4tKew" "The Financial Express")
      (mk "UC5DZ4oicRvd_rCK7zxTBXFQ" "Devin Gibson")
      (mk "UC-8_qAhNVG8G1wxONMnYr3Q" "GZERO Media")
      (mk "UCAYgEH1TAiRyd6iyk0JrzvQ" "Mike Plays")
      (mk "UCZ7AeeVbyslLM_8-nVy2B8Q" "Skill Up")
      (mk "UCEW9foRmk4UdbzacT8KCYkA" "News Ganga")
      (mk "UC_976xMxPgzIa290Hqtk-9g" "Walt Disney Animation Studios")
      (mk "UC5bKZHg4PzURMOWcvanl6nA" "FOX 13 Seattle")
      (mk "UCfIXdjDQH9Fau7y99_Orpjw" "Gorillaz")
      (mk "UCt06i6t7Nn8hg2TVcYDsgcA" "LJ")
      (mk "UCRvsrJB_GhMhdLSA4ae5MqQ" "Tom Powell Jr")
      (mk "UC0aSHiQNMy8IMmS7_8WbtdA" "FunkyFrogBait")
      (mk "UC85eXsaeTD6cCCe6N2vB0dQ" "SGA")
      (mk "UCUrfzuazQPsjSTeq4x28QXA" "PoliticsNewsPolitics")
      (mk "UC_bMDjdLd6XPbROr1xcUCHw" "YinkaThatGuy")
      (mk "UC2_X49uo6B7jSVSOwJSjznQ" "YukkoEX")
      (mk "UCAVojJ1k03GZzjSbdXXunkw" "Shane2")
      (mk "UCNjfNLnQYbjBEvnS8KFuyGQ" "FOX 10 Phoenix")
      (mk "UCoA4Xlmkop9PlSGuGdrHm5A" "Infatheline")
      (mk "UCqOPTuLESVvDJtxooEJ9tVw" "StreamOnCNN")
      (mk "UCwWhs_6x42TyRM4Wstoq8HA" "The Daily Show")
      (mk "UCHvGJ-eAV8krPgqofo65WYQ" "Illustrate to Educate")
      (mk "UCG8rbF3g2AMX70yOd8vqIZg" "Logan Paul")
      (mk "UCBO3Gkrej6BAR346oWic-IA" "EVELIN")
      (mk "UCqoZ40XymtdcOp2YOoMw9uw" "OneTopic")
      (mk "UC9k-yiEpRHMNVOnOi_aQK8w" "Inside Edition")
      (mk "UC25GHmlU1I-zbNcZe7a-aiQ" "Jemele Hill")
      (mk "UCLFwj9ugjp26bXAb3vDDPTQ" "Yuzuha!")
      (mk "UCmeOj4wjzP4LT5mEFyIp-LA" "Siffareeno")
      (mk "UCO8WCQsddotuNAH6-Pb_A0Q" "StreetCan")
      (mk "UCoAxJF0J-kTqVS7HP0e7sfw" "HasanDaily")
      (mk "UCE7f7HEPnLRyWxx0f3EpLbA" "Waking Women")
      (mk "UC8Z-VjXBtDJTvq6aqkIskPg" "Polimer News")
      (mk "UCzC-UXOUfSMTA0k6UeQD8dQ" "momem")
      (mk "UCYPvAwZP8pZhSMW8qs7cVCw" "India Today")
      (mk "UC8QNOIOoi63U0arTgU47vEQ" "unknown")
      (mk "UC_wpodAWmXyQanNVof8vyFg" "The Soy Pill")
      (mk "UCTyWEQvhuYNKpzYCtA3AzCg" "unknown")
      (mk "UCvo3jQe4L1ZaSwdQHHQ1Zqw" "Alec Gunter")
      (mk "UC-SJ6nODDmufqBzPBwCvYvQ" "CBS Mornings")
      (mk "UC-_fdI6-TJPwHAeXZcmwnsg" "GreenCat")
      (mk "UCgwv23FVv3lqh567yagXfNg" "DisneyMusicVEVO")
      (mk "UCzjTWXq_oHNst5NkJY113HQ" "Riverboat Jack")
      (mk "UCpXyxLahbn7vZfR5fexenuw" "Flats Two")
      (mk "UCdKj0VzVR0Af0wzd7-68Avw" "Tim Henson")
      (mk "UCi7Zk9baY1tvdlgxIML8MXg" "CTV News")
      (mk "UCynyM7W39qkv19a-0dFtEvA" "Pupzy")
      (mk "UCoRQI9DCEzCpfvI21puHEtA" "Johnnie Guilbert")
      (mk "UCK7IIV6Q2junGSdYK3BmZMg" "TMZ")
      (mk "UC0v-tlzsn0QZwJnkiaUSJVQ" "REACT")
      (mk "UCtu2BCnJoFGRBOuIh570QWw" "Sodapoppin")
      (mk "UCup3etEdjyF1L3sRbU-rKLw" "24 News")
      (mk "UCmuTmpLY35O3csvhyA6vrkg" "TeleSUR English")
      (mk "UCBwSufNse8VMBvQM_rCSvgQ" "Morgz")
      (mk "UCyYhxPxa-bYr-IIAGIV33PQ" "Drama Kween")
      (mk "UCLhoj8ijqBVymbVD48hhQIQ" "Dumbsville")
      (mk "UCJS4UHGP6Q3BI-0ZIGrGXgw" "Junkeyy")
      (mk "UCinjnmQEwCddOudyCC1v7qA" "KTLA 5")
      (mk "UCYHosdETLPp6dpJEsgIUTmw" "Jake Broe")
      (mk "UCr4kgAUTFkGIwlWSodg43QA" "Michael Knowles")
      (mk "UClkO4MArT2WKWj32YDD_-Ew" "The Democrats")
      (mk "UCcukTqc1cJJ4K3c4uzxTzjA" "The China Show")
      (mk "UC531MlZA5LUbeGwEN_zcppw" "News18 Bihar Jharkhand")
      (mk "UC9YcTIQuhwgoOQqYMKYqW9A" "Migos ATL")
      (mk "UCicvc24eAbFp-thRrBnSP2A" "Answers in Genesis")
      (mk "UCELBodZwev0kgJY5Cz61UPQ" "Talia Mar+")
      (mk "UCJwE0uGZCI31R-dlgdlbvtA" "CorinXV")
      (mk "UCWsDFcIhY2DBi3GB5uykGXA" "IShowSpeed")
      (mk "UCkRzm-ELNPhz9l4sGRx3sMQ" "Mike Nellis")
      (mk "UC66VoFZ2upgvnpnQduoHTZA" "decunnew")
      (mk "UCcyqdK1u6GfpBy1LW0bmzrw" "Got Talent South Africa")
      (mk "UCNXD5enYf0UZXccisoxLy0A" "The Biblical Conservative")
      (mk "UCjuN2-heR5gBGIUG_E9Qrxg" "camkablam")
      (mk "UCJSxCOEw2SopkddtjbE4ZaA" "ABC World News Tonight")
      (mk "UCpOKZqwLz8Uk4TMXJF3AnLA" "unknown")
      (mk "UCu-AT1u3_FQdML2l_ODpvCA" "memot")
      (mk "UCW7DEppFdRIbcuYREFiMJAQ" "Rare Memes")
      (mk "UCbq3nNZKry1KjS6n0jw6S_Q" "TikTok CREEPY")
      (mk "UCke6I9N4KfC968-yRcd5YRg" "SSundee")
      (mk "UC1hW1iEFDsW-6V0zC8jqVQA" "Hasan Reactions")
      (mk "UCt38KUTj72UEdWUdmnZHwOw" "ZoeTube")
      (mk "UCqIsmb6AmjzsewSAqsFdSbA" "ellis")
      (mk "UChKQYI9z5rO_sdNjhwyyjSg" "Sideserf Cake Studio")
      (mk "UC9IQhNgS43lmUdU-KdGyb0A" "News18 Urdu")
      (mk "UCXISYK3xagaK5DHnhQ4X0hw" "Diario AS")
      (mk "UCMY4o8_rPjmFoatx7F4TvHQ" "Twinkl Kids TV")
      (mk "UCpLB7kBu9O5dbBKhaIOmqcQ" "DeFranco News Clips")
      (mk "UC3mQV9qPc4pzzYHkhTlRA-A" "Kirk Takes Daily")
      (mk "UCie7RmdcnvXA1FXHRJa7WtA" "KCTV5 News")
      (mk "UCRwA1NUcUnwsly35ikGhp0A" "Noticias Telemundo")
      (mk "UCPgLNge0xqQHWM5B5EFH9Cg" "The Telegraph")
      (mk "UCi13cFku9P5M2ykAWDdIeZg" "Keegan Tatum")
      (mk "UC6KAzM2H6GFxI78kXfopgGg" "DailySpeedClips")
      (mk "UCMA7L1oRCozJaehbDFF6p_Q" "DT is Back")
      (mk "UCoMdktPbSTixAyNGwb-UYkQ" "Sky News")
      (mk "UCO9zJy7HWrIS3ojB4Lr7Yqw" "Lil Wayne")
      (mk "UCqnbDFdCpuN8CMEg0VuEBqA" "The New York Times")
      (mk "UCAql2DyGU2un1Ei2nMYsqOA" "Donald J Trump")
      (mk "UCbgcYEdMsuypG2NJ-znBp3w" "ATN Bangla News")
      (mk "UCyZVCV9xhrCyz4hPehvb4Wg" "Internet Today")
      (mk "UCGie8GMlUo3kBKIopdvumVQ" "Still Watching Netflix")
      (mk "UC4e-87tzDuHYE0RNTjqYOPQ" "Baby News Network")
      (mk "UCC552Sd-3nyi_tk2BudLUzA" "AsapSCIENCE")
      (mk "UCw3fku0sH3qA3c3pZeJwdAw" "Daily Mail World")
      (mk "UCQfwfsi5VrQ8yKZ-UWmAEFg" "FRANCE 24 English")
      (mk "UCYLR1ghzYNyvfjw78raCuxA" "Dr. Phil")
      (mk "UC790WPHI_Sewr5LqiITAz-g" "Canada Today")
      (mk "UCZpjmnFZANDsgzQQkZwMJ7w" "SSSniperWolf Gaming Top Videos")
      (mk "UC3wCAOfSB0W9iuKDDtNJeGw" "Danny Go!")
      (mk "UCagO3YGMBqDjrWBhw7wKuGA" "Keith Edwards")
      (mk "UCAebQubO4U1HQaR-rwsqUhA" "Bowblax")
      (mk "UCqD7wgVS7jjJcJ8u0W9tt-Q" "DimpleVideo")
      (mk "UChirEOpgFCupRAk5etXqPaA" "Bloomberg News")
      (mk "UCMPNAq4xRaz2XMtYSvm8oOA" "Freakin' Famous Auditions")
      (mk "UC2X6M-GBOx8nV1X5RRMVTmw" "Canada Next")
      (mk "UCrPseYLGpNygVi34QpGNqpA" "Ludwig")
      (mk "UCN7jo9su_7oDqwpfin8lgjw" "Hasanabi Clips")
      (mk "UCeH6qE4V7n5tVwP7NkdrtJg" "The View")
      (mk "UC9MpuWZatMPIJVo_b_FCSKA" "MoonlightEdits")
      (mk "UC0L4FNvqduCM49XPjb8dZHQ" "Disney - Topic")
      (mk "UCnGVtqzoexqB5Nb-R_E51XA" "American Secrets")
      (mk "UCt-XpD0mhZVj2zUJb3i0b1Q" "Compilation Beast")
      (mk "UC-EMx2EV7ntOaNytwNiCyeg" "Erica Forever After")
      (mk "UCtFZqbrEByTPN8VwC5dOhqA" "Destiny Highlights")
      (mk "UCtoaZpBnrd0lhycxYJ4MNOQ" "HasanAbi")
      (mk "UCT0YzdGNnZYWm40dDV6DLMQ" "Amirah _mix")
      (mk "UCPkq1dBinCcXQJYv1Skfw4A" "Latest T M")
      (mk "UCw0_9Iih3qM_I_gFLrJeNRg" "Wall Street Journal Opinion")
      (mk "UCd8Aox2OXxfrHloMwjZCBFw" "Mario Adrion")
      (mk "UCrwbBzP11NhxRUCRKx_BgoQ" "Cash Jordan")
      (mk "UCczFNVVax0S1tOIBp-QGw-Q" "AtteDee")
      (mk "UCeY0bbntWzzVIaj2z3QigXg" "NBC News")
      (mk "UCuL3xV8AqD3sekKOhhyZqOA" "Straight Arrow")
      (mk "UC8pOnl4XYXcKfZ_aWBO0o_A" "JiDionPremium")
      (mk "UC0fO_-gbN8r2ImmJ5-qLdeA" "Slop Roach")
      (mk "UCtCZC8TvTGYaeEQBNx648qA" "The USA Stream")
      (mk "UCN7B-QD0Qgn2boVH5Q0pOWg" "BBC News Hindi")
      (mk "UCqlYzSgsh5jdtWYfVIBoTDw" "Fox News Clips")
      (mk "UCBu0KdNokE4MqdkacvH37_A" "WFAA")
      (mk "UC_iUeUzozCHEReJ-shKcCYA" "Internet Anarchist")
      (mk "UCfOkwqj6GoBfbdrBuFo4img" "The Thief One")
      (mk "UCmyKnNRH0wH-r8I-ceP-dsg" "PuthiyathalaimuraiTV")
      (mk "UCQeRaTukNYft1_6AZPACnog" "Asmongold TV")
      (mk "UCl_vAxZpvbO-PFXdDu7EdHw" "Ujjwal")
      (mk "UCLXo7UDZvByw2ixzpQCufnA" "Vox")
      (mk "UCJ5v_MCY6GNUBTO8-D3XoAg" "WWE")
      (mk "UC9r9HYFxEQOBXSopFS61ZWg" "MeidasTouch")
      (mk "UCQztlwsK5pV45U8vMtfbWjg" "Dr. Jordan B Cooper")
      (mk "UCQc3Rhsw8dl-vl13UUWYRQQ" "London Storm")
      (mk "UCN14VoNSni7WqcGeuWn2OLg" "OrionGplays")
      (mk "UCZjR0cPlO91NNQ-6fgvtuhA" "Dexta Daps")
      (mk "UCL_KcyTqjIT5uHi19qZ8zIw" "unknown")
      (mk "UCD4UWbxOOrFsxkMMfjYQ0VA" "Foltyn Reacts")
      (mk "UCzuqE7-t13O4NIDYJfakrhw" "Democracy Now!")
      (mk "UCKbj5d8f70i0AYLyiJ3YMXg" "KMPH FOX26 NEWS")
      (mk "UC8p1vwvWtl6T73JiExfWs1g" "CBS News")
      (mk "UCLe_q9axMaeTbjN0hy1Z9xA" "Caleb Hammer")
      (mk "UCKti4xis1ZJ2FQFAuDQ1kpg" "Dr. Ben")
      (mk "UCztGY3Qsxxk7JDSY3Q_iXsw" "Best HipHop Music")
      (mk "UChVO_r6gSLH_usmjUfiXU3Q" "Know way no how")
      (mk "UC3780MVtSV3Huj4si_CQvlQ" "BBC News සිංහල")
      (mk "UCsT0YIqwnpJCM-mx7-gSA4Q" "TEDx Talks")
      (mk "UC6my_lD3kBECBifeq0n2mdg" "X Factor Global")
      (mk "UCiiiNujtnT1ULcEXCWIFjQw" "Houston Public Media")
      (mk "UCyI4gi0BtlKiUl6KgtuVIUw" "CTV Your Morning")
      (mk "UCyri-PL3l4Dn9IooWXQAqfA" "Hook Global")
      (mk "UCP45EebTGl1ISj2DX33A2Rg" "Fanum Live")
      (mk "UCpgILFSGxY-9mQR79fLSt2A" "Senate Democrats")
      (mk "UCoWTV6unC8rbshn7-0BF8vw" "JoJo Siwa")
      (mk "UCXxyynFIIszB0pSQfbAOkmA" "Life, take two!")
      (mk "UCjRXO-HSl5XpuF-cWvtMV_g" "Tim Black TV")
      (mk "UCkBrtQrHN6Lc3vJUzXT0m6A" "Lincoln Square")
      (mk "UCnJo_lQSjVHCwUzUtVqde4Q" "Vaushite")
      (mk "UCknLrEdhRCp1aegoMqRaCZg" "DW News")
      (mk "UCaxOQZrF5llUMp-JjesUz1A" "Lil Durk")
      (mk "UCnmtYnwv3h-yxgVhMUeZJ8Q" "boody")
      (mk "UCGUJ_4gaYiwyndRzTsedMzA" "USA BS Network")
      (mk "UCOS9H38LKF5Yrp3BFLQ7MNw" "Kluster")
      (mk "UC4AScNTPAuPW0JtHtbfPwxQ" "HasMEMES")
      (mk "UC4-79UOlP48-QNGgCko5p2g" "MrBeast 2")
      (mk "UCqREBYw4H7SZyCXiUJXifVA" "Daniela Avanzini")
      (mk "UCsooa4yRKGN_zEE8iknghZA" "TED-Ed")
      (mk "UCG1CoynVOh5uj12qpDLQ7fQ" "Fox Nation")
      (mk "UCTjDhFuGXlhx9Us0gq0VK2w" "The Trump Report")
      (mk "UCrhRdj-SbmakNH7Zmyg2mUw" "Anomaly Report")
      (mk "UCa6vGFO9ty8v5KZJXQxdhaw" "Jimmy Kimmel Live")
      (mk "UCMtFAi84ehTSYSE9XoHefig" "The Late Show with Stephen Colbert")
      (mk "UC7wV9BwhmNksC2VxZbOqiZA" "Nogla & Terroriser React")
      (mk "UCx8Z14PpntdaxCt2hakbQLQ" "The Lallantop")
      (mk "UCQtEIMnABKkglAlrASZ4p9w" "Leaflit & Asari")
      (mk "UCiWLfSweyRNmLpgEHekhoAg" "ESPN")
      (mk "UClqifC6Nd7v-IfTqce4k62A" "Carry Depie")
      (mk "UCizqDT7CpXE3e4aBlx1fiEw" "unknown")
      (mk "UCWvF8GrHIQLRqgVpKAscbeQ" "unknown")
      (mk "UCfO3B57E6NpIn-KsVjvmLLw" "unknown")
      (mk "UCD1Em4q90ZUK2R5HKesszJg" "Clash of Clans")
      (mk "UCfnpUsAB6Qb-HpEiCy3ZPiA" "Mo Funny")
      (mk "UCXzC3VMKJUK-jTMtUaZz-uA" "Bills News Consolidated")
      (mk "UCct1pE5fNVUdIR1aw3wxPew" "notdefining")
      (mk "UCMliswJ7oukCeW35GSayhRA" "WSJ News")
      (mk "UCqdOvfSmM2NKRNE0FSbATuw" "FOX 29 Philadelphia")
      (mk "UCzJXNzqz6VMHSNInQt_7q6w" "Megyn Kelly")
      (mk "UC-8t7yvYJaBy2QJ0O_Xllsw" "DUSK Reacts")
      (mk "UChFnGuCZ_Fb4DhbxRm9N9UQ" "Oprah")
      (mk "UC5T7D-Dh1eDGtsAFCuwv_Sw" "7NEWS Australia")
      (mk "UCuzS3rPQAYqHcLWqOFuY0pw" "News 24")
      (mk "UC3EmxrWVl7K8xBH_UVIWY4Q" "The Mirror")
      (mk "UClkXLaqttTs8YJHyuZ_wVKA" "Viral Memes")
      (mk "UCbmoYCccdSpnWdmWW4b7BlA" "Politics Exchange")
      (mk "UCmbm72l60p3OH4aL4o7BFeA" "Turning Point UK")
      (mk "UCnMp_7DVSGuzNfTpNKWVldw" "TommyKayVODs")
      (mk "UCJquYOG5EL82sKTfH9aMA9Q" "Rick Beato")
      (mk "UC_m3q4psNrO7XoZohSiBA8g" "unknown")
      (mk "UC06DvgSsBrL24RNd_MXqNIg" "NumberONE")
      (mk "UCSD4jzd-0jOsZ9KAe9rxmPQ" "Ashley Gavin")
      (mk "UC-_mPIOcPS5EiR0gWG9go1g" "FailSide Moment")
      (mk "UCDrLGkZTcNCshOLiKi5NtEw" "WGN News")
      (mk "UCCj956IF62FbT7Gouszaj9w" "BBC")
      (mk "UC_gUM8rL-Lrg6O3adPW9K1g" "WION")
      (mk "UCURGLompzAFIuf8pTqnRQug" "TNT GRAFFITI")
      (mk "UCi4fcBVyo4CAnmdgXeO-NvA" "CBS Boston")
      (mk "UCYELGPo--bqZX_XcnJvdIJA" "Casey Blake")
      (mk "UCZHRPkcryTnlZFc-Ss5TiVw" "Phoenix Animations")
      (mk "UCKY1msUI1iVtnKHPaLOsiQg" "Yahoo News")
      (mk "UCekbhIcWL_x4bYVZPZZi0iw" "Asianet News English")
      (mk "UC0eLBYhxW9HC0P9PXQ73mpQ" "Cash")
      (mk "UCDT1meaKQ_D1HjhTGULNbew" "Streamers Reloaded")
      (mk "UCCuJoMu1y_o9pczBxshPmqw" "Got Talent Shorts")
      (mk "UCV98lDQ42J3PDjNQIpdoYmg" "JKW Compilations")
      (mk "UC4Ec_7qJhQlYjVWn0ZhMrSg" "K9 Multimedia")
      (mk "UCSHZKyawb77ixDdsGog4iWA" "Lex Fridman")
      (mk "UCxi4yNzqJhjs4u6fLRonU1A" "BBC Playback")
      (mk "UCVTyTA7-g9nopHeHbeuvpRA" "Late Night with Seth Meyers")
      (mk "UCACRim7l0tmc5lhNnDQyUvQ" "The Dallas Morning News")
      (mk "UCmGSJVG3mCRXVOP4yZrU1Dw" "Johnny Harris")
      (mk "UCT2X19JJaJGUN7mrYuImANQ" "America's Got Talent")
      (mk "UCWA4LJu3-gZfvvt6DN8-VFQ" "MoreAliA Top Videos")
      (mk "UCGLA2qQ_N_83Spcjz51d8HA" "MAGNO NEWS")
      (mk "UCVxZlxikHMY8LzspzinH1ww" "Us Weekly")
      (mk "UCCvfdExsmntZlxlDUsNMJfg" "America Only")
      (mk "UCIBHwinVPgVmIRiFJdX40fA" "Ireland's Got Talent")
      (mk "UCXIJgqnII2ZOINSWNOGFThA" "Fox News")
      (mk "UCGq-a57w-aPwyi3pW7XLiHw" "The Diary Of A CEO")
      (mk "UCfiWa7d6um8dAb9hSz2UD-w" "Bryton Myler")
      (mk "UCNBmxc6FvKyxtCpUygcdINA" "WKYC Channel 3")
      (mk "UCyF5AQlKSAm1OP-nX3lBrDg" "Rizky Aulia")
      (mk "UCALsgRqlpl867WCkckre1Sg" "DestinyBites")
      (mk "UC0IWRLai-BAwci_e9MylNGw" "CarryisLive")
      (mk "UCDmCBKaKOtOrEqgsL4-3C8Q" "Blaire White")
      (mk "UCHbZa_koHjqy_H5Wz3AGjjg" "Streamer Highlights")
      (mk "UCBTE3ebHLYZAHRBQqaAUYhg" "Vexbakes")
      (mk "UC4-AGCUwX7C-D4BsBook9fQ" "Young America's Foundation")
      (mk "UCETZ7OiW7-wqwb-6hsz3C4w" "Bionic")
      (mk "UCVvQREV_htIcqsb79TbmMsw" "One Challenge")
      (mk "UC77tObmZQampes4mWZmAjZw" "unknown")
      (mk "UCkS_HP3m9NXOgswVAKbMeJQ" "Then & Now")
      (mk "UC16niRr50-MSBwiO3YDb3RA" "BBC News")
      (mk "UCxsjWbW_inWEEgfZyJoyS2A" "Zero React")
      (mk "UCpwYqKXDVQYtuib-zCoftbg" "Amanda's Mild Takes")
      (mk "UCYOeaN9YfmXV1oJfiDcPaug" "Whop Originals")
      (mk "UCRXnOs1rjfLMYrtZ-0n29NA" "FreedomToons")
      (mk "UCOHHd4AVAgOUsGfgaXAMJdw" "KidBehindACamera")
      (mk "UCOGa-48fFt4cW0UnW5WSdRg" "FOX 2 Detroit")
      (mk "UCfio-qUSwEkYnEW4aVejO-Q" "The Enemies Project")
      (mk "UCN5tcDI7z6vN9s3p3n_JtoQ" "Jorge Ramos")
      (mk "UCaON315MhreLMfHRchLnKlg" "Twitch Scrubing")
      (mk "UCd9fzbANRDUO8UlSb0fg34w" "Jotaerre")
      (mk "UCV3Nm3T-XAgVhKH9jT0ViRg" "AJ+")
      (mk "UC-3jIAlnQmbbVMV6gR7K8aQ" "The Majority Report w/ Sam Seder")
      (mk "UCWXPkK02j6MHW-4xCJzgMuw" "Golden State Times")
      (mk "UCjHWv2DU5-HLpogAAr386DQ" "FOX 5 Atlanta")
      (mk "UCsJKFktV0oUOB6reMpg_0pQ" "Free Roaming Photography")
      (mk "UCvgfXK4nTYKudb0rFR6noLA" "UFC")
      (mk "UC3055Mg81-5X5l9t_DFAAxQ" "Urban Legends")
      (mk "UCOmjR-JVOshlZbUoQYOCxWg" "Dr. G Explains")
      (mk "UCr3cBLTYmIK9kY0F_OdFWFQ" "Casually Explained")
      (mk "UC98saSu1w3i9w-PG8Tsfi3Q" "JoJo")
      (mk "UCG5Kp09WJc3rJ5QjUY_AEug" "Justin Trouble")
      (mk "UClHVl2N3jPEbkNJVx-ItQIQ" "HealthyGamerGG")
      (mk "UCV4MuJHfEXNMjrjwcd4tHEA" "Slow News Day")
      (mk "UC0VvxW6DEAVxIEfWgBnuaMQ" "ShareAmerica")
      (mk "UC5bEfSFTYQVfLCwkhBt8NtQ" "The Heritage Foundation")
      (mk "UCqYw-CTd1dU2yGI71sEyqNw" "GMA News")
      (mk "UCja8sZ2T4ylIqjggA1Zuukg" "CBS Sports")
      (mk "UC5maSolHQX9er0BOxrzjMwA" "FOX 7 Austin")
      (mk "UC295-Dw_tDNtZXFeAPAW6Aw" "5-Minute Crafts")
      (mk "UC30nbd6-eUIvRi5zMCTRI1Q" "Maceツ")
      (mk "UCbpqhOEGlI-1lS4GfAeV2vA" "Soulja Boy")
      (mk "UC6O5FQjHayliiojkA7PaHTA" "TLS - Idiots At Work")
      (mk "UCYCFeGE0Y8QlWJsho8-r1_w" "ViralVideoLab")
      (mk "UC2jwKIODVzbfQo1Doml-RWQ" "Shyaren")
      (mk "UCfIOSIFur-qFToVKahB0A6w" "L3WG Reacts")
      (mk "UCtRTXkq7LrqwPdfaeGW8Axw" "Eden is Online")
      (mk "UCloH7JPn0CtzIJnThe125_g" "MB14")
      (mk "UCQSg8ZOrr1tH9mrmMYilfjw" "Celebrity Substitute")
      (mk "UCPpN3Hbkc9Ck3-H22WaT3SA" "xqcttvjuice")
      (mk "UCUsN5ZwHx2kILm84-jPDeXw" "Comedy Central")
      (mk "UC2V1ul4ul85kac0Y81wXTqQ" "Kwite")
      (mk "UCkPeaJ9dwHTvq6OYrsSGz7Q" "Robert Davis")
      (mk "UCvAnclelY8eSq8GyPE19KTw" "The National Desk")
      (mk "UCsJF0oPEzEQ_cN-nNMlK3wg" "nyaraVT")
      (mk "UCkBS_xU1WQ7FVsDoQ_OPeDg" "CBS Chicago")
      (mk "UC_2irx_BQR7RsBKmUV9fePQ" "ABN Telugu")
      (mk "UCGmnsW623G1r-Chmo5RB4Yw" "KSI")
      (mk "UCjq9ElqnV7Df6NLb4oDHKqQ" "KCENNews")
      (mk "UC52X5wxOL_s5yw0dQk7NtgA" "Associated Press")
      (mk "UC0Kgvj5t_c9EMWpEDWJuR1Q" "DJ Khaled")
      (mk "UCWHbFbZkrCwNxHUVlPQGLXg" "destinyhqclips")
      (mk "UC6Hyj5sVbiYhpc_FA14nziw" "Mikhaila Peterson")
      (mk "UCmSPDMxfLphFJlZirsHbP0A" "Viral Feed")
      (mk "UC6EmR959HIts4gzdt80t3Xg" "Mega YTP")
      (mk "UC4OqEJz6oABzz_7nu29zF3A" "FOX 26 Houston")
      (mk "UCHOtZ0eGmaYibbHfzwdST1Q" "Friends From Work")
      (mk "UCq5guwoq4CLsNOU-Zkp4waA" "Discovering Fiona")
      (mk "UCoo9priHndMj6q9tpGtZrMg" "Deprivation Slept")
      (mk "UCnkvVqNcHpAs5JNJW7-9Syw" "Big Tymers")
      (mk "UCIzXayRP7-P0ANpq-nD-h5g" "The Sun")
      (mk "UCjiXtODGCCulmhwypZAWSag" "Jynxzi")
      (mk "UCmRbHAgG2k2vDUvb3xsEunQ" "CNBC-TV18")
      (mk "UCcWkShE9dqAw8uM1RJC99fQ" "Xanderhal")
      (mk "UCk_e9rhSH_Gg4Mp44Ut72ZQ" "WIN Compilation")
      (mk "UCl_LO48OHG9K8A3Js8Hj40g" "Viral Voices")
      (mk "UCUtZaxDF3hD5VK4xRYFBePQ" "Britain's Got Talent")
      (mk "UC2x_qNZXKDxNP1j4jvHATRQ" "Face the Nation")
      (mk "UCKETYkwpPAQ09rd47iLoIsQ" "brookesharks")
      (mk "UCA6oXQTT_mtCj32dZDdoL6w" "Basic Logic")
      (mk "UC0JJtK3m8pwy6rVgnBz47Rw" "Rotten Mango")
      (mk "UC9s1PI-BH7qOdmZKXbBDNxg" "Epic Rap Battle Parodies")
      (mk "UCdIE3qqvO6hybTXtG0gux2w" "MedaBuzz")
      (mk "UC56RKHnIutm-L99-fhxulDA" "Tik Tok Now")
      (mk "UCa-x5T8TD99WYST764WhsEA" "KEZI 9")
      (mk "UCoGav6jgImtvjpogwhRr7Wg" "Chicago_News")
      (mk "UCqTa3sNT6SfiQ2DQK_kuWlA" "Oneindia News")
      (mk "UCvpfautZTTR1opQB04T2fTA" "Conservative Vibes")
      (mk "UC9HQXWbt14wTdr_Tzc8ZE0A" "Doctor Youn")
      (mk "UCyOMUZ7f2DJDCeTRAYuwudQ" "Make That Change")
      (mk "UCY9eEaH19ulZmdusctU1ejA" "Glamour")
      (mk "UCO01ytfzgXYy4glnPJm4PPQ" "Matt Walsh")
      (mk "UCBi2mrWuNuyYy4gbM6fU18Q" "ABC News")
      (mk "UC3M7l8ved_rYQ45AVzS0RGA" "The Jimmy Dore Show")
      (mk "UC7Gf2tZ8coTX2ckTPgn62iQ" "Disney Kids")
      (mk "UCSP_VKyy6EKtloF625wut5Q" "BruhMan")
      (mk "UC1SaV8cJ5u5U9iEZS6QRbpg" "5-Minute Crafts TEENS")
      (mk "UCzdOLUx-iUO7wfWLpYLGxUQ" "TruthHurts_2026")
      (mk "UCABZ7Z6SBTp4IsARDceOq7w" "HYPE+")
      (mk "UCV9_KinVpV-snHe3C3n1hvA" "shane")
      (mk "UClFSU9_bUb4Rc6OYfTt5SPw" "Philip DeFranco")
      (mk "UCaJsUfWlqkiDxnoWrTK2iyg" "Politics & Paper")
      (mk "UClSTuQObWlw56blWZiW-wcw" "Bobby Shmurda")
      (mk "UCPJHQ5_DLtxZ1gzBvZE99_g" "Smosh Alike")
      (mk "UCNcdbMyA59zE-Vk668bKWOg" "Disney Jr.")
      (mk "UCQlJ7XpBtiMLKNSd4RAJmRQ" "The Weekly Show with Jon Stewart")
      (mk "UCHSIA2JRC5PWvUX4Sl8OrcA" "Jammidodger")
      (mk "UCgSO-swInyhWSUpgKIDrnjQ" "NOAHFINNCE")
      (mk "UCTOoRgpHTjAQPk6Ak70u-pA" "CNN 10")
      (mk "UCrSVc3he0AQD_CEqOIVdvyg" "unknown")
      (mk "UC3XTzVzaHQEd30rQbuvCtTQ" "LastWeekTonight")
      (mk "UCaWd5_7JhbQBe4dknZhsHJg" "WatchMojo.com")
      (mk "UCUaT_39o1x6qWjz7K2pWcgw" "Beast Reacts")
      (mk "UCwPzlQU2MqEQJWgqM_0VFKQ" "KSBW Action News 8")
      (mk "UCVjh0oZ3Ug5-s3WX1awxblQ" "Popcorn")
      (mk "UCjuKQCmKlCtrPL2wl1uIphQ" "MorePegasus")
      (mk "UCb0tMboxhHE8Jx6-nhJmRPw" "Allure")
      (mk "UCAeWdyKJXGWmVAXFpgLNNTg" "CBS Evening News")
      (mk "UCmgvP1a5H32FE_yCyYGedEg" "thermia")
      (mk "UCpa-Zb0ZcQjTCPP1Dx_1M8Q" "LegalEagle")
      (mk "UCZWlSUNDvCCS1hBiXV0zKcA" "PragerU")
      (mk "UC5dUUCs748wCYQl682LX6bg" "Farron Balanced")
      (mk "UCpHHJHwi5kwPNBC7qNz_pUg" "Dave Neal")
      (mk "UCWyDCS2xtZgab_MUlhmpQZA" "YourRAGE")
      (mk "UCcgVECVN4OKV6DH1jLkqmcA" "Jake Paul")
      (mk "UCjqyxpqA_88GWbZVB2E-Z_A" "Demurly Media")
      (mk "UCHmb7OFncrZ7BRpMxTzsP4g" "The US Sun")
      (mk "UCyxcZgX1wNU-nk1yB9CvzSw" "Aaron Parnas")
      (mk "UCQfrWrZ6-XHGO0wgoODqXww" "KingofClipz")
      (mk "UCeV2O_6QmFaaKBZHY3bJgsA" "JoJo Siwa")
      (mk "UCJVBaQLwyTfxbvoP5A9G6rA" "Gama")
      (mk "UClt01z1wHHT7c5lKcU8pxRQ" "hbomberguy")
      (mk "UCT6iAerLNE-0J1S_E97UAuQ" "YongYea")
      (mk "UCKRoXz3hHAu2XL_k3Ef4vJQ" "Pod Save America")
      (mk "UCJgZJZZbnLFPr5GJdCuIwpA" "Legal AF")
      (mk "UCVuFPbAjTi3mqpH-0veJRWg" "CBS Philadelphia")
      (mk "UCEXjRWyIHGDARGKJXQTi_yQ" "RockyDank")
      (mk "UCuMoaBp0ozi9c-67AFWtg-Q" "Samantha Lux")
      (mk "UCSi7XpA8swk2rJww6HEHA7g" "HasanAbi Rewind")
      (mk "UCDYT9mM3L_ByrPYMyl0MGGg" "BBC Ideas")
      (mk "UC8fsoduB61Ept6T84mRxFog" "The Moment")
      (mk "UCNJTWkcUJoMBamCr1IW097w" "Jolah Politics")
      (mk "UCi70qFIwSUyMgxT5ZjR2zQg" "TALENTKINGHD")
      (mk "UCsuqAjJtlUP1XxnXeXjSpxg" "Critikal Chronicles")
      (mk "UCF5fVevjGC4eUg213wiZR5A" "Thug Theory")
      (mk "UCoFITRWg-ut6p78rnnBi52A" "BubblePinkElle")
      (mk "UCzgxx_DM2Dcb9Y1spb9mUJA" "TWICE")
      (mk "UCuZBxbwknYtE30Qdh0dQ1Tg" "Jacksinfo")
      (mk "UCy0dTlYgFtwyItApHRHPdAw" "Worldwide Music")
      (mk "UCdrBnBNLsN4_cH32HWbr9qg" "GH'S")
      (mk "UCZFMm1mMw0F81Z37aaEzTUA" "NDTV")
      (mk "UCxCfoSInadl-4i3F70zDt1A" "NBC New York")
      (mk "UCHpw8xwDNhU9gdohEcJu4aA" "The Guardian")
      (mk "UC_lEiu6917IJz03TnntWUaQ" "CNN en Español")
      (mk "UCxAGqUo8Qm5jyFyxjs78B0w" "Hellion.Vision")
      (mk "UCvixJtaXuNdMPUGdOPcY8Ag" "David Pakman Show")
      (mk "UCUC1Y65XvU2n9lb6GvfAQ5g" "Destiny DGG Clips")
      (mk "UCJ6o36XL0CpYb6U5dNBiXHQ" "Shaun")
      (mk "UCYLS9TSah19IsB8yyUpiDzg" "Jordindian")
      (mk "UCxFWzKZa74SyAqpJyVlG5Ew" "Kat Blaque")
      (mk "UCYiYFWmU1ozUD8mTQUDmFHw" "Conservative Ladies")
      (mk "UCAea1C_i5EL0Bu48FM-N6Qw" "Ali-A²")
      (mk "UCKy1dAqELo0zrOtPkf0eTMw" "IGN")
      (mk "UCW2QOSa8rtTRreEqqkYcmmg" "Jovan Bradley")
      (mk "UCXrwgY7yxq3UMMSLUJfSn2A" "TrueBlue")
      (mk "UCL0u5uz7KZ9q-pe-VC8TY-w" "Candace Owens")
      (mk "UCe02lGcO-ahAURWuxAJnjdA" "Timcast")
      (mk "UCn_uMY15GlwaPpx80-WjR6g" "Occupy Democrats")
      (mk "UCFmofUYwZd1Ibf_O3PF71jg" "FOX 32 Chicago")
      (mk "UCQXHTFnQYFTqN0MqmNh9EIA" "BBC World Service")
      (mk "UCdLE2uABtZjc9aLDFl5_BPQ" "EarthMan")
      (mk "UCnFmWQbVW_YbqPQZGNuq8sA" "Andrew Dotson")
      (mk "UCdZmX-f3TDaRhnhM4KLM4SQ" "Doctor ER")
      (mk "UC9N7wBTsK93KJFHwAMslbVg" "HalForNY")
      (mk "UCx6h-dWzJ5NpAlja1YsApdg" "Newsmax")
      (mk "UCS1j8LH6zQ1xqmm06B8EOnQ" "Shark Tooth 🌀")
      (mk "UC3v3VpUyf34SLfN1IyUlMeA" "inside nepal news")
      (mk "UCAUO8EhsSTz02stvKDupChQ" "MTV News")
      (mk "UCoJhK5kMc4LjBKdiYrDtzlA" "Redacted")
      (mk "UC8op54WYWHOloW620_r6S1A" "Jason Rosenbaum")
      (mk "UCzn4ij1jh39Zpj0N8vHiVqA" "Sundae Conversation")
      (mk "UCaeO5vkdj5xOQHp4UmIN6dw" "The Daily Wire")
      (mk "UC2etEuPIfohP4P53wM0KImA" "5-Minute Crafts DIY")
      (mk "UClstjKOVQ1V-BhFP8arH2XQ" "Leana Deeb")
      (mk "UC-eeR93Xb31Fk397K05vW_g" "Quintheo")
      (mk "UCEfe80CP2cs1eLRNQazffZw" "Dave Smith")
      (mk "UCumtYpCY26F6Jr3satUgMvA" "NTV Telugu")
      (mk "UCtuwNYL0ulHE6rRXivZvUXg" "WonderAuria")
      (mk "UCBc13XYipnBIBE3Ff8QaaGg" "IBC24")
      (mk "UC9CSR-6NKXXCLq1igyW70mg" "doggity")
      (mk "UCBwejc-awS-mANgrkHQ5-6A" "BBC London")
      (mk "UCOlq7FRJdf0QtfsPtwZ64Cg" "Golden Voices")
      (mk "UCg24p0qlHK6TL3DCAiecppQ" "unknown")
      (mk "UCZW7uA8PwgRhoS44Aurwp-g" "Conduit")
      (mk "UCb5RPUFX8Cr4ye-mukGYgtw" "Clash of Time")
      (mk "UCR4z8ccOWNoUThB4VAMNBTg" "OUR STUPID REACTIONS")
      (mk "UC0Ra4Wt7u860wRJRyoRdhpg" "Capitol Central")
      (mk "UCySTKqYThqBbKdEtzOjFhgg" "Sam Collins")
      (mk "UCXg2L_c6fFI-hH3lzsGOQkg" "Ryan Pictures")
      (mk "UCdSS1S6jnCAqNz0ttO6boOw" "ClipNeverStop")
      (mk "UCgEvEKgmQ-CHPIeOSaGCffw" "Amala Ekpunobi")
      (mk "UCErKUCncCyBgEdxWAtrj5hg" "Hip Hughes (HipHughes)")
      (mk "UCrvhNP_lWuPIP6QZzJmM-bw" "New York Post")
      (mk "UCVnBaemGSz05OUyKmQjIJSA" "Warren Smith - Secret Scholar Society")
      (mk "UCOEvClYLRZcT5bNCCI5eMKg" "CBS Pittsburgh")
      (mk "UCDnEa2HC2eeT-cN3pAKnNTw" "Top Viral Talent")
      (mk "UCKgJEs_v0JB-6jWb8lIy9Xw" "BlazeTV")
      (mk "UCLOPC6bOBuiSBAJ16JXLAHg" "Last Night On Destiny")
      (mk "UCoh6A539KgTaqXenKj4hgWg" "Dima The Show")
      (mk "UC8Su5vZCXWRag13H53zWVwA" "TIME")
      (mk "UCj6EKBe990fanr4MSh45Alw" "The Canadian Press")
      (mk "UCpWSYhAy698xPkfDXd87GwA" "FlawlessKevin")
      (mk "UCWCEYVwSqr7Epo6sSCfUgiw" "MIRROR NOW")
      (mk "UCVFm-5smU7mNREPXtT78Jvw" "unknown")
      (mk "UCEs5MQjXJq27-X2vgdwtYDw" "Dagar")
      (mk "UCwd8Byi93KbnsYmCcKLExvQ" "Negocios TV")
      (mk "UCVBD2a1uUkhX18B1WVcddzQ" "The Planet D")
      (mk "UCxMXl9L79X1Mq_4iwCOyPFg" "CBS TEXAS")
      (mk "UC37PFGlxWgx4tU6SlhPCdCw" "whatever")
      (mk "UCVvdPoakKrgavRTdFxRvC1w" "The Vocalyst")
      (mk "UCOtR7QEHj32VrfbvhKr9FlA" "Canada's Got Talent")
      (mk "UCL2JgVl_8ExIo6Xxu0ArHug" "Toddally")
      (mk "UCVv0saCKl3TIt-0ZaE85ftA" "theneedtoknow")
      (mk "UC4EQHfzIbkL_Skit_iKt1aA" "Moist Charlie Clips")
      (mk "UCyzkxMLeZDcd_Qhzh6uMgbg" "PoliticsJOE")
      (mk "UCR9120YBAqMfntqgRTKmkjQ" "A24com")
      (mk "UC8mnXeOlR9hC2w8aYqY9WNQ" "Loudwire")
      (mk "UCc30Q1bAxLtfzeS_jh7J5wQ" "HasanAbi Archive")
      (mk "UC7z-QspogmmNjYGPAcypJpw" "nopejustnick")
      (mk "UCeBWh-0p7vgBeD6HOHBpfwQ" "Top 10 Talent")
      (mk "UC9KUAdPr9Rb8MEyuvL59J4A" "Neilla Uwase")
      (mk "UCbDSo4C1f1SnKsAzHOpTdUA" "Talent Rewind")
      (mk "UC4CtHwx1jBdPlYCFX-UjPAw" "James's Army")
      (mk "UCII84rxnNkEjtk1zC3qTtbg" "The Rest Is Politics US")
      (mk "UCNXjJ4Igw2Ir8774eBNb4yA" "KRCG 13")
      (mk "UCeny7bIu5FsrZ8C55dSmWSw" "The Necessary Conversation")
      (mk "UC2vlpX8sNDBmPcY_1_QSGJg" "tlc uk")
      (mk "UC4iraTePkGIYUGDsOl85BCw" "PF Jung")
      (mk "UCf1mRk7vSkC-89IHf0PL97g" "HaveYouBeenOutside")
      (mk "UCgAPgHNmQSG_ySHRiOVeF4Q" "FOCUS online")
      (mk "UC8-Th83bH_thdKZDJCrn88g" "The Tonight Show Starring Jimmy Fallon")
      (mk "UCjElJyiXmQXnWmceQ1JyKrA" "Asianet Suvarna News")
      (mk "UCCizpvXws0bY_VAf7DYRV5g" "HasanAbi Direct")
      (mk "UC-NPQYmHM9AagZg2GfaiiBw" "Viral Now")
      (mk "UCVrK_pMRp_q8IelpfUCTGLQ" "Turning Point USA")
      (mk "UCEk4EFSCvSPtZDTck_RLsOQ" "Jamesito")
      (mk "UCacgRtCiBjKeVnnPMU44ung" "Daily Denims")
      (mk "UCYj0JoiJtU-nJtvaHHYozZw" "Jeff Square")
      (mk "UCmdR4DlZgP4rEslW12Dv_kg" "Dangerously Informed with Evie")
      (mk "UCcT6w3xUyVshyR2_2vrMp1w" "WUSA9")
      (mk "UCbuTTnEzYIACGCZUegN0fKg" "Capital Insight")
      (mk "UCccLJcTFQAVcFGOWcF1DTtw" "V U Meme")
      (mk "UC_8TgFRkbkthGkiNoF9j1OA" "The Sesh")
      (mk "UCunkVlKjHWCJ6OKfffus19Q" "ABC News 4")
      (mk "UCry2gCVdntv6r661sKUiKXw" "WCCO - CBS Minnesota")
      (mk "UCyy1V55KUxnlaj8QQ6M6nhw" "darkishalfcrazy")
      (mk "UCRRsHRG0qzS42KAK1YsEr-g" "One TikTok Mashup")
      (mk "UCYOaYgTPCwEN9AvDjZ78HMA" "Kawaii Reaction")
      (mk "UCx72q8HrzTnYq4Se2x1gDuA" "Y Celeb worldwide")
      (mk "UCXXnwJW6WTK2b3i3p6GLaPw" "Magician's Got Talent")
      (mk "UCldfgbzNILYZA4dmDt4Cd6A" "Secular Talk")
      (mk "UCIeoXI9QOITF_58A-C1DZHA" "BD Design Co.")
      (mk "UCatt7TBjfBkiJWx8khav_Gg" "Piers Morgan Uncensored")
      (mk "UCjDsbbzHgTrGc4Ff26TJtsA" "E! News")
      (mk "UCGHtep7hxIpz2D6RAQ8Kp0g" "Jeremy Boreing")
      (mk "UCobLPOgCMMWVwkOjcDOHqjw" "Luxander Moss")
      (mk "UCDKJdFer1phQI95UinPZehw" "Turkey Tom")
      (mk "UCYedMp8lKCCw9y0Qe3J9huQ" "KWTX News10")
      (mk "UC8Xwcv1F_Hmg3NxsetJqdYg" "One Tiktok Mashup k")
      (mk "UCKII0Ml9S5wneKbHswmUrIQ" "CNN Indonesia")
      (mk "UClv4rIrZ8yc6jqXEDXg6Z0Q" "Ryan Beard")
      (mk "UCnwUjPK7dXety-AJ4fNw_RQ" "The Paint Explainer")
      (mk "UC5ZiUaIJ2b5dYBYGf5iEUrA" "Netflix Latinoamérica")
      (mk "UCu2fHtN58JgOUG3yaskmYrg" "DH BIHAR NEWS")
      (mk "UCh13rzqPKn5c24RU9tLz_TQ" "FOX News Podcasts")
      (mk "UCE9ZKI1b_PhVm3gejYuilhw" "IMPAULSIVE Clips")
      (mk "UCruQg25yVBppUWjza8AlyZA" "FOX 4 Dallas-Fort Worth")
      (mk "UCYWIEbibRcZav6xMLo9qWWw" "The Ring of Fire")
      (mk "UCIZGqIYkST36dLp0uf9o9nw" "The Notorious B.I.G.")
      (mk "UCLJnBT-U0CI_ldF2E-FpwdQ" "cecilily")
      (mk "UCrPhcbDwqWRc-3tteE2BS6g" "Mama Doctor Jones")
      (mk "UCVT1tPkR-fUVlO652EcO3ow" "CBS Sunday Morning")
      (mk "UCET00YnetHT7tOpu12v8jxg" "CBS Sports Golazo")
      (mk "UC6o-wWU-v2ClFMwougmK7dA" "BBC Politics")
      (mk "UCXICWhTJXqXWdC3r0LHgB1w" "Lamont Tyson")
      (mk "UCA3OHQYyLKHdI_k54SMyb6w" "Mori")
      (mk "UCIRYBXDze5krPDzAEOxFGVA" "Guardian News")
      (mk "UCmDTrq0LNgPodDOFZiSbsww" "xQc")
      (mk "UCAuUUnT6oDeKwE6v1NGQxug" "TED")
      (mk "UCDRIjKy6eZOvKtOELtTdeUA" "Breaking Points")
      (mk "UCFfD9fWqkT4PNy7v6r8ilmg" "Conservative Twins")
      (mk "UCwff7OoSHp3el6GqnSwcSdA" "T Pain")
      (mk "UC0L1suV8pVgO4pCAIBNGx5w" "60 Minutes Australia")
      (mk "UCef1-8eOpJgud7szVPlZQAQ" "CNN-News18")
      (mk "UCKwucPzHZ7zCUIf7If-Wo1g" "DD News")
      (mk "UCcc_LE8kzIzcloTVAttch5w" "Dr. Jonathan Tam")
      (mk "UCVnjt9mMx46gMUeTtONXimQ" "KENS 5: Your San Antonio News Source")
      (mk "UCl16xaNY2arX3OzZBvTlsPQ" "Steve Terreberry")
      (mk "UCnquIO-KeazvWWR38jvdu0A" "WSVN-TV")
      (mk "UCA4s5lwjkmmR9Coh1-FGItQ" "Viral Trends Daily🌏")
      (mk "UCvhPRRiwI1_p4OBsY0yz6mg" "BBC News Africa")
      (mk "UCAj9nn-gOcKuD4ropg44HCw" "DJ Noize")
      (mk "UC6ZFN9Tx6xh-skXCuRHCDpQ" "PBS NewsHour")
      (mk "UCW46hm2zWvhalt8XySF4nkg" "Daily Dose of Christ")
      (mk "UCCXoCcu9Rp7NPbTzIvogpZg" "Fox Business")
      (mk "UCIFk2uvCNcEmZ77g0ESKLcQ" "The Why Files")
      (mk "UC9bZ9eWvF0eXVqrxK9ve7Nw" "theofficialGloRilla")
      (mk "UCz6XquIbM5OcfK7r3hQQCXA" "Ludwin")
      (mk "UCpfXcgCK_RaBnXxjXzJN2Tw" "Benaminute")
      (mk "UCDVYQ4Zhbm3S2dlz7P1GBDg" "NFL")
      (mk "UC1Ahz-Lx2CkejAunMWwCpYQ" "WDTV 5 News")
      (mk "UC_mneEC0wc29EGGmIsN_xLA" "Aunty Donna")
      (mk "UCd7SCDxPEIYdXHkrpEmBXFA" "Real _ news")
      (mk "UCZkgQOMM_i7B2fy8lHxi7cA" "West Coast Finest")
      (mk "UCK0z0_5uL7mb9IjntOKi5XQ" "The Atlantic")
      (mk "UCHLyP4MuA-JAFBCwxXOEDdA" "FOX 5 Washington DC")
      (mk "UCM-eRxEc_TutiPIbOS1YYbw" "The Enforcer")
      (mk "UCPfeM2tm3T19uPf8pU3VHLg" "Ty Turner")
      (mk "UCTi3mRHhtqqrz5rXgw0F3mw" "Amazing Auditions")
      (mk "UCIveFvW-ARp_B_RckhweNJw" "StevenCrowder")
      (mk "UCojNA7ZvnmGuIvYnm44wl3Q" "WLKY News Louisville")
      (mk "UCb--64Gl51jIEVE-GLDAVTg" "C-SPAN")
      (mk "UCLHkMOoQseOPi3HptU3dq5g" "RAY LIVE")
      (mk "UCUzqsHTec5ZkJU5S4Tmhweg" "Mujin")
      (mk "UCXsB24rV6wUaLtfGJvBh-kg" "Marc Jennings")
      (mk "UCZTu831eAXKZd-5w5onpiag" "Daily Dose Of SANITY")
      (mk "UCw77677G3EAODp61b0izs7w" "6abc Philadelphia")
      (mk "UCfM3zsQsOnfWNUppiycmBuw" "EminemMusic")
      (mk "UCA4y9g_GRdNrZLH_u5LLSdw" "BanglaVision NEWS")
      (mk "UCiOPyc6yDwdxt1GSCGvleVg" "Moist Chronicles")
      (mk "UCQANb2YPwAtK-IQJrLaaUFw" "Brian Tyler Cohen")
      (mk "UCYVinkwSX7szARULgYpvhLw" "Ali-A")
      (mk "UCBBQ9PIs8ARguuwVJZowGIg" "Hasanabi Productions")
      (mk "UCAKK8dbcSmckr2sWJhv5ezA" "WBNS 10TV")
      (mk "UCFVUStJ4azXbWMhFO4yTELg" "KUTV 2 News Salt Lake City")
      (mk "UCTrQ7HXWRRxr7OsOtodr2_w" "Channel 4 News")
      (mk "UCt3tlVHWxa0rojahYIKJI_w" "Northeast Live")
      (mk "UCFJxE0l3cVYU4kHzi4qVEkw" "Rebecca Watson (Skepchick)")
      (mk "UCErZnemlR2ayaAytVYNbB1Q" "La Otra Cara del Mundo")
      (mk "UC7Q4rvzJDbHeBHYk5rnvZeA" "The Humanist Report")
      (mk "UCvCfpQXRXdJdL07pzTIA6Cw" "Kai Cenat Live")
      (mk "UC8zJedg1f4sKnyuHWeS6vyw" "50 Cent")
      (mk "UCrp_UI8XtuYfpiqluWLD7Lw" "CNBC Television")
      (mk "UCmGu_-no0e5z9PwJsXjM41A" "TikTok Dance")
      (mk "UCGzZLTFPTN4h6YVnDKk4QQg" "hloa _ ast")
      (mk "UCGRryxFxjXbVAtBPE9EbyMg" "Joe Bartolozzi")
      (mk "UCxcrzzhQDj5zKJbXfIscCtg" "ABC News In-depth")
      (mk "UC5p_l5ZeB_wGjO_yDXwiqvw" "TommyInnit")
      (mk "UCc2RL8jvY1rJPuCnJVsIQWw" "MSToons")
      (mk "UCNcFMVXgOCl5BOtbAechM5A" "unknown")
      (mk "UChF5O40UBqAc82I7-i5ig6A" "Bloomberg Podcasts")
      (mk "UCJIfeSCssxSC_Dhc5s7woww" "Lex Clips")
      (mk "UCO0akufu9MOzyz3nvGIXAAw" "News24")
      (mk "UCWElIIlFx2JiyI9UVrbrEcw" "Atlanta News First")
      (mk "UCpxlHiBcrDTRdypBBpF3xMg" "TheDuckingNerds")
      (mk "UCto0JEelepQkcueYJgUA8zw" "Nicholas Light TV")
      (mk "UCu1wUSjVGL2azTLNN_rqo3Q" "Talent Replay")
      (mk "UCgdywGAij6Nob5WealtDKXQ" "Ali-A Plays")
      (mk "UCYfJvoKTasSSty2duZ_5D2Q" "Café Fox Tale")
      (mk "UC4b0ttz3Lh1mdcNOOM23R5A" "MemeSack")
      (mk "UCXgQjCFcgaooFb-gIT1Vo-g" "POPbuzz Memes")
      (mk "UCQmWt938Z8TkdPq6uasdlbA" "diesel patches")
      (mk "UCyps-v4WNjWDnYRKmZ4BUGw" "Airrack")
      (mk "UCFx1nseXKTc1Culiu3neeSQ" "REPORTER LIVE")
      (mk "UCOa6zgAg07RodxHMk40omdA" "Freshlol")
      (mk "UCCjG8NtOig0USdrT5D1FpxQ" "NewsNation")
      (mk "UC-Bgb7bgFDczAgfoKxFneFw" "Vera’s magic tv")
      (mk "UCq6VFHwMzcMXbuKyG7SQYIg" "penguinz0")
      (mk "UCIr4vkCsn0tdTW2xZ1jRG1g" "Liberal Hivemind")
      (mk "UCIALMKvObZNtJ6AmdCLP7Lg" "Bloomberg Television")
      (mk "UCUamVL0L_lgG720vqmdZqoA" "Noodle & Pals")
      (mk "UCKjU3KzdbJE1EFcHVqXC3_g" "CBC News: The National")
      (mk "UCHVd0LM1g9S0cttDHkidEHA" "Steve Hofstetter")
      (mk "UCAMPco9PqjBbI_MLsDOO4Jw" "American Idol")
      (mk "UCp1KrVaZDZ7BOI_QBuTWWmg" "KING 5 Seattle")
      (mk "UCfwx98Wty7LhdlkxL5PZyLA" "truly")
      (mk "UCYz8MBZdBbncYv-q8Eh92RQ" "The Narrative Brief")
      (mk "UCjIngCN57O70jAo5Ez6Kmqw" "KERA")
      (mk "UC_IpSl6O_-IRAA6fiNs05Gg" "ABC")
      (mk "UCSWoppsVL0TLxFQ2qP_DLqQ" "NBCLA")
      (mk "UCP391YRAjSOdM_bwievgaZA" "Jovem Pan News")
      (mk "UCzNPh2wueY888Tt3vgzxk2Q" "Quiz Plug")
      (mk "UCBbpLKJLhIbDd_wX4ubU_Cw" "DB Live")
      (mk "UC1_yfBLZ2FNOGz9cacSibvw" "Viral Crimes")
      (mk "UCckHqySbfy5FcPP6MD_S-Yg" "Times Of India")
      (mk "UC535XrYeD-S3ZAjfCZ8hXNw" "The Quiz Show")
      (mk "UCMl6pPuV-d12pbgV5Ugugjw" "Kids Got Talent")
      (mk "UCvu9hl-2Rtn54IzHfIsOdRA" "LOLLoop")
      (mk "UCIPqOTYW439-5hUz6r3U1fA" "H.BurgerGuy")
      (mk "UCf4nYHJi6V0_lil4uGX4HwQ" "Patrick Star Official")
      (mk "UCdhF-HzXWYAQ-yNC-yX-lMQ" "graaavel")
      (mk "UCNye-wNBqNL5ZzHSJj3l8Bg" "Al Jazeera English")
      (mk "UCCFVYozQjMVOjkSTbBVK_3Q" "MacDoesIt")
      (mk "UCPahzXZvF8f5bRJ5TNvZS8w" "TYT Sports")
      (mk "UCJm2TgUqtK1_NLBrjNQ1P-w" "Second Thought")
      (mk "UCbU6Rve0XMNZ2a2yaYgjlTA" "Pondering Politics")
      (mk "UC7ddSzBrkukSCJzMIXfGEdg" "Jack Cocchiarella")
      (mk "UCPDXXXJj9nax0fr0Wfc048g" "Dropout")
      (mk "UCGmOuk25_FgwkH2HRAJIfqQ" "xQc Clips")
      (mk "UCUKOZiRKuxh6peXL19oKjZw" "FailArmy 2.0")
      (mk "UCfdNM3NAhaBOXCafH7krzrA" "The Infographics Show")
      (mk "UCG4Hp1KbGw4e02N7FpPXDgQ" "The Bulwark")
      (mk "UCnMBV5Iw4WqKILKue1nP6Hg" "Dunya News")
      (mk "UCDo9msNItILnyF_Y2eHaNQg" "RiceGum")
      (mk "UC1VKVKhJLc7PjdPPVxTDk0Q" "NBC4 Washington")
      (mk "UCRl8O0ygm0fwpmM65kxxA3w" "Late Night Hasan")
      (mk "UClQ3NafOy_42dJ0toK3QUKw" "Stay Wild")
      (mk "UCerL4WZxy37tdPyDt2x3zMA" "Trace Dominguez")
      (mk "UC9AKA0PYiGCSPqfCEMaKtag" "Trump")
      (mk "UCz2yxQJZgiB_5elTzqV7FiQ" "BOL News")
      (mk "UCsIzhRSKbRtvBGsiLHfcGOA" "CBS 12 News - WPEC")
      (mk "UCHNEMZ69yEvdro8J2yS5xlQ" "RankiGuy")
      (mk "UChDKyKQ59fYz3JO2fl0Z6sg" "TODAY")
      (mk "UCAHVeeUYu70LGb0c0Rfb5Ig" "Political Voices Network")
      (mk "UCtFQDgA8J8_iiwc5-KoAQlg" "ANI News")
      (mk "UCqFzWxSCi39LnW1JKFR3efg" "Saturday Night Live")
      (mk "UCbiYozUzj8tRetz1ihnyiIg" "Domo3000")
      (mk "UCzF4Ryn8TKn64md77gS5Q5Q" "11Alive")
      (mk "UCFTHixpysIgljmKns7_7KfA" "venom")
      (mk "UCl9roQQwv4o4OuBj3FhQdDQ" "The Damage Report")
      (mk "UCbKWv2x9t6u8yZoB3KcPtnw" "Alan Becker")
      (mk "UClI8C7mmrHfN_aDRkXmTSbw" "memom")
      (mk "UCy5tR9C0xM6tp7ha1Usq9Ag" "LIVE SNEAKO")
      (mk "UCcHJCcXClsgQQOaSPXI-99g" "Chrisie")
      (mk "UC1Cp5caGwHvJZxHoevGoDdA" "BRAIN TIME")
      (mk "UC2a35q7eyzkfoIusBzdH4Hw" "Newsweek")
      (mk "UCitnbHEoc3c9aucJE44uXeg" "Justice Korsgaard")
      (mk "UC554eY5jNUfDq3yDOJYirOQ" "Destiny")
      (mk "UCIvaYmXn910QMdemBG3v1pQ" "Zee News")
      (mk "UCPDis9pjXuqyI7RYLJ-TTSA" "FailArmy")
      (mk "UCkrtUnUL6ClHI1fMVOTEjkQ" "Dr. Daf Show")
      (mk "UCGwu0nbY2wSkW8N-cghnLpA" "JaidenAnimations")
      (mk "UCXemAinqVNGregdHyOmQ9_A" "Demetri Falco")
      (mk "UCVxBA3Cbu3pm8w8gEIoMEog" "ABC7")
      (mk "UCnWi59TPymx0_qt7PX3VeNA" "PIX11 News")
      (mk "UC0QHWhjbe5fGJEPz3sVb6nw" "Doctor Mike")
      (mk "UCIHdDJ0tjn_3j-FS7s_X1kQ" "Valuetainment")
      (mk "UCpInjhuJ1WUekcFeXPPyGGg" "Netflix Family")
      (mk "UC57XAjJ04TY8gNxOWf-Sy0Q" "5-Minute Crafts PLAY")
      (mk "UCU9WJGMn_C5AB79J3mqUr7g" "Rorschach")
      (mk "UCD2GdZBCsUa0TIssLai6Skw" "Top Talent")
      (mk "UC6cMJ0aFn_DcxQ-t7goGACQ" "Violet💖")
      (mk "UCz8QaiQxApLq8sLNcszYyJw" "Firstpost")
      (mk "UCK7tptUDHh-RYDsdxO1-5QQ" "The Wall Street Journal")
      (mk "UCHqkXbgqrDrDVInBMSoGQgQ" "The Daily Signal")
      (mk "UCytSP0M0Jdnw6qIy3Y-nTig" "NewsX Live")
      (mk "UCMwJJL5FJFuTRT55ksbQ4GQ" "Asmongold Clips")
      (mk "UCc6Dy2ljJEC2MKpCgwL4cLA" "The Punch Cut")
      (mk "UC6juUGSJu-RvOFi6DgJe1HQ" "Robert Tolppi")
      (mk "UC_NT0EK1f9CoWnzPJV1pj1A" "BBC Comedy")
      (mk "UC1yBKRuGpC1tSM73A0ZjYjQ" "The Young Turks")
      (mk "UC2064-GFZ1y5NYZuUGX4iEA" "Destiny's Child")
      (mk "UC-jaY6dGP1RhvMIunvlLktA" "The Perseverance")
      (mk "UC8CuM9DxDFfJjTnZzT_23ZA" "Rumble Ron")
      (mk "UCmYesELO6axBrCuSpf7S9DQ" "Mr. Beat")
      (mk "UCCLLvHL_ITnyhEKJjB3-wxg" "unknown")
      (mk "UCun4tg1BecN4PuxwZ6mL3NA" "National Review")
      (mk "UCHjm6wybRbldhqveS7c2WTA" "Insider News")
      (mk "UCGeBogGDZ9W3dsGx-mWQGJA" "IMPAULSIVE")
      (mk "UCc7p7J9tem8-18oJ0JzYOGg" "The Evaluator")
      (mk "UCWG2b3GNAIDx9KlpYn_WEJQ" "Celebs Goat")
      (mk "UCwH-lORF3rBFef9gk8HGwUg" "Hollywood Remix")
      (mk "UC73H5p3GP8b5N1f3hozIXyQ" "TBN Israel")
      (mk "UC3lUI0xV1brqvnfzAGwodYQ" "Acesten Harls")
      (mk "UCPTrIwdhJAlBkItRNyFcLPA" "Aidan Hall")
      (mk "UC3i1cInn3KFrn9kuU7_bJFg" "GirlShroom")
      (mk "UCjXB7nX8bL2U2sje8d212Yw" "Roland S. Martin")
      (mk "UCZZ1hYlH54T6Sd0NB4U4DQA" "Hadi Rahim")
      (mk "UC2CCXzC56k0b8L49R_iW-Yw" "DaBaby")
      (mk "UCDCmxTR1x6ylSYlh_nrJHZQ" "Victoria Rose")
      (mk "UCnwI-VN5jXWIGQKOI9PMDMw" "WPRI")
      (mk "UCGbg3DjQdcqWwqOLHpYHXIg" "The Yard")
      (mk "UC-uhvujip5deVcEtLxnW8qg" "TLDR News Global")
      (mk "UCmvayONEsLn_NOJ4k3PrLug" "ARIEL")
      (mk "UCIPPMRA040LQr5QPyJEbmXA" "MrBeast Gaming")
      (mk "UCFFbwnve3yF62-tVXkTyHqg" "Zee Music Company")
      (mk "UCejO4LBBh-PahDh6UWSx1Cg" "BN Hindi")
      (mk "UCadkYuT67cogndIMl4hbz-A" "Dev Gurjar Rasiya")
      (mk "UCUx2xAViYolMLCQAC8vgYvw" "CBS 13 News")
      (mk "UC1sAQpHqHy4SV6ZSu98xGmg" "ETimes")
      (mk "UCYvdoTAxZDGMCElpn4Rg3cQ" "Jay Black")
      (mk "UCPRUgAl_MV9PajsrG_BmT9w" "BuzzFeed Celeb")
      (mk "UCGovFxnYvAR_OozTMzQqt3A" "SSSniperWolf Top Videos")
      (mk "UCxlMUXEbzCTbV6kL1p7lcWQ" "unknown")
      (mk "UCvqtzdcURSqNjY9RQEK4XmQ" "Glenn Beck")
      (mk "UCUSySH2YjIwsDu2Hx6DWwTA" "Jesse Dollemore")
      (mk "UCFQyVljCrdof5Uqmo8p3c0Q" "13WHAM ABC News")
      (mk "UCb1Ti1WKPauPpXkYKVHNpsw" "LBC")
      (mk "UCBP39EHhfsTB4nAXpFQHjCg" "America First Drive")
      (mk "UCG0V362DBWHWavTM-JysGhw" "ProVZzz")
      (mk "UC7sL-CtxlyCPeZ0Oj95kvDQ" "NewsWest 9")
      (mk "UCPLMPHT-d8GZOqL_AHJFdQQ" "Parrot")
      (mk "UC_vFLohxs5PkAxlk7Y6jEtw" "ABC 7 Chicago")
      (mk "UC0vn8ISa4LKMunLbzaXLnOQ" "GBNews")
      (mk "UC8LK_LgSrMCUlPILJhdolhg" "Mike Flint")
      (mk "UCq18eeL7D9Vd8DhjMcLh9QQ" "Good Morning Britain")
      (mk "UCPP3etACgdUWvizcES1dJ8Q" "News18 India")
      (mk "UCg2Hrw2t8P-s_4WKKx_ShSA" "Marcus Dib")
      (mk "UCIv3LvN_0CNzMpSrTF9naNA" "The Line")
      (mk "UC-yJOYXe_gw1dAnFQ5nMhWQ" "Ohh that's RICH")
      (mk "UCbwMZHCMpBiOWfYLBOH-9Qw" "TheOfficialLoganPaul")
      (mk "UCpJlmVOckoFYvK4Mf7tM4bQ" "Onyx Kids")
      (mk "UCroKPvbmaQKGK5tjtQsvaDw" "Daily Wire News")
      (mk "UCftwRNsjfRo08xYE31tkiyw" "WIRED")
      (mk "UCgeV3tFiU2Xg0PD1dAQbBHA" "Jimmy Snow & The Line")
      (mk "UClwddNv0Cr6SIEGkzVK886w" "FOX 9 Minneapolis-St. Paul")
      (mk "UCuHeJgTeMf3r3wLv64hOUog" "Freedom Daily")
      (mk "UCcism3ZeVO42iNAh7ea91uQ" "Caden")
      (mk "UCfYW5GXBXueSO5p9bxD45qg" "BBC Global")
      (mk "UCv7BR3sK8XcH3j4WtfXK9OA" "Worst Trends")
      (mk "UCBtjFm7bmGzUb3xvYhFSHuQ" "Touchy Reactions")
      (mk "UCpJ7ZS8hK-IOeciv952Xhug" "Really American")
      (mk "UCA4sF2INOBVv2aNglhNjNNA" "RICH CRAFTS")
      (mk "UCdtXPiqI2cLorKaPrfpKc4g" "Entertainment Tonight")
      (mk "UCQLRK5wiWGmzp4dnFt0arwA" "PinkNews")
      (mk "UC4Rrzu44rIpYtuVit90Kl5w" "LA Times Studios")
      (mk "UC8BxSGcBKriJvoeyKOnJ6tA" "The Washington Examiner")
      (mk "UCTjMNDSrfpReO6atYFIbriQ" "OwlOFC")
      (mk "UCJjSDX-jUChzOEyok9XYRJQ" "Jubilee")
      (mk "UCX8pnu3DYUnx8qy8V_c6oHg" "Techno Gamerz")
      (mk "UC-4SOzdo3fpAtsPKRB1OFvA" "Destiny Productions")
      (mk "UCUkSBEJC33xb-WU-pRimdkg" "SenpaiExtras")
      (mk "UCFbU05UvawdNQNqPuE1NYxA" "التفاح الأخضر")
      (mk "UCCYWagpWEequTwx61dYGT0w" "Gianmarco Soresi")
      (mk "UCH7nv1A9xIrAifZJNvt7cgA" "ABP MAJHA")
      (mk "UCu7G08TrwPx_0WH4M7OxjIQ" "12 News")
      (mk "UCIbaZHZP3VqXRfJlAtJv6Vw" "U.S. Democratic Socialists")
      (mk "UClDtG4S7HtwnPktmu3ZIqkA" "StreamClipper")
      (mk "UCSncGB_s0tuWN-4l-58mmvQ" "ProBoiz 95")
      (mk "UC6iSAm2OgMS8e_RKuwnXzaw" "Laugh Trapped")
      (mk "UCC_K68VPF-NEPBky01ClquA" "NBC News Learn")
      (mk "UC9infsKo33_2LUoiqXGgQWg" "Renegade Cut")
      (mk "UCfcc8OORrouV1lO_qeIZVNQ" "Jimmy Here")
      (mk "UC4xuh0pSLRLhzWGUnpOlvXw" "Michael Franzese")
      (mk "UCJ69rQqmXQNdjMntJpvsgZA" "H Vee")
      (mk "UCMAtX9eFBpwc4LtgvbqsOpQ" "CrowderBits")
      (mk "UChLtXXpo4Ge1ReTEboVvTDg" "Global News")
      (mk "UCG1h-Wqjtwz7uUANw6gazRw" "Lindsay Ellis")
      (mk "UCfaIu2jO-fppCQV_lchCRIQ" "Charlie Kirk")
      (mk "UCluH8hy4VXBZancjCepXccw" "Thinking Christian")
      (mk "UC85aYbNSFjsJdxfpxgQr8tA" "Judo Sloth Gaming")
      (mk "UCGBR9bk3MCr0wrdP5iLlBBQ" "Conservative — Conservateur")
      (mk "UCupvZG-5ko_eiXAupbDfxWw" "CNN")
      (mk "UC3F9KlSIiokndbF6_S1ObiA" "JasperDasper")
      (mk "UCaXkIU1QidjPwiAYu6GcHjg" "MS NOW")
      (mk "UCTp1SMW1Wz3RPJFT6UdkisQ" "Artman")
      (mk "UCo9oQdIk1MfcnzypG3UnURA" "The Rational National")
      (mk "UCr1-1RNDJLhWqcLqz14xjxQ" "Streamer Moments")
      (mk "UCW3Ms3ZxVaZUniP-HifWCDg" "Karry Kraft")
      (mk "UCMoes0p_7J-WJuvQxBhleLg" "KasualKai54")
      (mk "UCwmZiChSryoWQCZMIQezgTg" "BBC Earth")
      (mk "UCDGknzyQfNiThyt4vg4MlTQ" "The Obama White House")
      (mk "UCBy_C4Tg58BRzyKky45Pfow" "FOX8 WGHP")
      (mk "UCHuvz9zn7t5CTGJqXj8IKCA" "Censored Views")
      (mk "UCF9LFWX5cdGHBg_FDm6tFrQ" "Breezy Politics")
      (mk "UCF-VP3b3oH0XASqsLI5rnLw" "Times Radio")
      (mk "UCJVnKZWT3WXxfG8T6EUdezw" "Disney Channel Music")
      (mk "UCttspZesZIDEwwpVIgoZtWQ" "IndiaTV")
      (mk "UC2uCqzAqQoMweYFiyENGIYQ" "Lana")
      (mk "UCIjLRyywnG8olYXAEVYGYgQ" "CMV")
      (mk "UCKkW8kJRYo0GXd1asPX3Z9Q" "Black Conservative Perspective")
      (mk "UCX6b17PVsYBQ0ip5gyeme-Q" "CrashCourse")
      (mk "UCM7M5XDIqvVUL4LIKPMHthA" "Debate Vault")
      (mk "UCJg9wBPyKMNA5sRDnvzmkdg" "LiveNOW from FOX")
      (mk "UCu80jy-7aAhPxda8_u_sxVA" "Kitty Mashup")
      (mk "UCwPy85bZrLGYDRU3AOSK8Ow" "Phat Memer")
      (mk "UCVgO39Bk5sMo66-6o6Spn6Q" "ABC News (Australia)")
      (mk "UCUBIrDsIVzRpKsClMlSlTpQ" "BBC News Mundo")
      (mk "UCIjSUWHWp6KohfnR5OQTXnQ" "FOX 5 New York")
      (mk "UCJsgJk0Nwst62HikqF8IxzQ" "Viralmashup Edits")
      (mk "UCud7qstfwb6EbgOVbD391rw" "TeasingOliver")
      (mk "UCbR7juPwtP-bV_w0840ciYQ" "Channel 4")
      (mk "UCfDIOBU2LwMah_rBxL9xjdQ" "Idiots In Cars Crash Compilation")
      (mk "UCg0VO_LJZjTzubUQ34CwnLQ" "T. Folse Nuclear")
      (mk "UCoP4V9_s2t5Wt3dZbGDRqSw" "Howieazy")
      (mk "UCcirgl5o8EPL7XeDsuIlQCg" "VERTICILE")
      (mk "UCfDdlNLRVb1h3_7Xh-WhL3w" "TheDC Shorts")
      (mk "UCtEb98_ptdXj6N6woTfgxVQ" "ICKY")
      (mk "UCrWmonkmTk5NbvmVnc7f70w" "Glenn Kirschner")
      (mk "UCCvcd0FYi58LwyTQP9LITpA" "Soft White Underbelly")
      (mk "UCfU4-ArXuSX0tpyApyklMAg" "Axios")
      (mk "UCLkOVcbrrsuljcL8ddI43VA" "Cam Higby")
      (mk "UCUxiymg0tZtu7VXHCX0yMdA" "Thrittle")
      (mk "UCXs0PlIGUDSXfBaF7j-1euA" "Don Lemon")
      (mk "UC0rE2qq81of4fojo-KhO5rg" "Tanmay Bhat")
      (mk "UCyeVfsThIHM_mEZq7YXIQSQ" "MoreAliA")
      (mk "UCw0ry7cLRUnq3Oaszlhgqfg" "DLS News")
      (mk "UC7oPkqeHTwuOZ5CZ-R9f-6w" "Triggernometry")
      (mk "UCO_DaPp4ifhMAmiyybSLx9w" "BBC Earth Kids")
      (mk "UCFZ1Dv_jsdIIUgnJVVcbqKQ" "Brut America")
      (mk "UCZ5cvDR2HhVUcdVoTvvQKLw" "I've Had It")
      (mk "UCMu5gPmKp5av0QCAajKTMhw" "ERB")
      (mk "UCFuzExfO2fUVmNK5_COvsNg" "8 News Now — Las Vegas")
      (mk "UCBR8-60-B28hp2BmDPdntcQ" "YouTube")
      (mk "UCM32F09Rdb0rRomsYvHJp2g" "unknown")
      (mk "UCiTCB-B_weEmwHk7ifNobQw" "BBC News Telugu")
      (mk "UCGttrUON87gWfU6dMWm1fcA" "Tucker Carlson")
      (mk "UCV5Ai6_xmYW5Aak5FFd0jjQ" "Loveamerica")
      (mk "UCrWdPsIgE4GIWGiFUMHL4bQ" "Sumit 007")
      (mk "UCG38HE2LucNPGFu--W7BfUA" "unknown")
      (mk "UCVdQEYBdy0lBZz4wLSdxc6Q" "Nightbirde Music")
      (mk "UCwXrBBZnIh2ER4lal6WbAHw" "Mathrubhumi News")
      (mk "UCPFzA28Hw9tYDxXAeidDk6w" "Nick Freitas")
      (mk "UC9GGzAhhvhJO1hL10-BcgNA" "Le Huffington Post")
      (mk "UCk1DyFm90mmdVbvfwhbGIMA" "Java Europe")
      (mk "UCq7OKQb6_1tbA73oSloIiZQ" "2WAY")
      (mk "UCvj3hNvwrEgTRkeut7_cBAQ" "JiDion")
      (mk "UCadMpX28EMXTCYYBg1DUJIg" "Skeeter Jean")
      (mk "UCvubOhuUIhYoYnRyXHtcygQ" "American Bridge 21st Century")
      (mk "UCM05jgFNwoeXvWfO9GuExzA" "Luke Beasley")
      (mk "UCHd62-u_v4DvJ8TCFtpi4GA" "Washington Post")
      (mk "UCIaH-gZIVC432YRjNVvnyCA" "Chris Williamson")
      (mk "UCHlo32FvGRPDk4U14VUyfYg" "critikal compilations")
    ];
  };
}
