{...}: let
  #=====================================================================#
  # FREETUBE BLOCKED CHANNELS
  #=====================================================================#
  # FreeTube re-resolves any entry missing a preferredName or icon, one
  # API call each, so entries are emitted pre-filled. The icon is a 1x1
  # transparent GIF: only the Distraction Free settings page renders it,
  # browsing thumbnails come from the API and are unaffected.
  #
  # Names are frozen at the time they were added - nothing re-resolves
  # them. Grab a new id from a channel page's "externalId" field, not the
  # first "channelId" match.
  blankIcon = "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==";

  mk = id: label: {
    name = id;
    preferredName = label;
    icon = blankIcon;
  };

  #--------------------------------------------------------------------#
  #-- Political commentary
  #--------------------------------------------------------------------#
  politicalCommentary = [
    (mk "UCq7OKQb6_1tbA73oSloIiZQ" "2WAY")
    (mk "UCyxcZgX1wNU-nk1yB9CvzSw" "Aaron Parnas")
    (mk "UC8DA4o0SyaGfyVaBLbF5EXg" "Adam Mockler")
    (mk "UCgEvEKgmQ-CHPIeOSaGCffw" "Amala Ekpunobi")
    (mk "UCpwYqKXDVQYtuib-zCoftbg" "Amanda's Mild Takes")
    (mk "UCBP39EHhfsTB4nAXpFQHjCg" "America First Drive")
    (mk "UCvubOhuUIhYoYnRyXHtcygQ" "American Bridge 21st Century")
    (mk "UCCvfdExsmntZlxlDUsNMJfg" "America Only")
    (mk "UCu28JGd1UDoQRlZZtG5Qrcw" "Amir Odom")
    (mk "UCicvc24eAbFp-thRrBnSP2A" "Answers in Genesis")
    (mk "UCSD4jzd-0jOsZ9KAe9rxmPQ" "Ashley Gavin")
    (mk "UCnQC_G5Xsjhp9fEJKuIcrSw" "Ben Shapiro")
    (mk "UC4OvD2yIbofl9l4dIlqSNMw" "Bill O'Reilly")
    (mk "UCXzC3VMKJUK-jTMtUaZz-uA" "Bills News Consolidated")
    (mk "UCLml2_OPYFkrqs38TVrcU5g" "BlackConservative24")
    (mk "UCKkW8kJRYo0GXd1asPX3Z9Q" "Black Conservative Perspective")
    (mk "UCDmCBKaKOtOrEqgsL4-3C8Q" "Blaire White")
    (mk "UCDRIjKy6eZOvKtOELtTdeUA" "Breaking Points")
    (mk "UCF9LFWX5cdGHBg_FDm6tFrQ" "Breezy Politics")
    (mk "UCQANb2YPwAtK-IQJrLaaUFw" "Brian Tyler Cohen")
    (mk "UCpQ_q9AwSgzepjnVElVY0ag" "Brian Tyler Cohen News")
    (mk "UCcism3ZeVO42iNAh7ea91uQ" "Caden")
    (mk "UCLkOVcbrrsuljcL8ddI43VA" "Cam Higby")
    (mk "UC2X6M-GBOx8nV1X5RRMVTmw" "Canada Next")
    (mk "UC790WPHI_Sewr5LqiITAz-g" "Canada Today")
    (mk "UCL0u5uz7KZ9q-pe-VC8TY-w" "Candace Owens")
    (mk "UC0Ra4Wt7u860wRJRyoRdhpg" "Capitol Central")
    (mk "UCVhSS17jxUOueWmIUYfQcWg" "Celebs AgainstTrump")
    (mk "UCfaIu2jO-fppCQV_lchCRIQ" "Charlie Kirk")
    (mk "UCIaH-gZIVC432YRjNVvnyCA" "Chris Williamson")
    (mk "UCZW7uA8PwgRhoS44Aurwp-g" "Conduit")
    (mk "UCGBR9bk3MCr0wrdP5iLlBBQ" "Conservative — Conservateur")
    (mk "UCYiYFWmU1ozUD8mTQUDmFHw" "Conservative Ladies")
    (mk "UCXNSyuKeoiHOld1OS3kHuVg" "Conservatives")
    (mk "UCFfD9fWqkT4PNy7v6r8ilmg" "Conservative Twins")
    (mk "UCvpfautZTTR1opQB04T2fTA" "Conservative Vibes")
    (mk "UCFZSV_So_OaXgXVzgu58tJQ" "cpac")
    (mk "UCMAtX9eFBpwc4LtgvbqsOpQ" "CrowderBits")
    (mk "UCroKPvbmaQKGK5tjtQsvaDw" "Daily Wire News")
    (mk "UCEfe80CP2cs1eLRNQazffZw" "Dave Smith")
    (mk "UCvixJtaXuNdMPUGdOPcY8Ag" "David Pakman Show")
    (mk "UC7d2WmQqHxc9PTJyj3bVFgw" "Dean Withers")
    (mk "UCM7M5XDIqvVUL4LIKPMHthA" "Debate Vault")
    (mk "UCzuqE7-t13O4NIDYJfakrhw" "Democracy Now!")
    (mk "UCmA3zSO1wjBGwl61SeM4a3Q" "Democratic Reporter")
    (mk "UCAql2DyGU2un1Ei2nMYsqOA" "Donald J Trump")
    (mk "UCCsiAKRKcgzA_372WbXNBaw" "Dr. Steve Turley")
    (mk "UCHZA_aJuGa4jEoJs6KW-_pw" "Energi Media")
    (mk "UC5dUUCs748wCYQl682LX6bg" "Farron Balanced")
    (mk "UCG1CoynVOh5uj12qpDLQ7fQ" "Fox Nation")
    (mk "UCuHeJgTeMf3r3wLv64hOUog" "Freedom Daily")
    (mk "UCRXnOs1rjfLMYrtZ-0n29NA" "FreedomToons")
    (mk "UCvqtzdcURSqNjY9RQEK4XmQ" "Glenn Beck")
    (mk "UCrWmonkmTk5NbvmVnc7f70w" "Glenn Kirschner")
    (mk "UCWXPkK02j6MHW-4xCJzgMuw" "Golden State Times")
    (mk "UC-8_qAhNVG8G1wxONMnYr3Q" "GZERO Media")
    (mk "UC9N7wBTsK93KJFHwAMslbVg" "HalForNY")
    (mk "UCnbKOlm6H9njgmN-Yil90Rg" "Heather Cox Richardson")
    (mk "UCZ5cvDR2HhVUcdVoTvvQKLw" "I've Had It")
    (mk "UC7ddSzBrkukSCJzMIXfGEdg" "Jack Cocchiarella")
    (mk "UCYHosdETLPp6dpJEsgIUTmw" "Jake Broe")
    (mk "UCHSIA2JRC5PWvUX4Sl8OrcA" "Jammidodger")
    (mk "UCYvdoTAxZDGMCElpn4Rg3cQ" "Jay Black")
    (mk "UC25GHmlU1I-zbNcZe7a-aiQ" "Jemele Hill")
    (mk "UCGHtep7hxIpz2D6RAQ8Kp0g" "Jeremy Boreing")
    (mk "UCUSySH2YjIwsDu2Hx6DWwTA" "Jesse Dollemore")
    (mk "UCgeV3tFiU2Xg0PD1dAQbBHA" "Jimmy Snow & The Line")
    (mk "UCNJTWkcUJoMBamCr1IW097w" "Jolah Politics")
    (mk "UCxFWzKZa74SyAqpJyVlG5Ew" "Kat Blaque")
    (mk "UCagO3YGMBqDjrWBhw7wKuGA" "Keith Edwards")
    (mk "UC3mQV9qPc4pzzYHkhTlRA-A" "Kirk Takes Daily")
    (mk "UCPZbwdXrHUXXuaDDdRuZ40A" "Kirk Unpacked")
    (mk "UCXICWhTJXqXWdC3r0LHgB1w" "Lamont Tyson")
    (mk "UCJgZJZZbnLFPr5GJdCuIwpA" "Legal AF")
    (mk "UCSHZKyawb77ixDdsGog4iWA" "Lex Fridman")
    (mk "UCIr4vkCsn0tdTW2xZ1jRG1g" "Liberal Hivemind")
    (mk "UCkBrtQrHN6Lc3vJUzXT0m6A" "Lincoln Square")
    (mk "UCV5Ai6_xmYW5Aak5FFd0jjQ" "Loveamerica")
    (mk "UCM05jgFNwoeXvWfO9GuExzA" "Luke Beasley")
    (mk "UCO01ytfzgXYy4glnPJm4PPQ" "Matt Walsh")
    (mk "UCzJXNzqz6VMHSNInQt_7q6w" "Megyn Kelly")
    (mk "UC9r9HYFxEQOBXSopFS61ZWg" "MeidasTouch")
    (mk "UC4xuh0pSLRLhzWGUnpOlvXw" "Michael Franzese")
    (mk "UCr4kgAUTFkGIwlWSodg43QA" "Michael Knowles")
    (mk "UCkRzm-ELNPhz9l4sGRx3sMQ" "Mike Nellis")
    (mk "UC6Hyj5sVbiYhpc_FA14nziw" "Mikhaila Peterson")
    (mk "UCjuKQCmKlCtrPL2wl1uIphQ" "MorePegasus")
    (mk "UCun4tg1BecN4PuxwZ6mL3NA" "National Review")
    (mk "UCn_uMY15GlwaPpx80-WjR6g" "Occupy Democrats")
    (mk "UCGX7nGXpz-CmO_Arg-cgJ7A" "PBD Podcast")
    (mk "UCatt7TBjfBkiJWx8khav_Gg" "Piers Morgan Uncensored")
    (mk "UCKRoXz3hHAu2XL_k3Ef4vJQ" "Pod Save America")
    (mk "UCAHVeeUYu70LGb0c0Rfb5Ig" "Political Voices Network")
    (mk "UCbmoYCccdSpnWdmWW4b7BlA" "Politics Exchange")
    (mk "UCyzkxMLeZDcd_Qhzh6uMgbg" "PoliticsJOE")
    (mk "UCUrfzuazQPsjSTeq4x28QXA" "PoliticsNewsPolitics")
    (mk "UCaJsUfWlqkiDxnoWrTK2iyg" "Politics & Paper")
    (mk "UClGpc-n0Tt44FEkYvs7Tzew" "PoliticusUSA")
    (mk "UCbU6Rve0XMNZ2a2yaYgjlTA" "Pondering Politics")
    (mk "UCZWlSUNDvCCS1hBiXV0zKcA" "PragerU")
    (mk "UCKpSiUg_W-scoE6ltSp4TnQ" "President Sunday")
    (mk "UCpJ7ZS8hK-IOeciv952Xhug" "Really American")
    (mk "UCuMo0RRtnNDuMB8DV5stEag" "Rebel HQ")
    (mk "UCoJhK5kMc4LjBKdiYrDtzlA" "Redacted")
    (mk "UCHqC-yWZ1kri4YzwRSt6RGQ" "Right Side Broadcasting Network")
    (mk "UCzjTWXq_oHNst5NkJY113HQ" "Riverboat Jack")
    (mk "UCkPeaJ9dwHTvq6OYrsSGz7Q" "Robert Davis")
    (mk "UCjXB7nX8bL2U2sje8d212Yw" "Roland S. Martin")
    (mk "UCldfgbzNILYZA4dmDt4Cd6A" "Secular Talk")
    (mk "UCpgILFSGxY-9mQR79fLSt2A" "Senate Democrats")
    (mk "UCIveFvW-ARp_B_RckhweNJw" "StevenCrowder")
    (mk "UCuL3xV8AqD3sekKOhhyZqOA" "Straight Arrow")
    (mk "UCSFy-1JrpZf0tFlRZfo-Rvw" "Sydney Watson")
    (mk "UCNXD5enYf0UZXccisoxLy0A" "The Biblical Conservative")
    (mk "UCHqkXbgqrDrDVInBMSoGQgQ" "The Daily Signal")
    (mk "UCaeO5vkdj5xOQHp4UmIN6dw" "The Daily Wire")
    (mk "UCl9roQQwv4o4OuBj3FhQdDQ" "The Damage Report")
    (mk "UCfDdlNLRVb1h3_7Xh-WhL3w" "TheDC Shorts")
    (mk "UClkO4MArT2WKWj32YDD_-Ew" "The Democrats")
    (mk "UCQVhgOxzt5W1fZhOd0l2E6g" "The First")
    (mk "UC5bEfSFTYQVfLCwkhBt8NtQ" "The Heritage Foundation")
    (mk "UC7Q4rvzJDbHeBHYk5rnvZeA" "The Humanist Report")
    (mk "UC3M7l8ved_rYQ45AVzS0RGA" "The Jimmy Dore Show")
    (mk "UCIv3LvN_0CNzMpSrTF9naNA" "The Line")
    (mk "UC-3jIAlnQmbbVMV6gR7K8aQ" "The Majority Report w/ Sam Seder")
    (mk "UCYz8MBZdBbncYv-q8Eh92RQ" "The Narrative Brief")
    (mk "UCDGknzyQfNiThyt4vg4MlTQ" "The Obama White House")
    (mk "UCo9oQdIk1MfcnzypG3UnURA" "The Rational National")
    (mk "UCII84rxnNkEjtk1zC3qTtbg" "The Rest Is Politics US")
    (mk "UCYWIEbibRcZav6xMLo9qWWw" "The Ring of Fire")
    (mk "UCTjDhFuGXlhx9Us0gq0VK2w" "The Trump Report")
    (mk "UC8BxSGcBKriJvoeyKOnJ6tA" "The Washington Examiner")
    (mk "UCYxRlFDqcWM4y7FfpiAN3KQ" "The White House")
    (mk "UC1yBKRuGpC1tSM73A0ZjYjQ" "The Young Turks")
    (mk "UCjRXO-HSl5XpuF-cWvtMV_g" "Tim Black TV")
    (mk "UCe02lGcO-ahAURWuxAJnjdA" "Timcast")
    (mk "UC-uhvujip5deVcEtLxnW8qg" "TLDR News Global")
    (mk "UC7oPkqeHTwuOZ5CZ-R9f-6w" "Triggernometry")
    (mk "UCXrwgY7yxq3UMMSLUJfSn2A" "TrueBlue")
    (mk "UC9AKA0PYiGCSPqfCEMaKtag" "Trump")
    (mk "UCGttrUON87gWfU6dMWm1fcA" "Tucker Carlson")
    (mk "UCmbm72l60p3OH4aL4o7BFeA" "Turning Point UK")
    (mk "UCVrK_pMRp_q8IelpfUCTGLQ" "Turning Point USA")
    (mk "UCwNJt9PYyN1uyw2XhNIQMMA" "TYT Investigates")
    (mk "UCGUJ_4gaYiwyndRzTsedMzA" "USA BS Network")
    (mk "UCIbaZHZP3VqXRfJlAtJv6Vw" "U.S. Democratic Socialists")
    (mk "UCIHdDJ0tjn_3j-FS7s_X1kQ" "Valuetainment")
    (mk "UCnJo_lQSjVHCwUzUtVqde4Q" "Vaushite")
    (mk "UCVnBaemGSz05OUyKmQjIJSA" "Warren Smith - Secret Scholar Society")
    (mk "UC2s0uKOc2WgB9eGta7cUUEA" "Washington Week PBS")
    (mk "UC4-AGCUwX7C-D4BsBook9fQ" "Young America's Foundation")
  ];

  #--------------------------------------------------------------------#
  #-- Political streamers and clip channels
  #--------------------------------------------------------------------#
  politicalStreamers = [
    (mk "UCALsgRqlpl867WCkckre1Sg" "DestinyBites")
    (mk "UCUC1Y65XvU2n9lb6GvfAQ5g" "Destiny DGG Clips")
    (mk "UCtFZqbrEByTPN8VwC5dOhqA" "Destiny Highlights")
    (mk "UCWHbFbZkrCwNxHUVlPQGLXg" "destinyhqclips")
    (mk "UC554eY5jNUfDq3yDOJYirOQ" "Destiny")
    (mk "UC-4SOzdo3fpAtsPKRB1OFvA" "Destiny Productions")
    (mk "UC2064-GFZ1y5NYZuUGX4iEA" "Destiny's Child")
    (mk "UCc30Q1bAxLtfzeS_jh7J5wQ" "HasanAbi Archive")
    (mk "UCN7jo9su_7oDqwpfin8lgjw" "Hasanabi Clips")
    (mk "UCCizpvXws0bY_VAf7DYRV5g" "HasanAbi Direct")
    (mk "UCtoaZpBnrd0lhycxYJ4MNOQ" "HasanAbi")
    (mk "UCBBQ9PIs8ARguuwVJZowGIg" "Hasanabi Productions")
    (mk "UCte9SD4XLBDFtRZD2dzj_jw" "HasanAbi Reacts")
    (mk "UCSi7XpA8swk2rJww6HEHA7g" "HasanAbi Rewind")
    (mk "UCB-MPptlCv5VCdIvAJxNwcA" "Hasanabi Yaps")
    (mk "UCoAxJF0J-kTqVS7HP0e7sfw" "HasanDaily")
    (mk "UC1hW1iEFDsW-6V0zC8jqVQA" "Hasan Reactions")
    (mk "UC4AScNTPAuPW0JtHtbfPwxQ" "HasMEMES")
    (mk "UCLOPC6bOBuiSBAJ16JXLAHg" "Last Night On Destiny")
    (mk "UCRl8O0ygm0fwpmM65kxxA3w" "Late Night Hasan")
    (mk "UCy5tR9C0xM6tp7ha1Usq9Ag" "LIVE SNEAKO")
    (mk "UCdUD6racxisHiSX9iWFcuug" "The Vaush Pit")
    (mk "UC1E-JS8L0j1Ei70D9VEFrPQ" "Vaush")
    (mk "UCcWkShE9dqAw8uM1RJC99fQ" "Xanderhal")
  ];

  #--------------------------------------------------------------------#
  #-- News networks
  #--------------------------------------------------------------------#
  newsNetworks = [
    (mk "UC0L1suV8pVgO4pCAIBNGx5w" "60 Minutes Australia")
    (mk "UC5T7D-Dh1eDGtsAFCuwv_Sw" "7NEWS Australia")
    (mk "UCunkVlKjHWCJ6OKfffus19Q" "ABC News 4")
    (mk "UCVgO39Bk5sMo66-6o6Spn6Q" "ABC News (Australia)")
    (mk "UCxcrzzhQDj5zKJbXfIscCtg" "ABC News In-depth")
    (mk "UCBi2mrWuNuyYy4gbM6fU18Q" "ABC News")
    (mk "UCJSxCOEw2SopkddtjbE4ZaA" "ABC World News Tonight")
    (mk "UC52X5wxOL_s5yw0dQk7NtgA" "Associated Press")
    (mk "UCfYW5GXBXueSO5p9bxD45qg" "BBC Global")
    (mk "UCBwejc-awS-mANgrkHQ5-6A" "BBC London")
    (mk "UCCj956IF62FbT7Gouszaj9w" "BBC")
    (mk "UCYUPBf8y9ggcnpBxCKZteHA" "BBC News Gujarati")
    (mk "UC16niRr50-MSBwiO3YDb3RA" "BBC News")
    (mk "UCUBIrDsIVzRpKsClMlSlTpQ" "BBC News Mundo")
    (mk "UC3780MVtSV3Huj4si_CQvlQ" "BBC News සිංහල")
    (mk "UC6o-wWU-v2ClFMwougmK7dA" "BBC Politics")
    (mk "UCQXHTFnQYFTqN0MqmNh9EIA" "BBC World Service")
    (mk "UChirEOpgFCupRAk5etXqPaA" "Bloomberg News")
    (mk "UChF5O40UBqAc82I7-i5ig6A" "Bloomberg Podcasts")
    (mk "UCIALMKvObZNtJ6AmdCLP7Lg" "Bloomberg Television")
    (mk "UCuFFtHWoLl5fauMMD5Ww2jA" "CBC News")
    (mk "UCKjU3KzdbJE1EFcHVqXC3_g" "CBC News: The National")
    (mk "UCYI_ychRnL7sJrG6PUSBpQA" "CBN News")
    (mk "UCAeWdyKJXGWmVAXFpgLNNTg" "CBS Evening News")
    (mk "UC-SJ6nODDmufqBzPBwCvYvQ" "CBS Mornings")
    (mk "UC8p1vwvWtl6T73JiExfWs1g" "CBS News")
    (mk "UCVT1tPkR-fUVlO652EcO3ow" "CBS Sunday Morning")
    (mk "UCbR7juPwtP-bV_w0840ciYQ" "Channel 4")
    (mk "UCTrQ7HXWRRxr7OsOtodr2_w" "Channel 4 News")
    (mk "UCrp_UI8XtuYfpiqluWLD7Lw" "CNBC Television")
    (mk "UCmRbHAgG2k2vDUvb3xsEunQ" "CNBC-TV18")
    (mk "UCTOoRgpHTjAQPk6Ak70u-pA" "CNN 10")
    (mk "UC_lEiu6917IJz03TnntWUaQ" "CNN en Español")
    (mk "UCupvZG-5ko_eiXAupbDfxWw" "CNN")
    (mk "UCb--64Gl51jIEVE-GLDAVTg" "C-SPAN")
    (mk "UCi7Zk9baY1tvdlgxIML8MXg" "CTV News")
    (mk "UCyI4gi0BtlKiUl6KgtuVIUw" "CTV Your Morning")
    (mk "UCknLrEdhRCp1aegoMqRaCZg" "DW News")
    (mk "UC2x_qNZXKDxNP1j4jvHATRQ" "Face the Nation")
    (mk "UCg40OxZ1GYh3u3jBntB6DLg" "Forbes Breaking News")
    (mk "UCCXoCcu9Rp7NPbTzIvogpZg" "Fox Business")
    (mk "UCqlYzSgsh5jdtWYfVIBoTDw" "Fox News Clips")
    (mk "UCXIJgqnII2ZOINSWNOGFThA" "Fox News")
    (mk "UCh13rzqPKn5c24RU9tLz_TQ" "FOX News Podcasts")
    (mk "UCQfwfsi5VrQ8yKZ-UWmAEFg" "FRANCE 24 English")
    (mk "UC0vn8ISa4LKMunLbzaXLnOQ" "GBNews")
    (mk "UChLtXXpo4Ge1ReTEboVvTDg" "Global News")
    (mk "UCH1oRy1dINbMVp3UFWrKP0w" "Good Morning America")
    (mk "UCq18eeL7D9Vd8DhjMcLh9QQ" "Good Morning Britain")
    (mk "UCIRYBXDze5krPDzAEOxFGVA" "Guardian News")
    (mk "UC9k-yiEpRHMNVOnOi_aQK8w" "Inside Edition")
    (mk "UCHjm6wybRbldhqveS7c2WTA" "Insider News")
    (mk "UCb1Ti1WKPauPpXkYKVHNpsw" "LBC")
    (mk "UCJg9wBPyKMNA5sRDnvzmkdg" "LiveNOW from FOX")
    (mk "UCaXkIU1QidjPwiAYu6GcHjg" "MS NOW")
    (mk "UCC_K68VPF-NEPBky01ClquA" "NBC News Learn")
    (mk "UCeY0bbntWzzVIaj2z3QigXg" "NBC News")
    (mk "UCx6h-dWzJ5NpAlja1YsApdg" "Newsmax")
    (mk "UCCjG8NtOig0USdrT5D1FpxQ" "NewsNation")
    (mk "UCn4sPeUomNGIr26bElVdDYg" "NowThis Impact")
    (mk "UC6ZFN9Tx6xh-skXCuRHCDpQ" "PBS NewsHour")
    (mk "UChqUTb7kYRX8-EiaN3XFrSQ" "Reuters")
    (mk "UCTln5ss6h6L_xNfMeujfPbg" "Scripps News")
    (mk "UCoMdktPbSTixAyNGwb-UYkQ" "Sky News")
    (mk "UCmuTmpLY35O3csvhyA6vrkg" "TeleSUR English")
    (mk "UCj6EKBe990fanr4MSh45Alw" "The Canadian Press")
    (mk "UCvAnclelY8eSq8GyPE19KTw" "The National Desk")
    (mk "UCeH6qE4V7n5tVwP7NkdrtJg" "The View")
    (mk "UCF-VP3b3oH0XASqsLI5rnLw" "Times Radio")
    (mk "UChDKyKQ59fYz3JO2fl0Z6sg" "TODAY")
    (mk "UCKY1msUI1iVtnKHPaLOsiQg" "Yahoo News")
  ];

  #--------------------------------------------------------------------#
  #-- Local and regional news
  #--------------------------------------------------------------------#
  localNews = [
    (mk "UCzF4Ryn8TKn64md77gS5Q5Q" "11Alive")
    (mk "UCFQyVljCrdof5Uqmo8p3c0Q" "13WHAM ABC News")
    (mk "UCw77677G3EAODp61b0izs7w" "6abc Philadelphia")
    (mk "UCFuzExfO2fUVmNK5_COvsNg" "8 News Now — Las Vegas")
    (mk "UC_vFLohxs5PkAxlk7Y6jEtw" "ABC 7 Chicago")
    (mk "UCVxBA3Cbu3pm8w8gEIoMEog" "ABC7")
    (mk "UCYUbNjkuE4lsr2v1Id2O1oA" "ABC7 News Bay Area")
    (mk "UCfIjR00qhYUFkbWIugAAbGg" "ABC 7 News - WJLA")
    (mk "UCWElIIlFx2JiyI9UVrbrEcw" "Atlanta News First")
    (mk "UCsIzhRSKbRtvBGsiLHfcGOA" "CBS 12 News - WPEC")
    (mk "UCUx2xAViYolMLCQAC8vgYvw" "CBS 13 News")
    (mk "UCMKP8n1dUg-b84lfpb0mfdA" "CBS6 Albany")
    (mk "UCxMXl9L79X1Mq_4iwCOyPFg" "CBS TEXAS")
    (mk "UCoGav6jgImtvjpogwhRr7Wg" "Chicago_News")
    (mk "UC-2MJlKSq9_pYk5-bdvMhnw" "Denver7")
    (mk "UCNjfNLnQYbjBEvnS8KFuyGQ" "FOX 10 Phoenix")
    (mk "UC5bKZHg4PzURMOWcvanl6nA" "FOX 13 Seattle")
    (mk "UC4OqEJz6oABzz_7nu29zF3A" "FOX 26 Houston")
    (mk "UCqdOvfSmM2NKRNE0FSbATuw" "FOX 29 Philadelphia")
    (mk "UCOGa-48fFt4cW0UnW5WSdRg" "FOX 2 Detroit")
    (mk "UCFmofUYwZd1Ibf_O3PF71jg" "FOX 32 Chicago")
    (mk "UCruQg25yVBppUWjza8AlyZA" "FOX 4 Dallas-Fort Worth")
    (mk "UCjHWv2DU5-HLpogAAr386DQ" "FOX 5 Atlanta")
    (mk "UCIjSUWHWp6KohfnR5OQTXnQ" "FOX 5 New York")
    (mk "UCHLyP4MuA-JAFBCwxXOEDdA" "FOX 5 Washington DC")
    (mk "UC5maSolHQX9er0BOxrzjMwA" "FOX 7 Austin")
    (mk "UCBy_C4Tg58BRzyKky45Pfow" "FOX8 WGHP")
    (mk "UClwddNv0Cr6SIEGkzVK886w" "FOX 9 Minneapolis-St. Paul")
    (mk "UCiiiNujtnT1ULcEXCWIFjQw" "Houston Public Media")
    (mk "UC4Ec_7qJhQlYjVWn0ZhMrSg" "K9 Multimedia")
    (mk "UCjq9ElqnV7Df6NLb4oDHKqQ" "KCENNews")
    (mk "UCie7RmdcnvXA1FXHRJa7WtA" "KCTV5 News")
    (mk "UCVnjt9mMx46gMUeTtONXimQ" "KENS 5: Your San Antonio News Source")
    (mk "UCjIngCN57O70jAo5Ez6Kmqw" "KERA")
    (mk "UCa-x5T8TD99WYST764WhsEA" "KEZI 9")
    (mk "UCp1KrVaZDZ7BOI_QBuTWWmg" "KING 5 Seattle")
    (mk "UCKbj5d8f70i0AYLyiJ3YMXg" "KMPH FOX26 NEWS")
    (mk "UCNXjJ4Igw2Ir8774eBNb4yA" "KRCG 13")
    (mk "UCwPzlQU2MqEQJWgqM_0VFKQ" "KSBW Action News 8")
    (mk "UCMiY4t431lhXY4QtPZtzftQ" "KSIClips")
    (mk "UCinjnmQEwCddOudyCC1v7qA" "KTLA 5")
    (mk "UCFVUStJ4azXbWMhFO4yTELg" "KUTV 2 News Salt Lake City")
    (mk "UCYedMp8lKCCw9y0Qe3J9huQ" "KWTX News10")
    (mk "UCxCfoSInadl-4i3F70zDt1A" "NBC New York")
    (mk "UCnWi59TPymx0_qt7PX3VeNA" "PIX11 News")
    (mk "UCStCUMvCw067Nw5uSlbyDsw" "THV11")
    (mk "UCzOrrheF99HIxv9Do2K5ghw" "UNIVISION LOS ANGELES")
    (mk "UCAKK8dbcSmckr2sWJhv5ezA" "WBNS 10TV")
    (mk "UCry2gCVdntv6r661sKUiKXw" "WCCO - CBS Minnesota")
    (mk "UC1Ahz-Lx2CkejAunMWwCpYQ" "WDTV 5 News")
    (mk "UCBu0KdNokE4MqdkacvH37_A" "WFAA")
    (mk "UCByGc7P_siORkC1pum8T3_Q" "WFSB 3")
    (mk "UCDrLGkZTcNCshOLiKi5NtEw" "WGN News")
    (mk "UCTvZcgH_rsvaGuZ8mU5jpnA" "WHAS11")
    (mk "UCk_e9rhSH_Gg4Mp44Ut72ZQ" "WIN Compilation")
    (mk "UC_gUM8rL-Lrg6O3adPW9K1g" "WION")
    (mk "UCNBmxc6FvKyxtCpUygcdINA" "WKYC Channel 3")
    (mk "UCojNA7ZvnmGuIvYnm44wl3Q" "WLKY News Louisville")
    (mk "UCnwI-VN5jXWIGQKOI9PMDMw" "WPRI")
    (mk "UCnquIO-KeazvWWR38jvdu0A" "WSVN-TV")
    (mk "UCcT6w3xUyVshyR2_2vrMp1w" "WUSA9")
  ];

  #--------------------------------------------------------------------#
  #-- International news
  #--------------------------------------------------------------------#
  internationalNews = [
    (mk "UCsgC5cbz3DE2Shh34gNKiog" "92 News HD")
    (mk "UCIYLOcEUX6TbBo7HQVF2PKA" "9 News Australia")
    (mk "UC_2irx_BQR7RsBKmUV9fePQ" "ABN Telugu")
    (mk "UCH7nv1A9xIrAifZJNvt7cgA" "ABP MAJHA")
    (mk "UCRWFSbif-RFENbBrSiez1DA" "ABP NEWS")
    (mk "UCV3Nm3T-XAgVhKH9jT0ViRg" "AJ+")
    (mk "UCNye-wNBqNL5ZzHSJj3l8Bg" "Al Jazeera English")
    (mk "UCvi6hEzLM-Z_unKPSuuzKvg" "ANC 24/7")
    (mk "UCtFQDgA8J8_iiwc5-KoAQlg" "ANI News")
    (mk "UCMmpLL2ucRHAXbNHiCPyIyg" "ARY News")
    (mk "UCekbhIcWL_x4bYVZPZZi0iw" "Asianet News English")
    (mk "UCjElJyiXmQXnWmceQ1JyKrA" "Asianet Suvarna News")
    (mk "UCbgcYEdMsuypG2NJ-znBp3w" "ATN Bangla News")
    (mk "UCA4y9g_GRdNrZLH_u5LLSdw" "BanglaVision NEWS")
    (mk "UCvhPRRiwI1_p4OBsY0yz6mg" "BBC News Africa")
    (mk "UCN7B-QD0Qgn2boVH5Q0pOWg" "BBC News Hindi")
    (mk "UCiTCB-B_weEmwHk7ifNobQw" "BBC News Telugu")
    (mk "UCejO4LBBh-PahDh6UWSx1Cg" "BN Hindi")
    (mk "UCz2yxQJZgiB_5elTzqV7FiQ" "BOL News")
    (mk "UCKII0Ml9S5wneKbHswmUrIQ" "CNN Indonesia")
    (mk "UCef1-8eOpJgud7szVPlZQAQ" "CNN-News18")
    (mk "UCKwucPzHZ7zCUIf7If-Wo1g" "DD News")
    (mk "UCadkYuT67cogndIMl4hbz-A" "Dev Gurjar Rasiya")
    (mk "UCXISYK3xagaK5DHnhQ4X0hw" "Diario AS")
    (mk "UCw0ry7cLRUnq3Oaszlhgqfg" "DLS News")
    (mk "UCnMBV5Iw4WqKILKue1nP6Hg" "Dunya News")
    (mk "UCzI8K9xO_5E-4iCP7Km6cRQ" "Faye D'Souza")
    (mk "UCz8QaiQxApLq8sLNcszYyJw" "Firstpost")
    (mk "UCgAPgHNmQSG_ySHRiOVeF4Q" "FOCUS online")
    (mk "UCJVBaQLwyTfxbvoP5A9G6rA" "Gama")
    (mk "UC_vt34wimdCzdkrzVejwX9g" "Geo News")
    (mk "UCqYw-CTd1dU2yGI71sEyqNw" "GMA News")
    (mk "UCBc13XYipnBIBE3Ff8QaaGg" "IBC24")
    (mk "UCYPvAwZP8pZhSMW8qs7cVCw" "India Today")
    (mk "UCttspZesZIDEwwpVIgoZtWQ" "IndiaTV")
    (mk "UC3v3VpUyf34SLfN1IyUlMeA" "inside nepal news")
    (mk "UCN5tcDI7z6vN9s3p3n_JtoQ" "Jorge Ramos")
    (mk "UCd9fzbANRDUO8UlSb0fg34w" "Jotaerre")
    (mk "UCP391YRAjSOdM_bwievgaZA" "Jovem Pan News")
    (mk "UCErZnemlR2ayaAytVYNbB1Q" "La Otra Cara del Mundo")
    (mk "UCwXrBBZnIh2ER4lal6WbAHw" "Mathrubhumi News")
    (mk "UCWCEYVwSqr7Epo6sSCfUgiw" "MIRROR NOW")
    (mk "UCZFMm1mMw0F81Z37aaEzTUA" "NDTV")
    (mk "UCwd8Byi93KbnsYmCcKLExvQ" "Negocios TV")
    (mk "UC531MlZA5LUbeGwEN_zcppw" "News18 Bihar Jharkhand")
    (mk "UCPP3etACgdUWvizcES1dJ8Q" "News18 India")
    (mk "UC9IQhNgS43lmUdU-KdGyb0A" "News18 Urdu")
    (mk "UCO0akufu9MOzyz3nvGIXAAw" "News24")
    (mk "UCEW9foRmk4UdbzacT8KCYkA" "News Ganga")
    (mk "UCtbo6_eDG7zEtaOtcSltJkA" "NewsTamil 24X7")
    (mk "UCytSP0M0Jdnw6qIy3Y-nTig" "NewsX Live")
    (mk "UCUsm-fannqOY02PNN67C0KA" "NMás")
    (mk "UCt3tlVHWxa0rojahYIKJI_w" "Northeast Live")
    (mk "UCRwA1NUcUnwsly35ikGhp0A" "Noticias Telemundo")
    (mk "UCumtYpCY26F6Jr3satUgMvA" "NTV Telugu")
    (mk "UCqTa3sNT6SfiQ2DQK_kuWlA" "Oneindia News")
    (mk "UC8Z-VjXBtDJTvq6aqkIskPg" "Polimer News")
    (mk "UCmyKnNRH0wH-r8I-ceP-dsg" "PuthiyathalaimuraiTV")
    (mk "UCLHkMOoQseOPi3HptU3dq5g" "RAY LIVE")
    (mk "UCFx1nseXKTc1Culiu3neeSQ" "REPORTER LIVE")
    (mk "UCcukTqc1cJJ4K3c4uzxTzjA" "The China Show")
    (mk "UCx8Z14PpntdaxCt2hakbQLQ" "The Lallantop")
    (mk "UC6RJ7-PaXg6TIH2BzZfTV7w" "Times Now")
    (mk "UCMk9Tdc-d1BIcAFaSppiVkw" "Times Now Navbharat")
    (mk "UCw8Fc5R0Q5yyS3KrDCPM3xg" "Times Now World")
    (mk "UCckHqySbfy5FcPP6MD_S-Yg" "Times Of India")
    (mk "UCIvaYmXn910QMdemBG3v1pQ" "Zee News")
    (mk "UCFbU05UvawdNQNqPuE1NYxA" "التفاح الأخضر")
  ];

  #--------------------------------------------------------------------#
  #-- Print and digital press
  #--------------------------------------------------------------------#
  printMedia = [
    (mk "UCb0tMboxhHE8Jx6-nhJmRPw" "Allure")
    (mk "UCfU4-ArXuSX0tpyApyklMAg" "Axios")
    (mk "UCFZ1Dv_jsdIIUgnJVVcbqKQ" "Brut America")
    (mk "UCWmMgbc1g6g5O8Tn_-k5qgA" "Democracy Docket")
    (mk "UCY9eEaH19ulZmdusctU1ejA" "Glamour")
    (mk "UC4Rrzu44rIpYtuVit90Kl5w" "LA Times Studios")
    (mk "UC2a35q7eyzkfoIusBzdH4Hw" "Newsweek")
    (mk "UCrvhNP_lWuPIP6QZzJmM-bw" "New York Post")
    (mk "UCm1fqkJ-Tq64bQzM6VRMicQ" "New York Times Opinion")
    (mk "UCQLRK5wiWGmzp4dnFt0arwA" "PinkNews")
    (mk "UCgjtvMmHXbutALaw9XzRkAg" "POLITICO")
    (mk "UCmagDxvmbBpjzKg09LmBSow" "Punchbowl News")
    (mk "UC0VvxW6DEAVxIEfWgBnuaMQ" "ShareAmerica")
    (mk "UCK0z0_5uL7mb9IjntOKi5XQ" "The Atlantic")
    (mk "UCG4Hp1KbGw4e02N7FpPXDgQ" "The Bulwark")
    (mk "UC7qZ_e097NBkgOljy1joVRA" "The Daily Beast")
    (mk "UCACRim7l0tmc5lhNnDQyUvQ" "The Dallas Morning News")
    (mk "UCmk6ZFMy1CT80orXca4tKew" "The Financial Express")
    (mk "UCSRRURbKlPf1HwPUhjmufTg" "The Free Press")
    (mk "UCHpw8xwDNhU9gdohEcJu4aA" "The Guardian")
    (mk "UCPWXiRWZ29zrxPFIQT7eHSA" "The Hill")
    (mk "UC3EmxrWVl7K8xBH_UVIWY4Q" "The Mirror")
    (mk "UCqnbDFdCpuN8CMEg0VuEBqA" "The New York Times")
    (mk "UCIzXayRP7-P0ANpq-nD-h5g" "The Sun")
    (mk "UCPgLNge0xqQHWM5B5EFH9Cg" "The Telegraph")
    (mk "UCHmb7OFncrZ7BRpMxTzsP4g" "The US Sun")
    (mk "UCK7tptUDHh-RYDsdxO1-5QQ" "The Wall Street Journal")
    (mk "UC8Su5vZCXWRag13H53zWVwA" "TIME")
    (mk "UCP6HGa63sBC7-KHtkme-p-g" "USA TODAY")
    (mk "UCVxZlxikHMY8LzspzinH1ww" "Us Weekly")
    (mk "UCn8zNIfYAQNdrFRrr8oibKw" "VICE")
    (mk "UCLXo7UDZvByw2ixzpQCufnA" "Vox")
    (mk "UCw0_9Iih3qM_I_gFLrJeNRg" "Wall Street Journal Opinion")
    (mk "UCHd62-u_v4DvJ8TCFtpi4GA" "Washington Post")
    (mk "UCftwRNsjfRo08xYE31tkiyw" "WIRED")
    (mk "UCMliswJ7oukCeW35GSayhRA" "WSJ News")
    (mk "UCEAZeUIeJs0IjQiqTCdVSIg" "Yahoo Finance")
  ];

  #--------------------------------------------------------------------#
  #-- BBC non-news channels
  #--------------------------------------------------------------------#
  bbcNonNews = [
    (mk "UCCwUTfKeDj4p9uTNrn9U6Sw" "BBC Archive")
    (mk "UC_NT0EK1f9CoWnzPJV1pj1A" "BBC Comedy")
    (mk "UCO_DaPp4ifhMAmiyybSLx9w" "BBC Earth Kids")
    (mk "UCwmZiChSryoWQCZMIQezgTg" "BBC Earth")
    (mk "UCDYT9mM3L_ByrPYMyl0MGGg" "BBC Ideas")
    (mk "UCHaHD477h-FeBbVh9Sh7syA" "BBC Learning English")
    (mk "UCxi4yNzqJhjs4u6fLRonU1A" "BBC Playback")
    (mk "UC-FQUIVQ-bZiefzBiQAa8Fw" "BBC Radio 1")
  ];

  #--------------------------------------------------------------------#
  #-- Entertainment and late night
  #--------------------------------------------------------------------#
  entertainment = [
    (mk "UCLUZ6ShyBV3vnUAVMlUs4_g" "Absolute Documentaries")
    (mk "UC_mneEC0wc29EGGmIsN_xLA" "Aunty Donna")
    (mk "UCEZHP3ngrpdDuO-v1eYfdow" "Botched")
    (mk "UCPRUgAl_MV9PajsrG_BmT9w" "BuzzFeed Celeb")
    (mk "UCQSg8ZOrr1tH9mrmMYilfjw" "Celebrity Substitute")
    (mk "UCWG2b3GNAIDx9KlpYn_WEJQ" "Celebs Goat")
    (mk "UCRmDJhK_ocN5jXBRIEAyNXg" "Comedy Central Africa")
    (mk "UCUsN5ZwHx2kILm84-jPDeXw" "Comedy Central")
    (mk "UCpLB7kBu9O5dbBKhaIOmqcQ" "DeFranco News Clips")
    (mk "UCXs0PlIGUDSXfBaF7j-1euA" "Don Lemon")
    (mk "UCPDXXXJj9nax0fr0Wfc048g" "Dropout")
    (mk "UCYLR1ghzYNyvfjw78raCuxA" "Dr. Phil")
    (mk "UCjDsbbzHgTrGc4Ff26TJtsA" "E! News")
    (mk "UCdtXPiqI2cLorKaPrfpKc4g" "Entertainment Tonight")
    (mk "UC1sAQpHqHy4SV6ZSu98xGmg" "ETimes")
    (mk "UCKy1dAqELo0zrOtPkf0eTMw" "IGN")
    (mk "UCa6vGFO9ty8v5KZJXQxdhaw" "Jimmy Kimmel Live")
    (mk "UCJjSDX-jUChzOEyok9XYRJQ" "Jubilee")
    (mk "UC3XTzVzaHQEd30rQbuvCtTQ" "LastWeekTonight")
    (mk "UCVTyTA7-g9nopHeHbeuvpRA" "Late Night with Seth Meyers")
    (mk "UCAUO8EhsSTz02stvKDupChQ" "MTV News")
    (mk "UChFnGuCZ_Fb4DhbxRm9N9UQ" "Oprah")
    (mk "UCmyjVwYZbp5YPYTUyeopO2g" "Pawn Stars")
    (mk "UClFSU9_bUb4Rc6OYfTt5SPw" "Philip DeFranco")
    (mk "UCXgQjCFcgaooFb-gIT1Vo-g" "POPbuzz Memes")
    (mk "UCqFzWxSCi39LnW1JKFR3efg" "Saturday Night Live")
    (mk "UCPJHQ5_DLtxZ1gzBvZE99_g" "Smosh Alike")
    (mk "UCGie8GMlUo3kBKIopdvumVQ" "Still Watching Netflix")
    (mk "UCwWhs_6x42TyRM4Wstoq8HA" "The Daily Show")
    (mk "UCGq-a57w-aPwyi3pW7XLiHw" "The Diary Of A CEO")
    (mk "UCMtFAi84ehTSYSE9XoHefig" "The Late Show with Stephen Colbert")
    (mk "UC8-Th83bH_thdKZDJCrn88g" "The Tonight Show Starring Jimmy Fallon")
    (mk "UCQlJ7XpBtiMLKNSd4RAJmRQ" "The Weekly Show with Jon Stewart")
    (mk "UC2vlpX8sNDBmPcY_1_QSGJg" "tlc uk")
    (mk "UCK7IIV6Q2junGSdYK3BmZMg" "TMZ")
    (mk "UCaWd5_7JhbQBe4dknZhsHJg" "WatchMojo.com")
  ];

  #--------------------------------------------------------------------#
  #-- Educational and video essay
  #--------------------------------------------------------------------#
  educationalAndEssay = [
    (mk "UCbKWv2x9t6u8yZoB3KcPtnw" "Alan Becker")
    (mk "UCC552Sd-3nyi_tk2BudLUzA" "AsapSCIENCE")
    (mk "UCr3cBLTYmIK9kY0F_OdFWFQ" "Casually Explained")
    (mk "UCNvsIonJdJ5E4EXMa65VYpA" "ContraPoints")
    (mk "UCX6b17PVsYBQ0ip5gyeme-Q" "CrashCourse")
    (mk "UC0QHWhjbe5fGJEPz3sVb6nw" "Doctor Mike")
    (mk "UCnFRJ3mNt6nL9vMHduwCCyg" "Ellii (formerly ESL Library)")
    (mk "UClt01z1wHHT7c5lKcU8pxRQ" "hbomberguy")
    (mk "UClHVl2N3jPEbkNJVx-ItQIQ" "HealthyGamerGG")
    (mk "UCErKUCncCyBgEdxWAtrj5hg" "Hip Hughes (HipHughes)")
    (mk "UCHvGJ-eAV8krPgqofo65WYQ" "Illustrate to Educate")
    (mk "UCGwu0nbY2wSkW8N-cghnLpA" "JaidenAnimations")
    (mk "UCmGSJVG3mCRXVOP4yZrU1Dw" "Johnny Harris")
    (mk "UCpa-Zb0ZcQjTCPP1Dx_1M8Q" "LegalEagle")
    (mk "UCG1h-Wqjtwz7uUANw6gazRw" "Lindsay Ellis")
    (mk "UCrPhcbDwqWRc-3tteE2BS6g" "Mama Doctor Jones")
    (mk "UCmYesELO6axBrCuSpf7S9DQ" "Mr. Beat")
    (mk "UCFJxE0l3cVYU4kHzi4qVEkw" "Rebecca Watson (Skepchick)")
    (mk "UC9infsKo33_2LUoiqXGgQWg" "Renegade Cut")
    (mk "UCJquYOG5EL82sKTfH9aMA9Q" "Rick Beato")
    (mk "UCJm2TgUqtK1_NLBrjNQ1P-w" "Second Thought")
    (mk "UCJ6o36XL0CpYb6U5dNBiXHQ" "Shaun")
    (mk "UCsooa4yRKGN_zEE8iknghZA" "TED-Ed")
    (mk "UCAuUUnT6oDeKwE6v1NGQxug" "TED")
    (mk "UCsT0YIqwnpJCM-mx7-gSA4Q" "TEDx Talks")
    (mk "UCg0VO_LJZjTzubUQ34CwnLQ" "T. Folse Nuclear")
    (mk "UCfdNM3NAhaBOXCafH7krzrA" "The Infographics Show")
    (mk "UCkS_HP3m9NXOgswVAKbMeJQ" "Then & Now")
    (mk "UCnwUjPK7dXety-AJ4fNw_RQ" "The Paint Explainer")
    (mk "UCerL4WZxy37tdPyDt2x3zMA" "Trace Dominguez")
  ];

  #--------------------------------------------------------------------#
  #-- Streamers
  #--------------------------------------------------------------------#
  streamers = [
    (mk "UCyps-v4WNjWDnYRKmZ4BUGw" "Airrack")
    (mk "UCQeRaTukNYft1_6AZPACnog" "Asmongold TV")
    (mk "UCfiWa7d6um8dAb9hSz2UD-w" "Bryton Myler")
    (mk "UC0IWRLai-BAwci_e9MylNGw" "CarryisLive")
    (mk "UCBbpLKJLhIbDd_wX4ubU_Cw" "DB Live")
    (mk "UC9CSR-6NKXXCLq1igyW70mg" "doggity")
    (mk "UCP45EebTGl1ISj2DX33A2Rg" "Fanum Live")
    (mk "UCWsDFcIhY2DBi3GB5uykGXA" "IShowSpeed")
    (mk "UCvj3hNvwrEgTRkeut7_cBAQ" "JiDion")
    (mk "UCfcc8OORrouV1lO_qeIZVNQ" "Jimmy Here")
    (mk "UCyNzZ1wgkOWkzYE0zbs7zhA" "Jynxzi Live")
    (mk "UCjiXtODGCCulmhwypZAWSag" "Jynxzi")
    (mk "UCvCfpQXRXdJdL07pzTIA6Cw" "Kai Cenat Live")
    (mk "UCGmnsW623G1r-Chmo5RB4Yw" "KSI")
    (mk "UC2V1ul4ul85kac0Y81wXTqQ" "Kwite")
    (mk "UCrPseYLGpNygVi34QpGNqpA" "Ludwig")
    (mk "UCz6XquIbM5OcfK7r3hQQCXA" "Ludwin")
    (mk "UC4-79UOlP48-QNGgCko5p2g" "MrBeast 2")
    (mk "UCq6VFHwMzcMXbuKyG7SQYIg" "penguinz0")
    (mk "UCtu2BCnJoFGRBOuIh570QWw" "Sodapoppin")
    (mk "UCke6I9N4KfC968-yRcd5YRg" "SSundee")
    (mk "UCLldJScHWCtsFlfanYXS8nQ" "Stable Ronaldo Live")
    (mk "UCGbg3DjQdcqWwqOLHpYHXIg" "The Yard")
    (mk "UC5p_l5ZeB_wGjO_yDXwiqvw" "TommyInnit")
    (mk "UCfwx98Wty7LhdlkxL5PZyLA" "truly")
    (mk "UCDKJdFer1phQI95UinPZehw" "Turkey Tom")
    (mk "UC37PFGlxWgx4tU6SlhPCdCw" "whatever")
    (mk "UCmDTrq0LNgPodDOFZiSbsww" "xQc")
    (mk "UCWyDCS2xtZgab_MUlhmpQZA" "YourRAGE")
    (mk "UC2kkU18MIJpUaCdokZj3_kQ" "Zeducation")
  ];

  #--------------------------------------------------------------------#
  #-- Clip channels
  #--------------------------------------------------------------------#
  clipChannels = [
    (mk "UCMwJJL5FJFuTRT55ksbQ4GQ" "Asmongold Clips")
    (mk "UCdSS1S6jnCAqNz0ttO6boOw" "ClipNeverStop")
    (mk "UCsuqAjJtlUP1XxnXeXjSpxg" "Critikal Chronicles")
    (mk "UCHlo32FvGRPDk4U14VUyfYg" "critikal compilations")
    (mk "UC6KAzM2H6GFxI78kXfopgGg" "DailySpeedClips")
    (mk "UCbGCHkeXk7hV09XkJL0atbg" "Fear& Clips")
    (mk "UCE9ZKI1b_PhVm3gejYuilhw" "IMPAULSIVE Clips")
    (mk "UCIQqnNggjzmAM_RHwwH-IaA" "ImStillxQc")
    (mk "UCnxGkOGNMqQEUMvroOWps6Q" "JRE Clips")
    (mk "UCQfrWrZ6-XHGO0wgoODqXww" "KingofClipz")
    (mk "UCJIfeSCssxSC_Dhc5s7woww" "Lex Clips")
    (mk "UClSzp3HiF1N1gz1E2xzxtGg" "Livestreams Memes")
    (mk "UC4EQHfzIbkL_Skit_iKt1aA" "Moist Charlie Clips")
    (mk "UCiOPyc6yDwdxt1GSCGvleVg" "Moist Chronicles")
    (mk "UCWjBqATYrifMWdw-J84k8XA" "Parker Highlights")
    (mk "UCqJSzfY0TUADFHkw6tEOoOQ" "politics clips")
    (mk "UClDtG4S7HtwnPktmu3ZIqkA" "StreamClipper")
    (mk "UCHbZa_koHjqy_H5Wz3AGjjg" "Streamer Highlights")
    (mk "UCr1-1RNDJLhWqcLqz14xjxQ" "Streamer Moments")
    (mk "UCDT1meaKQ_D1HjhTGULNbew" "Streamers Reloaded")
    (mk "UCnwp0iOA4LjPhubDdPXsHWQ" "StreamerTV")
    (mk "UCqOPTuLESVvDJtxooEJ9tVw" "StreamOnCNN")
    (mk "UC4aqtbSmF7jDxOeiD19eZCA" "Tiny Clipper")
    (mk "UCnMp_7DVSGuzNfTpNKWVldw" "TommyKayVODs")
    (mk "UCaON315MhreLMfHRchLnKlg" "Twitch Scrubing")
    (mk "UCGmOuk25_FgwkH2HRAJIfqQ" "xQc Clips")
    (mk "UCPpN3Hbkc9Ck3-H22WaT3SA" "xqcttvjuice")
  ];

  #--------------------------------------------------------------------#
  #-- Reaction channels
  #--------------------------------------------------------------------#
  reactionChannels = [
    (mk "UCUaT_39o1x6qWjz7K2pWcgw" "Beast Reacts")
    (mk "UC-8t7yvYJaBy2QJ0O_Xllsw" "DUSK Reacts")
    (mk "UCD4UWbxOOrFsxkMMfjYQ0VA" "Foltyn Reacts")
    (mk "UCYOaYgTPCwEN9AvDjZ78HMA" "Kawaii Reaction")
    (mk "UCfIOSIFur-qFToVKahB0A6w" "L3WG Reacts")
    (mk "UC7wV9BwhmNksC2VxZbOqiZA" "Nogla & Terroriser React")
    (mk "UCR4z8ccOWNoUThB4VAMNBTg" "OUR STUPID REACTIONS")
    (mk "UCtDzHr6meh7Y_n6JqSmHazg" "Rayactions")
    (mk "UC0v-tlzsn0QZwJnkiaUSJVQ" "REACT")
    (mk "UCp0Dqeb9JEDJ8aDSWur3ZRQ" "REACTORS GOIN' CRAZY | RGC")
    (mk "UCBtjFm7bmGzUb3xvYhFSHuQ" "Touchy Reactions")
    (mk "UCxsjWbW_inWEEgfZyJoyS2A" "Zero React")
  ];

  #--------------------------------------------------------------------#
  #-- Gaming
  #--------------------------------------------------------------------#
  gaming = [
    (mk "UC3YUjC9f7GMRWzOKYgibk3A" "All About Fortnite")
    (mk "UCD1Em4q90ZUK2R5HKesszJg" "Clash of Clans")
    (mk "UCb5RPUFX8Cr4ye-mukGYgtw" "Clash of Time")
    (mk "UC85aYbNSFjsJdxfpxgQr8tA" "Judo Sloth Gaming")
    (mk "UCuuBNabOJHBc5rZfX4He9pA" "KreekCraft Hub")
    (mk "UCJHBJ7F-nAIlMGolm0Hu4vg" "Maizen")
    (mk "UCAYgEH1TAiRyd6iyk0JrzvQ" "Mike Plays")
    (mk "UCN14VoNSni7WqcGeuWn2OLg" "OrionGplays")
    (mk "UCJZam2u1G0syq3kyqrCXrNw" "PrestonPlayz")
    (mk "UCSncGB_s0tuWN-4l-58mmvQ" "ProBoiz 95")
    (mk "UCX8pnu3DYUnx8qy8V_c6oHg" "Techno Gamerz")
  ];

  #--------------------------------------------------------------------#
  #-- Kids and family
  #--------------------------------------------------------------------#
  kidsAndFamily = [
    (mk "UC3wCAOfSB0W9iuKDDtNJeGw" "Danny Go!")
    (mk "UCJVnKZWT3WXxfG8T6EUdezw" "Disney Channel Music")
    (mk "UCNcdbMyA59zE-Vk668bKWOg" "Disney Jr.")
    (mk "UC7Gf2tZ8coTX2ckTPgn62iQ" "Disney Kids")
    (mk "UCMl6pPuV-d12pbgV5Ugugjw" "Kids Got Talent")
    (mk "UCpInjhuJ1WUekcFeXPPyGGg" "Netflix Family")
    (mk "UC5ZiUaIJ2b5dYBYGf5iEUrA" "Netflix Latinoamérica")
    (mk "UCPFzA28Hw9tYDxXAeidDk6w" "Nick Freitas")
    (mk "UCUamVL0L_lgG720vqmdZqoA" "Noodle & Pals")
    (mk "UC_976xMxPgzIa290Hqtk-9g" "Walt Disney Animation Studios")
  ];

  #--------------------------------------------------------------------#
  #-- Music artists and label channels
  #--------------------------------------------------------------------#
  musicArtists = [
    (mk "UC8zJedg1f4sKnyuHWeS6vyw" "50 Cent")
    (mk "UCztGY3Qsxxk7JDSY3Q_iXsw" "Best HipHop Music")
    (mk "UCnkvVqNcHpAs5JNJW7-9Syw" "Big Tymers")
    (mk "UClSTuQObWlw56blWZiW-wcw" "Bobby Shmurda")
    (mk "UC2CCXzC56k0b8L49R_iW-Yw" "DaBaby")
    (mk "UCqREBYw4H7SZyCXiUJXifVA" "Daniela Avanzini")
    (mk "UCZjR0cPlO91NNQ-6fgvtuhA" "Dexta Daps")
    (mk "UCgwv23FVv3lqh567yagXfNg" "DisneyMusicVEVO")
    (mk "UC0L4FNvqduCM49XPjb8dZHQ" "Disney - Topic")
    (mk "UC0Kgvj5t_c9EMWpEDWJuR1Q" "DJ Khaled")
    (mk "UCAj9nn-gOcKuD4ropg44HCw" "DJ Noize")
    (mk "UCfM3zsQsOnfWNUppiycmBuw" "EminemMusic")
    (mk "UCfIXdjDQH9Fau7y99_Orpjw" "Gorillaz")
    (mk "UCaxOQZrF5llUMp-JjesUz1A" "Lil Durk")
    (mk "UCO9zJy7HWrIS3ojB4Lr7Yqw" "Lil Wayne")
    (mk "UC8mnXeOlR9hC2w8aYqY9WNQ" "Loudwire")
    (mk "UC9YcTIQuhwgoOQqYMKYqW9A" "Migos ATL")
    (mk "UCDLeP5A0yBqGUW8FrhWdDTw" "Rich Gang")
    (mk "UCbpqhOEGlI-1lS4GfAeV2vA" "Soulja Boy")
    (mk "UCIZGqIYkST36dLp0uf9o9nw" "The Notorious B.I.G.")
    (mk "UC9bZ9eWvF0eXVqrxK9ve7Nw" "theofficialGloRilla")
    (mk "UCwff7OoSHp3el6GqnSwcSdA" "T Pain")
    (mk "UCzgxx_DM2Dcb9Y1spb9mUJA" "TWICE")
    (mk "UCZkgQOMM_i7B2fy8lHxi7cA" "West Coast Finest")
    (mk "UCy0dTlYgFtwyItApHRHPdAw" "Worldwide Music")
    (mk "UCx72q8HrzTnYq4Se2x1gDuA" "Y Celeb worldwide")
    (mk "UCFFbwnve3yF62-tVXkTyHqg" "Zee Music Company")
  ];

  #--------------------------------------------------------------------#
  #-- Talent show farms
  #--------------------------------------------------------------------#
  talentShows = [
    (mk "UCTi3mRHhtqqrz5rXgw0F3mw" "Amazing Auditions")
    (mk "UCAMPco9PqjBbI_MLsDOO4Jw" "American Idol")
    (mk "UCT2X19JJaJGUN7mrYuImANQ" "America's Got Talent")
    (mk "UCtTLxG2tRLjB0aXMNWCmvhw" "Asia's Got Talent")
    (mk "UCUtZaxDF3hD5VK4xRYFBePQ" "Britain's Got Talent")
    (mk "UCOtR7QEHj32VrfbvhKr9FlA" "Canada's Got Talent")
    (mk "UCVG21WPT3_7rgPskQbmAyfA" "France's Got Talent")
    (mk "UCMPNAq4xRaz2XMtYSvm8oOA" "Freakin' Famous Auditions")
    (mk "UCOlq7FRJdf0QtfsPtwZ64Cg" "Golden Voices")
    (mk "UCe_Fx4EZAgKjDz0aQ_Y7hSA" "Got Talent Global")
    (mk "UCCuJoMu1y_o9pczBxshPmqw" "Got Talent Shorts")
    (mk "UCcyqdK1u6GfpBy1LW0bmzrw" "Got Talent South Africa")
    (mk "UCIBHwinVPgVmIRiFJdX40fA" "Ireland's Got Talent")
    (mk "UCXXnwJW6WTK2b3i3p6GLaPw" "Magician's Got Talent")
    (mk "UCi70qFIwSUyMgxT5ZjR2zQg" "TALENTKINGHD")
    (mk "UCSWwb_YyNB8vuC1VDcfPPaQ" "Talent Recap")
    (mk "UCu1wUSjVGL2azTLNN_rqo3Q" "Talent Replay")
    (mk "UCbDSo4C1f1SnKsAzHOpTdUA" "Talent Rewind")
    (mk "UCVvdPoakKrgavRTdFxRvC1w" "The Vocalyst")
    (mk "UCeBWh-0p7vgBeD6HOHBpfwQ" "Top 10 Talent")
    (mk "UCD2GdZBCsUa0TIssLai6Skw" "Top Talent")
    (mk "UCDnEa2HC2eeT-cN3pAKnNTw" "Top Viral Talent")
    (mk "UCM9LVNOFrL5BWmXA3c3Rngg" "World Best Talent")
  ];

  #--------------------------------------------------------------------#
  #-- Viral, meme and reupload farms
  #--------------------------------------------------------------------#
  viralAndMemeReuploads = [
    (mk "UCyYhxPxa-bYr-IIAGIV33PQ" "Drama Kween")
    (mk "UCllmCh9Zat9OaNyc3fRDJag" "Funny Zone")
    (mk "UCwH-lORF3rBFef9gk8HGwUg" "Hollywood Remix")
    (mk "UCu80jy-7aAhPxda8_u_sxVA" "Kitty Mashup")
    (mk "UC6iSAm2OgMS8e_RKuwnXzaw" "Laugh Trapped")
    (mk "UCvu9hl-2Rtn54IzHfIsOdRA" "LOLLoop")
    (mk "UC6EmR959HIts4gzdt80t3Xg" "Mega YTP")
    (mk "UC4b0ttz3Lh1mdcNOOM23R5A" "MemeSack")
    (mk "UC-sHeRGtnOcqt5tXh1nG9OQ" "memes from hole")
    (mk "UClI8C7mmrHfN_aDRkXmTSbw" "memom")
    (mk "UCu-AT1u3_FQdML2l_ODpvCA" "memot")
    (mk "UCfnpUsAB6Qb-HpEiCy3ZPiA" "Mo Funny")
    (mk "UCzC-UXOUfSMTA0k6UeQD8dQ" "momem")
    (mk "UC9MpuWZatMPIJVo_b_FCSKA" "MoonlightEdits")
    (mk "UC8Xwcv1F_Hmg3NxsetJqdYg" "One Tiktok Mashup k")
    (mk "UCRRsHRG0qzS42KAK1YsEr-g" "One TikTok Mashup")
    (mk "UCwPy85bZrLGYDRU3AOSK8Ow" "Phat Memer")
    (mk "UCW7DEppFdRIbcuYREFiMJAQ" "Rare Memes")
    (mk "UCbq3nNZKry1KjS6n0jw6S_Q" "TikTok CREEPY")
    (mk "UCmGu_-no0e5z9PwJsXjM41A" "TikTok Dance")
    (mk "UC56RKHnIutm-L99-fhxulDA" "Tik Tok Now")
    (mk "UCpnkp_D4FLPCiXOmDhoAeYA" "UnusualVideos")
    (mk "UC1_yfBLZ2FNOGz9cacSibvw" "Viral Crimes")
    (mk "UCmSPDMxfLphFJlZirsHbP0A" "Viral Feed")
    (mk "UCJsgJk0Nwst62HikqF8IxzQ" "Viralmashup Edits")
    (mk "UClkXLaqttTs8YJHyuZ_wVKA" "Viral Memes")
    (mk "UC-NPQYmHM9AagZg2GfaiiBw" "Viral Now")
    (mk "UCj6Ed6HiG3EHJP80EQ1L9bg" "Viral Sap")
    (mk "UCA4s5lwjkmmR9Coh1-FGItQ" "Viral Trends Daily🌏")
    (mk "UCYCFeGE0Y8QlWJsho8-r1_w" "ViralVideoLab")
    (mk "UCl_LO48OHG9K8A3Js8Hj40g" "Viral Voices")
    (mk "UCccLJcTFQAVcFGOWcF1DTtw" "V U Meme")
    (mk "UCv7BR3sK8XcH3j4WtfXK9OA" "Worst Trends")
  ];

  #--------------------------------------------------------------------#
  #-- Sports
  #--------------------------------------------------------------------#
  sports = [
    (mk "UCET00YnetHT7tOpu12v8jxg" "CBS Sports Golazo")
    (mk "UCja8sZ2T4ylIqjggA1Zuukg" "CBS Sports")
    (mk "UCiWLfSweyRNmLpgEHekhoAg" "ESPN")
    (mk "UCDVYQ4Zhbm3S2dlz7P1GBDg" "NFL")
    (mk "UCPahzXZvF8f5bRJ5TNvZS8w" "TYT Sports")
    (mk "UCvgfXK4nTYKudb0rFR6noLA" "UFC")
    (mk "UCJ5v_MCY6GNUBTO8-D3XoAg" "WWE")
  ];

  #--------------------------------------------------------------------#
  #-- Low-effort and clickbait
  #--------------------------------------------------------------------#
  lowEffort = [
    (mk "UCO9-nEt-Ymh8e-GbfK6HDOg" "Amazing News Today")
    (mk "UC4e-87tzDuHYE0RNTjqYOPQ" "Baby News Network")
    (mk "UC1Cp5caGwHvJZxHoevGoDdA" "BRAIN TIME")
    (mk "UCUKOZiRKuxh6peXL19oKjZw" "FailArmy 2.0")
    (mk "UCPDis9pjXuqyI7RYLJ-TTSA" "FailArmy")
    (mk "UCesUN0qMfhDMO7Tacx-Py3g" "Fail Impact")
    (mk "UC-_mPIOcPS5EiR0gWG9go1g" "FailSide Moment")
    (mk "UCw6s_N3IQI4sswTSfLoIUrA" "Funny Local News")
    (mk "UCIPPMRA040LQr5QPyJEbmXA" "MrBeast Gaming")
    (mk "UCpJlmVOckoFYvK4Mf7tM4bQ" "Onyx Kids")
    (mk "UCzNPh2wueY888Tt3vgzxk2Q" "Quiz Plug")
    (mk "UC535XrYeD-S3ZAjfCZ8hXNw" "The Quiz Show")
    (mk "UCMY4o8_rPjmFoatx7F4TvHQ" "Twinkl Kids TV")
  ];

  #--------------------------------------------------------------------#
  #-- Other - individual creators and unsorted
  #--------------------------------------------------------------------#
  misc = [
    (mk "UCu7G08TrwPx_0WH4M7OxjIQ" "12 News")
    (mk "UCup3etEdjyF1L3sRbU-rKLw" "24 News")
    (mk "UCR9120YBAqMfntqgRTKmkjQ" "A24com")
    (mk "UC_IpSl6O_-IRAA6fiNs05Gg" "ABC")
    (mk "UC3lUI0xV1brqvnfzAGwodYQ" "Acesten Harls")
    (mk "UCPTrIwdhJAlBkItRNyFcLPA" "Aidan Hall")
    (mk "UCvo3jQe4L1ZaSwdQHHQ1Zqw" "Alec Gunter")
    (mk "UCQVfy3QRi9zM7hp1m6ECKcg" "AlphaExtra")
    (mk "UCnGVtqzoexqB5Nb-R_E51XA" "American Secrets")
    (mk "UCGGsXUUTM6h0Dyomfm2p2Lg" "Amethysta Herrick, Ph.D.")
    (mk "UCT0YzdGNnZYWm40dDV6DLMQ" "Amirah _mix")
    (mk "UCnFmWQbVW_YbqPQZGNuq8sA" "Andrew Dotson")
    (mk "UCrhRdj-SbmakNH7Zmyg2mUw" "Anomaly Report")
    (mk "UCv8klVLFrL_Mf9JZAx5IDzw" "Arash Esfandiari")
    (mk "UCmvayONEsLn_NOJ4k3PrLug" "ARIEL")
    (mk "UC1PGcfaJ8lFEzgEGn6nm7fw" "Arikido")
    (mk "UCTp1SMW1Wz3RPJFT6UdkisQ" "Artman")
    (mk "UCczFNVVax0S1tOIBp-QGw-Q" "AtteDee")
    (mk "UCA6oXQTT_mtCj32dZDdoL6w" "Basic Logic")
    (mk "UCIeoXI9QOITF_58A-C1DZHA" "BD Design Co.")
    (mk "UCpfXcgCK_RaBnXxjXzJN2Tw" "Benaminute")
    (mk "UCETZ7OiW7-wqwb-6hsz3C4w" "Bionic")
    (mk "UCKgJEs_v0JB-6jWb8lIy9Xw" "BlazeTV")
    (mk "UCnmtYnwv3h-yxgVhMUeZJ8Q" "boody")
    (mk "UCAebQubO4U1HQaR-rwsqUhA" "Bowblax")
    (mk "UCKETYkwpPAQ09rd47iLoIsQ" "brookesharks")
    (mk "UCSP_VKyy6EKtloF625wut5Q" "BruhMan")
    (mk "UCoFITRWg-ut6p78rnnBi52A" "BubblePinkElle")
    (mk "UCYfJvoKTasSSty2duZ_5D2Q" "Café Fox Tale")
    (mk "UCLe_q9axMaeTbjN0hy1Z9xA" "Caleb Hammer")
    (mk "UCjuN2-heR5gBGIUG_E9Qrxg" "camkablam")
    (mk "UCbuTTnEzYIACGCZUegN0fKg" "Capital Insight")
    (mk "UClqifC6Nd7v-IfTqce4k62A" "Carry Depie")
    (mk "UCYELGPo--bqZX_XcnJvdIJA" "Casey Blake")
    (mk "UCrwbBzP11NhxRUCRKx_BgoQ" "Cash Jordan")
    (mk "UC0eLBYhxW9HC0P9PXQ73mpQ" "Cash")
    (mk "UCTtU4q8rJK0IBWkwli-rCEQ" "Catalyst")
    (mk "UCi4fcBVyo4CAnmdgXeO-NvA" "CBS Boston")
    (mk "UCkBS_xU1WQ7FVsDoQ_OPeDg" "CBS Chicago")
    (mk "UCVuFPbAjTi3mqpH-0veJRWg" "CBS Philadelphia")
    (mk "UCOEvClYLRZcT5bNCCI5eMKg" "CBS Pittsburgh")
    (mk "UCLJnBT-U0CI_ldF2E-FpwdQ" "cecilily")
    (mk "UCHuvz9zn7t5CTGJqXj8IKCA" "Censored Views")
    (mk "UCcHJCcXClsgQQOaSPXI-99g" "Chrisie")
    (mk "UCIjLRyywnG8olYXAEVYGYgQ" "CMV")
    (mk "UCt-XpD0mhZVj2zUJb3i0b1Q" "Compilation Beast")
    (mk "UCJwE0uGZCI31R-dlgdlbvtA" "CorinXV")
    (mk "UCRlCbdMywk2q4Bd-5nyiIOQ" "Cozy Cup Music")
    (mk "UCEs5MQjXJq27-X2vgdwtYDw" "Dagar")
    (mk "UCacgRtCiBjKeVnnPMU44ung" "Daily Denims")
    (mk "UCW46hm2zWvhalt8XySF4nkg" "Daily Dose of Christ")
    (mk "UCZTu831eAXKZd-5w5onpiag" "Daily Dose Of SANITY")
    (mk "UCw3fku0sH3qA3c3pZeJwdAw" "Daily Mail World")
    (mk "UCEH_fkvXZCMwPY1pKyEyM3Q" "DailyRapUpCrew")
    (mk "UCmdR4DlZgP4rEslW12Dv_kg" "Dangerously Informed with Evie")
    (mk "UCyy1V55KUxnlaj8QQ6M6nhw" "darkishalfcrazy")
    (mk "UCpHHJHwi5kwPNBC7qNz_pUg" "Dave Neal")
    (mk "UC66VoFZ2upgvnpnQduoHTZA" "decunnew")
    (mk "UCXemAinqVNGregdHyOmQ9_A" "Demetri Falco")
    (mk "UCjqyxpqA_88GWbZVB2E-Z_A" "Demurly Media")
    (mk "UCoo9priHndMj6q9tpGtZrMg" "Deprivation Slept")
    (mk "UC5DZ4oicRvd_rCK7zxTBXFQ" "Devin Gibson")
    (mk "UCu2fHtN58JgOUG3yaskmYrg" "DH BIHAR NEWS")
    (mk "UCQmWt938Z8TkdPq6uasdlbA" "diesel patches")
    (mk "UCoh6A539KgTaqXenKj4hgWg" "Dima The Show")
    (mk "UCqD7wgVS7jjJcJ8u0W9tt-Q" "DimpleVideo")
    (mk "UCfoxSKJm9pD1Ojb-ZiaOafQ" "Dingo")
    (mk "UCq5guwoq4CLsNOU-Zkp4waA" "Discovering Fiona")
    (mk "UCdZmX-f3TDaRhnhM4KLM4SQ" "Doctor ER")
    (mk "UC9HQXWbt14wTdr_Tzc8ZE0A" "Doctor Youn")
    (mk "UCJn6P-l72V2v5wVHtNXS5RQ" "Doll Deranged")
    (mk "UCbiYozUzj8tRetz1ihnyiIg" "Domo3000")
    (mk "UCKti4xis1ZJ2FQFAuDQ1kpg" "Dr. Ben")
    (mk "UCkrtUnUL6ClHI1fMVOTEjkQ" "Dr. Daf Show")
    (mk "UCTkXRDQl0luXxVQrRQvWS6w" "Dream")
    (mk "UCUNtD-UN-fQHHteLHK9HgvQ" "Dr. Fatima")
    (mk "UCOmjR-JVOshlZbUoQYOCxWg" "Dr. G Explains")
    (mk "UCcc_LE8kzIzcloTVAttch5w" "Dr. Jonathan Tam")
    (mk "UCQztlwsK5pV45U8vMtfbWjg" "Dr. Jordan B Cooper")
    (mk "UCMA7L1oRCozJaehbDFF6p_Q" "DT is Back")
    (mk "UCLhoj8ijqBVymbVD48hhQIQ" "Dumbsville")
    (mk "UCWnmTyhtsVRXGdbBOW4Rr1w" "DyQuell Dontae")
    (mk "UCdLE2uABtZjc9aLDFl5_BPQ" "EarthMan")
    (mk "UCtRTXkq7LrqwPdfaeGW8Axw" "Eden is Online")
    (mk "UCqIsmb6AmjzsewSAqsFdSbA" "ellis")
    (mk "UC9s1PI-BH7qOdmZKXbBDNxg" "Epic Rap Battle Parodies")
    (mk "UCMu5gPmKp5av0QCAajKTMhw" "ERB")
    (mk "UC-EMx2EV7ntOaNytwNiCyeg" "Erica Forever After")
    (mk "UCJLiLff4-TOFD-RR4-Ue_dA" "FairyPrincessLucy")
    (mk "UCpXyxLahbn7vZfR5fexenuw" "Flats Two")
    (mk "UCpWSYhAy698xPkfDXd87GwA" "FlawlessKevin")
    (mk "UC-PYaO3-ikcOLYKmvdN_CwA" "Food Club")
    (mk "UCsJKFktV0oUOB6reMpg_0pQ" "Free Roaming Photography")
    (mk "UCOa6zgAg07RodxHMk40omdA" "Freshlol")
    (mk "UCHOtZ0eGmaYibbHfzwdST1Q" "Friends From Work")
    (mk "UC0aSHiQNMy8IMmS7_8WbtdA" "FunkyFrogBait")
    (mk "UCdrBnBNLsN4_cH32HWbr9qg" "GH'S")
    (mk "UCCYWagpWEequTwx61dYGT0w" "Gianmarco Soresi")
    (mk "UC3i1cInn3KFrn9kuU7_bJFg" "GirlShroom")
    (mk "UC18w0GiCganWW6XeXcw4wgg" "glamspot1")
    (mk "UCPSdTC-PYah-O9B_QwaaYyw" "GlazeDaOne")
    (mk "UCnTtVY_CHmub27aFurnTanw" "Glimpse Grid")
    (mk "UCdhF-HzXWYAQ-yNC-yX-lMQ" "graaavel")
    (mk "UC-_fdI6-TJPwHAeXZcmwnsg" "GreenCat")
    (mk "UCZZ1hYlH54T6Sd0NB4U4DQA" "Hadi Rahim")
    (mk "UC5UyDGFC39h9Mcnem7aNNrg" "Happy Pancake")
    (mk "UCf1mRk7vSkC-89IHf0PL97g" "HaveYouBeenOutside")
    (mk "UCIPqOTYW439-5hUz6r3U1fA" "H.BurgerGuy")
    (mk "UC_zmPqauxanOAGszXfdipEA" "HeelvsBabyface")
    (mk "UCxAGqUo8Qm5jyFyxjs78B0w" "Hellion.Vision")
    (mk "UCGzZLTFPTN4h6YVnDKk4QQg" "hloa _ ast")
    (mk "UCyri-PL3l4Dn9IooWXQAqfA" "Hook Global")
    (mk "UCoP4V9_s2t5Wt3dZbGDRqSw" "Howieazy")
    (mk "UCJ69rQqmXQNdjMntJpvsgZA" "H Vee")
    (mk "UCABZ7Z6SBTp4IsARDceOq7w" "HYPE+")
    (mk "UCtEb98_ptdXj6N6woTfgxVQ" "ICKY")
    (mk "UCfDIOBU2LwMah_rBxL9xjdQ" "Idiots In Cars Crash Compilation")
    (mk "UCQyDIp03A6tsck3w29gflfg" "imKaiL00L")
    (mk "UCoA4Xlmkop9PlSGuGdrHm5A" "Infatheline")
    (mk "UC_iUeUzozCHEReJ-shKcCYA" "Internet Anarchist")
    (mk "UCyZVCV9xhrCyz4hPehvb4Wg" "Internet Today")
    (mk "UCuZBxbwknYtE30Qdh0dQ1Tg" "Jacksinfo")
    (mk "UCEk4EFSCvSPtZDTck_RLsOQ" "Jamesito")
    (mk "UC4CtHwx1jBdPlYCFX-UjPAw" "James's Army")
    (mk "UC8op54WYWHOloW620_r6S1A" "Jason Rosenbaum")
    (mk "UC3F9KlSIiokndbF6_S1ObiA" "JasperDasper")
    (mk "UCk1DyFm90mmdVbvfwhbGIMA" "Java Europe")
    (mk "UCYj0JoiJtU-nJtvaHHYozZw" "Jeff Square")
    (mk "UC8pOnl4XYXcKfZ_aWBO0o_A" "JiDionPremium")
    (mk "UCV98lDQ42J3PDjNQIpdoYmg" "JKW Compilations")
    (mk "UCGRryxFxjXbVAtBPE9EbyMg" "Joe Bartolozzi")
    (mk "UCoRQI9DCEzCpfvI21puHEtA" "Johnnie Guilbert")
    (mk "UCYLS9TSah19IsB8yyUpiDzg" "Jordindian")
    (mk "UCW2QOSa8rtTRreEqqkYcmmg" "Jovan Bradley")
    (mk "UCJS4UHGP6Q3BI-0ZIGrGXgw" "Junkeyy")
    (mk "UCitnbHEoc3c9aucJE44uXeg" "Justice Korsgaard")
    (mk "UCG5Kp09WJc3rJ5QjUY_AEug" "Justin Trouble")
    (mk "UCrYrcFGGs_nke1MggS8Jvqg" "Karl")
    (mk "UCW3Ms3ZxVaZUniP-HifWCDg" "Karry Kraft")
    (mk "UCMoes0p_7J-WJuvQxBhleLg" "KasualKai54")
    (mk "UCi13cFku9P5M2ykAWDdIeZg" "Keegan Tatum")
    (mk "UChVO_r6gSLH_usmjUfiXU3Q" "Know way no how")
    (mk "UC_62jYuKq0O-K66pjrK5jhQ" "Knox Hill")
    (mk "UC2uCqzAqQoMweYFiyENGIYQ" "Lana")
    (mk "UCPkq1dBinCcXQJYv1Skfw4A" "Latest T M")
    (mk "UCQtEIMnABKkglAlrASZ4p9w" "Leaflit & Asari")
    (mk "UClstjKOVQ1V-BhFP8arH2XQ" "Leana Deeb")
    (mk "UC9GGzAhhvhJO1hL10-BcgNA" "Le Huffington Post")
    (mk "UCXxyynFIIszB0pSQfbAOkmA" "Life, take two!")
    (mk "UCC974Jswc2RGhCmCpxF2boQ" "Lily Simpson")
    (mk "UC2bW_AY9BlbYLGJSXAbjS4Q" "Live Speedy")
    (mk "UCt06i6t7Nn8hg2TVcYDsgcA" "LJ")
    (mk "UCQc3Rhsw8dl-vl13UUWYRQQ" "London Storm")
    (mk "UCpMTplwUKH5D7jJ_O_YTWyg" "Lord Tmanoz")
    (mk "UCobLPOgCMMWVwkOjcDOHqjw" "Luxander Moss")
    (mk "UCCFVYozQjMVOjkSTbBVK_3Q" "MacDoesIt")
    (mk "UC30nbd6-eUIvRi5zMCTRI1Q" "Maceツ")
    (mk "UCGLA2qQ_N_83Spcjz51d8HA" "MAGNO NEWS")
    (mk "UCyOMUZ7f2DJDCeTRAYuwudQ" "Make That Change")
    (mk "UCXsB24rV6wUaLtfGJvBh-kg" "Marc Jennings")
    (mk "UCg2Hrw2t8P-s_4WKKx_ShSA" "Marcus Dib")
    (mk "UCd8Aox2OXxfrHloMwjZCBFw" "Mario Adrion")
    (mk "UCloH7JPn0CtzIJnThe125_g" "MB14")
    (mk "UCdIE3qqvO6hybTXtG0gux2w" "MedaBuzz")
    (mk "UC8LK_LgSrMCUlPILJhdolhg" "Mike Flint")
    (mk "UCA3OHQYyLKHdI_k54SMyb6w" "Mori")
    (mk "UCc2RL8jvY1rJPuCnJVsIQWw" "MSToons")
    (mk "UCUzqsHTec5ZkJU5S4Tmhweg" "Mujin")
    (mk "UC1VKVKhJLc7PjdPPVxTDk0Q" "NBC4 Washington")
    (mk "UCSWoppsVL0TLxFQ2qP_DLqQ" "NBCLA")
    (mk "UC9KUAdPr9Rb8MEyuvL59J4A" "Neilla Uwase")
    (mk "UCuzS3rPQAYqHcLWqOFuY0pw" "News 24")
    (mk "UC7sL-CtxlyCPeZ0Oj95kvDQ" "NewsWest 9")
    (mk "UCto0JEelepQkcueYJgUA8zw" "Nicholas Light TV")
    (mk "UCVdQEYBdy0lBZz4wLSdxc6Q" "Nightbirde Music")
    (mk "UC3wOMk2hNc1f3tWKnPPuUMw" "NIKKI")
    (mk "UCgSO-swInyhWSUpgKIDrnjQ" "NOAHFINNCE")
    (mk "UC7z-QspogmmNjYGPAcypJpw" "nopejustnick")
    (mk "UCct1pE5fNVUdIR1aw3wxPew" "notdefining")
    (mk "UChhyfYkhuVrzmvDr-WqpDSw" "Not Even Emily")
    (mk "UC06DvgSsBrL24RNd_MXqNIg" "NumberONE")
    (mk "UCsJF0oPEzEQ_cN-nNMlK3wg" "nyaraVT")
    (mk "UC-yJOYXe_gw1dAnFQ5nMhWQ" "Ohh that's RICH")
    (mk "UCVvQREV_htIcqsb79TbmMsw" "One Challenge")
    (mk "UCqoZ40XymtdcOp2YOoMw9uw" "OneTopic")
    (mk "UCGtLR4lHUM5ovzvFxY4bDOA" "Othniel Eleazar")
    (mk "UCTjMNDSrfpReO6atYFIbriQ" "OwlOFC")
    (mk "UCPLMPHT-d8GZOqL_AHJFdQQ" "Parrot")
    (mk "UC4iraTePkGIYUGDsOl85BCw" "PF Jung")
    (mk "UCZHRPkcryTnlZFc-Ss5TiVw" "Phoenix Animations")
    (mk "UC3h2dpafuScrNGMYiUDwUiQ" "pierbii")
    (mk "UCzWC1TkgyBxxrHkqb6aZf1g" "PLAYGRND SERIES")
    (mk "UCVjh0oZ3Ug5-s3WX1awxblQ" "Popcorn")
    (mk "UCG0V362DBWHWavTM-JysGhw" "ProVZzz")
    (mk "UCynyM7W39qkv19a-0dFtEvA" "Pupzy")
    (mk "UCl9u8dvuTxlikeGSKH8fQ9A" "pxppycorpse")
    (mk "UC-eeR93Xb31Fk397K05vW_g" "Quintheo")
    (mk "UCHNEMZ69yEvdro8J2yS5xlQ" "RankiGuy")
    (mk "UCvtq2iUDaijoI4TEtUl_SVw" "𝓡𝓪𝓿𝓮𝓷")
    (mk "UCd7SCDxPEIYdXHkrpEmBXFA" "Real _ news")
    (mk "UCA4sF2INOBVv2aNglhNjNNA" "RICH CRAFTS")
    (mk "UCyF5AQlKSAm1OP-nX3lBrDg" "Rizky Aulia")
    (mk "UC6juUGSJu-RvOFi6DgJe1HQ" "Robert Tolppi")
    (mk "UCEXjRWyIHGDARGKJXQTi_yQ" "RockyDank")
    (mk "UCU9WJGMn_C5AB79J3mqUr7g" "Rorschach")
    (mk "UC0JJtK3m8pwy6rVgnBz47Rw" "Rotten Mango")
    (mk "UC8CuM9DxDFfJjTnZzT_23ZA" "Rumble Ron")
    (mk "UClv4rIrZ8yc6jqXEDXg6Z0Q" "Ryan Beard")
    (mk "UCXg2L_c6fFI-hH3lzsGOQkg" "Ryan Pictures")
    (mk "UCuMoaBp0ozi9c-67AFWtg-Q" "Samantha Lux")
    (mk "UCySTKqYThqBbKdEtzOjFhgg" "Sam Collins")
    (mk "UCUkSBEJC33xb-WU-pRimdkg" "SenpaiExtras")
    (mk "UC85eXsaeTD6cCCe6N2vB0dQ" "SGA")
    (mk "UCS1j8LH6zQ1xqmm06B8EOnQ" "Shark Tooth 🌀")
    (mk "UC2jwKIODVzbfQo1Doml-RWQ" "Shyaren")
    (mk "UChKQYI9z5rO_sdNjhwyyjSg" "Sideserf Cake Studio")
    (mk "UCmeOj4wjzP4LT5mEFyIp-LA" "Siffareeno")
    (mk "UCadMpX28EMXTCYYBg1DUJIg" "Skeeter Jean")
    (mk "UCZ7AeeVbyslLM_8-nVy2B8Q" "Skill Up")
    (mk "UC0fO_-gbN8r2ImmJ5-qLdeA" "Slop Roach")
    (mk "UCV4MuJHfEXNMjrjwcd4tHEA" "Slow News Day")
    (mk "UCCvcd0FYi58LwyTQP9LITpA" "Soft White Underbelly")
    (mk "UCFrmfDhZIom8coan10W819w" "SquidTips")
    (mk "UClQ3NafOy_42dJ0toK3QUKw" "Stay Wild")
    (mk "UCHVd0LM1g9S0cttDHkidEHA" "Steve Hofstetter")
    (mk "UCl16xaNY2arX3OzZBvTlsPQ" "Steve Terreberry")
    (mk "UCsIc8Tq-YSFY3BViLJG4d1A" "Stickman Talks")
    (mk "UCO8WCQsddotuNAH6-Pb_A0Q" "StreetCan")
    (mk "UCrWdPsIgE4GIWGiFUMHL4bQ" "Sumit 007")
    (mk "UCELBodZwev0kgJY5Cz61UPQ" "Talia Mar+")
    (mk "UC0rE2qq81of4fojo-KhO5rg" "Tanmay Bhat")
    (mk "UC73H5p3GP8b5N1f3hozIXyQ" "TBN Israel")
    (mk "UCud7qstfwb6EbgOVbD391rw" "TeasingOliver")
    (mk "UCmAjdwkUVd5tcSRAhwV5gnQ" "The Chloe Connection")
    (mk "UCpxlHiBcrDTRdypBBpF3xMg" "TheDuckingNerds")
    (mk "UCfio-qUSwEkYnEW4aVejO-Q" "The Enemies Project")
    (mk "UCM-eRxEc_TutiPIbOS1YYbw" "The Enforcer")
    (mk "UCc7p7J9tem8-18oJ0JzYOGg" "The Evaluator")
    (mk "UC8fsoduB61Ept6T84mRxFog" "The Moment")
    (mk "UCeny7bIu5FsrZ8C55dSmWSw" "The Necessary Conversation")
    (mk "UCVv0saCKl3TIt-0ZaE85ftA" "theneedtoknow")
    (mk "UC-jaY6dGP1RhvMIunvlLktA" "The Perseverance")
    (mk "UCVBD2a1uUkhX18B1WVcddzQ" "The Planet D")
    (mk "UCc6Dy2ljJEC2MKpCgwL4cLA" "The Punch Cut")
    (mk "UCmgvP1a5H32FE_yCyYGedEg" "thermia")
    (mk "UC_8TgFRkbkthGkiNoF9j1OA" "The Sesh")
    (mk "UC_wpodAWmXyQanNVof8vyFg" "The Soy Pill")
    (mk "UCfOkwqj6GoBfbdrBuFo4img" "The Thief One")
    (mk "UCtCZC8TvTGYaeEQBNx648qA" "The USA Stream")
    (mk "UCAhtLWZIbOZTl4LIZ9Uby4A" "The Watering Hole")
    (mk "UCIFk2uvCNcEmZ77g0ESKLcQ" "The Why Files")
    (mk "UCluH8hy4VXBZancjCepXccw" "Thinking Christian")
    (mk "UCUxiymg0tZtu7VXHCX0yMdA" "Thrittle")
    (mk "UCF5fVevjGC4eUg213wiZR5A" "Thug Theory")
    (mk "UCdKj0VzVR0Af0wzd7-68Avw" "Tim Henson")
    (mk "UC6O5FQjHayliiojkA7PaHTA" "TLS - Idiots At Work")
    (mk "UCURGLompzAFIuf8pTqnRQug" "TNT GRAFFITI")
    (mk "UCL2JgVl_8ExIo6Xxu0ArHug" "Toddally")
    (mk "UCRvsrJB_GhMhdLSA4ae5MqQ" "Tom Powell Jr")
    (mk "UCzdOLUx-iUO7wfWLpYLGxUQ" "TruthHurts_2026")
    (mk "UCPfeM2tm3T19uPf8pU3VHLg" "Ty Turner")
    (mk "UCl_vAxZpvbO-PFXdDu7EdHw" "Ujjwal")
    (mk "UCU63EiU7Y-8xcRntPIRVrzA" "Unpacked")
    (mk "UC3055Mg81-5X5l9t_DFAAxQ" "Urban Legends")
    (mk "UCFTHixpysIgljmKns7_7KfA" "venom")
    (mk "UC-Bgb7bgFDczAgfoKxFneFw" "Vera’s magic tv")
    (mk "UCcirgl5o8EPL7XeDsuIlQCg" "VERTICILE")
    (mk "UCBTE3ebHLYZAHRBQqaAUYhg" "Vexbakes")
    (mk "UCDCmxTR1x6ylSYlh_nrJHZQ" "Victoria Rose")
    (mk "UC6cMJ0aFn_DcxQ-t7goGACQ" "Violet💖")
    (mk "UCE7f7HEPnLRyWxx0f3EpLbA" "Waking Women")
    (mk "UCtuwNYL0ulHE6rRXivZvUXg" "WonderAuria")
    (mk "UC6my_lD3kBECBifeq0n2mdg" "X Factor Global")
    (mk "UC7LJSq2EkTUhHiNjpXg22mg" "yikes")
    (mk "UC_bMDjdLd6XPbROr1xcUCHw" "YinkaThatGuy")
    (mk "UCT6iAerLNE-0J1S_E97UAuQ" "YongYea")
    (mk "UCBR8-60-B28hp2BmDPdntcQ" "YouTube")
    (mk "UC2_X49uo6B7jSVSOwJSjznQ" "YukkoEX")
    (mk "UCLFwj9ugjp26bXAb3vDDPTQ" "Yuzuha!")
    (mk "UCt38KUTj72UEdWUdmnZHwOw" "ZoeTube")
    (mk "UC77tObmZQampes4mWZmAjZw" "unknown")
    (mk "UC8QNOIOoi63U0arTgU47vEQ" "unknown")
    (mk "UC9KblDFy0lrGLvC6w0qH78g" "unknown")
    (mk "UCCLLvHL_ITnyhEKJjB3-wxg" "unknown")
    (mk "UCfO3B57E6NpIn-KsVjvmLLw" "unknown")
    (mk "UCg24p0qlHK6TL3DCAiecppQ" "unknown")
    (mk "UCG38HE2LucNPGFu--W7BfUA" "unknown")
    (mk "UCizqDT7CpXE3e4aBlx1fiEw" "unknown")
    (mk "UCL_KcyTqjIT5uHi19qZ8zIw" "unknown")
    (mk "UCM32F09Rdb0rRomsYvHJp2g" "unknown")
    (mk "UC_m3q4psNrO7XoZohSiBA8g" "unknown")
    (mk "UCNcFMVXgOCl5BOtbAechM5A" "unknown")
    (mk "UCpOKZqwLz8Uk4TMXJF3AnLA" "unknown")
    (mk "UCrSVc3he0AQD_CEqOIVdvyg" "unknown")
    (mk "UCTyWEQvhuYNKpzYCtA3AzCg" "unknown")
    (mk "UCvBL76p8GgJZExW_0k5BIAw" "unknown")
    (mk "UCVFm-5smU7mNREPXtT78Jvw" "unknown")
    (mk "UCWvF8GrHIQLRqgVpKAscbeQ" "unknown")
    (mk "UCxlMUXEbzCTbV6kL1p7lcWQ" "unknown")
  ];
in {
  programs.freetube.settings = {
    channelsHidden = builtins.toJSON (
      politicalCommentary
      ++ politicalStreamers
      ++ newsNetworks
      ++ localNews
      ++ internationalNews
      ++ printMedia
      ++ bbcNonNews
      ++ entertainment
      ++ educationalAndEssay
      ++ streamers
      ++ clipChannels
      ++ reactionChannels
      ++ gaming
      ++ kidsAndFamily
      ++ musicArtists
      ++ talentShows
      ++ viralAndMemeReuploads
      ++ sports
      ++ lowEffort
      ++ misc
    );
  };
}
