{
  inputs,
  lib,
  hostname,
  hostConfig,
  ...
}: {
  imports = [
    inputs.dms.homeModules.dank-material-shell
    inputs.dms.homeModules.niri
    inputs.dms-plugin-registry.homeModules.default
  ];

  #--------------------------------------------------------------------#
  #-- DankMaterialShell SETTINGS --#
  #--------------------------------------------------------------------#
  programs.dank-material-shell = {
    enable = true;

    #--- Niri-specific configuration
    niri = {
      enableSpawn = true; # Auto-start DMS with niri
    };

    #--- Plugins
    plugins = {
      amdGpuMonitor.enable = true;
      claudeCodeUsage.enable = hostConfig.claude.enable;
      powerUsagePlugin.enable = lib.mkIf (hostname == "laptop") true;
      screenRecorder.enable = true;
    };

    #--- Core features
    enableSystemMonitoring = true; # System monitoring widgets (dgop)
    enableVPN = true; # VPN management widget
    enableDynamicTheming = false; # Wallpaper-based theming (matugen)
    enableAudioWavelength = true; # Audio visualizer (cava)
    enableCalendarEvents = false; # Calendar integration (khal) - disabled: khal-0.13.0 broken in nixpkgs
    enableClipboardPaste = true; # Clipboard pasting via wtype
  };

  #--------------------------------------------------------------------#
  #-- DankMaterialShell NIRI KEYBINDS --#
  #--------------------------------------------------------------------#
  programs.niri.settings.binds = let
    dms = action: ["dms" "ipc" "call"] ++ (lib.splitString " " action);
  in {
    #--- DankMaterialShell Controls
    "Mod+A".action.spawn = dms "spotlight toggle"; # Application Launcher
    "Mod+V".action.spawn = dms "clipboard toggle"; # Clipboard Manager
    "Mod+P".action.spawn = dms "processlist toggle"; # Task Manager
    "Mod+Comma".action.spawn = dms "settings toggle"; # Settings
    "Mod+N".action.spawn = dms "notepad toggle"; # Notepad
    "Mod+K".action.spawn = dms "powermenu toggle"; # Power Menu
    "Mod+W".action.spawn = dms "dankdash wallpaper"; # Browse Wallpapers
    "Mod+Shift+N".action.spawn = dms "night toggle"; # Night Mode Toggle
    "Mod+L".action.spawn = dms "lock lock"; # Toggle lock screen
    "Mod+I".action.spawn = dms "inhibit toggle"; # Toggle idle inhibit
    "Mod+slash".action.spawn = dms "keybinds toggle niri"; # Show Keybind Cheatsheet
    "Mod+Insert".action.spawn = dms "screenRecorder toggleRecording"; # Screen Recorder
    "Mod+R".action.spawn = ["systemctl" "--user" "restart" "dms.service"]; # Restart DMS

    #--- Audio controls
    "XF86AudioRaiseVolume".action.spawn = dms "audio increment 3"; # Volume Up
    "XF86AudioLowerVolume".action.spawn = dms "audio decrement 3"; # Volume Down
    "XF86AudioMute".action.spawn = dms "audio mute"; # Mute Audio
    "XF86AudioMicMute".action.spawn = dms "audio micmute"; # Mute Microphone

    #--- Brightness controls
    "XF86MonBrightnessUp".action.spawn = dms "brightness increment 5"; # Brightness Up
    "XF86MonBrightnessDown".action.spawn = dms "brightness decrement 5"; # Brightness Down
  };

  #--------------------------------------------------------------------#
  #-- DECLARATIVE DankMaterialShell SETTINGS --#
  #--------------------------------------------------------------------#
  home.file = {
    #--- DMS Main Settings
    ".config/DankMaterialShell/settings.json" = {
      text = builtins.toJSON (lib.importJSON ./settings.json);
    };

    #--- DMS Clipboard Settings
    ".config/DankMaterialShell/clsettings.json" = {
      source = ./clsettings.json;
    };

    ".config/DankMaterialShell/cheatsheets/niri-dms.json" = {
      source = ./niri-cheatsheet.json;
    };

    #--- Niri KDL configuration files (auto-generated by home-manager)
    ".config/niri/dms/binds.kdl" = {
      text = "// DMS keybinds are configured via niri settings\n";
    };

    ".config/niri/dms/colors.kdl" = {
      text = "// Colors configured via Catppuccin theme\n";
    };

    ".config/niri/dms/outputs.kdl" = {
      text = "// Outputs configured in niri settings\n";
    };

    ".config/niri/dms/alttab.kdl" = {
      text = "// Alt-Tab configuration (DMS)\n";
    };

    ".config/niri/dms/layout.kdl" = {
      text = "// Layout configuration (DMS)\n";
    };

    ".config/niri/dms/wpblur.kdl" = {
      text = ''
        // Wallpaper blur configuration (DMS)
        blur {
            passes 4
            offset 4.0
            noise 0.0
            saturation 1.2
        }

        window-rule {
            background-effect {
                blur true
                xray true
            }
        }
      '';
    };
  };
}
